### ISSUE TITLE
Cookie Persistence configuration

### ISSUE THREAD

**Issue by Luxiter** [Aidaho12/haproxy-wi#10]
Hi 
we can suggest new features for cookie persistence 
One usefully method for cookie is dynamic with dynamic-cookie-key

i will show an example

frontend ExampleFront443
    bind xxx.xxx.xxx.xxx:443 ssl crt /etc/haproxy/certificato-apache.pem
    maxconn 100000
    mode http
    option forwardfor
    acl host-mysite hdr(Host) -i www.example.com
    block if !host-mysite
    http-request set-header X-Client-IP %[src]
       default_backend ExampleDMZ443

backend ExampleDMZ443
   mode http
   option forwardfor
   http-request set-header X-Forwarded-Port %[dst_port]
   http-request add-header X-Forwarded-Proto https if { ssl_fc }
   http-request set-header Host www.example.com
   option httpchk HEAD / HTTP/1.1\r\nHost:localhost
   dynamic-cookie-key your-custom-key-string
   cookie SERVERID insert indirect nocache dynamic
   server leportalfe01 xxx.xxx.xxx.xxx:443 check ssl verify none
   server leportalfe02 xxx.xxx.xxx.xxx:443 check ssl verify none

**Comment by Aidaho12** [comment]
Ok, i will add it in next release into list options
--
Отправлено из Mail.Ru для Android вторник, 08 мая 2018г., 15:52 +06:00 от Luxiter  notifications@github.com :

**Comment by Aidaho12** [comment]
Hi, look:
![default](https://user-images.githubusercontent.com/20718301/39959601-9ef151ee-5635-11e8-82c8-930126907a0f.png)
