### ISSUE TITLE
Configuration does not "show"

### ISSUE THREAD

**Issue by nichtdu92** [Aidaho12/haproxy-wi#100]
I am facing a problem with the show feature that organizes the configuration into drop down menus. If i hit edit i can see the config however the features "show, map, compare" don't work. Does anyone else have the problem as well?

**Comment by Aidaho12** [comment]
For me work fine. Show print screen and httpd error log

**Comment by nichtdu92** [comment]
No much to show but here you go:
https://ibb.co/T2d5Xf8

Log Entries when option is triggered:
-----------------------------------------------------------------------------------------------
[Mon Feb 04 12:16:21.903841 2019] [cgi:error] [pid 5593] [client 10.17.34.131:22323] AH01215: Traceback (most recent call last):, referer: http://ha-mgmt/app/config.py
[Mon Feb 04 12:16:21.903908 2019] [cgi:error] [pid 5593] [client 10.17.34.131:22323] AH01215:   File "/var/www/haproxy-wi/app/options.py", line 8, in <module>, referer: http://ha-mgmt/app/config.py
[Mon Feb 04 12:16:21.903919 2019] [cgi:error] [pid 5593] [client 10.17.34.131:22323] AH01215:     import ovw, referer: http://ha-mgmt/app/config.py
[Mon Feb 04 12:16:21.903947 2019] [cgi:error] [pid 5593] [client 10.17.34.131:22323] AH01215:   File "/var/www/haproxy-wi/app/ovw.py", line 15, referer: http://ha-mgmt/app/config.py
[Mon Feb 04 12:16:21.903974 2019] [cgi:error] [pid 5593] [client 10.17.34.131:22323] AH01215:     async def async_get_overview(serv1, serv2):, referer: http://ha-mgmt/app/config.py
[Mon Feb 04 12:16:21.903991 2019] [cgi:error] [pid 5593] [client 10.17.34.131:22323] AH01215:             ^, referer: http://ha-mgmt/app/config.py
[Mon Feb 04 12:16:21.904011 2019] [cgi:error] [pid 5593] [client 10.17.34.131:22323] AH01215: SyntaxError: invalid syntax, referer: http://ha-mgmt/app/config.py
[Mon Feb 04 12:16:21.917753 2019] [cgi:error] [pid 5593] [client 10.17.34.131:22323] End of script output before headers: options.py, referer: http://ha-mgmt/app/config.py

**Comment by nichtdu92** [comment]
Python 3.5.6

**Comment by Aidaho12** [comment]
Hmm... interesting... ok, use web debugger (ctr+shift+I) and check parameters what sends when you tap "show" or some else

**Comment by nichtdu92** [comment]
I get an 500 Error with the following GET request
http://ha-mgmt/app/options.py?serv=10.17.34.161&act=configShow&token=735222da-8935-430b-9ae6-c12ecef855c3

**Comment by Aidaho12** [comment]
Can't reproduce error... try relogin, and delete all cookies

**Comment by nichtdu92** [comment]
deleted cookies, logged in, same problem. I had this issue on another install as well...

**Comment by nichtdu92** [comment]
i fixed the problem by changing all headers of the python files to call python3.5. 

#!/usr/bin/env python3       -->        #!/usr/bin/env python3.5
