### ISSUE TITLE
Problem conecting to local haproxy server

### ISSUE THREAD

**Issue by aperezaudifilm** [Aidaho12/haproxy-wi#102]
Hello, I installed HAProxy v1.9.4  over NethServer (CentOS) release 7.6, and everything seems to work fine with a simple configuration. We can see stats for it in next image:

![02](https://user-images.githubusercontent.com/47574253/52661546-981d2e00-2f02-11e9-8802-566aa2c9c06c.png)

On same server I installed also HAProxy-WI following README instrucctions for RHEL 7 and when I connect to web management it doesn't seem to detect local installation, because going to haproxy > configs menu doesn't display any entry in Choose Server option, so I can't configure anything else:

![01](https://user-images.githubusercontent.com/47574253/52661303-07dee900-2f02-11e9-8d73-585a93352b98.png)

![02](https://user-images.githubusercontent.com/47574253/52662159-ec74dd80-2f03-11e9-8aaa-76396a0536d9.png)

I attach my simple haproxy.cfg, do you know what could I check or test to see what isn't not working fine?? 
global
 log /dev/log local0
 log /dev/log local1 notice
 chroot /var/lib/haproxy
 stats socket /run/haproxy/admin.sock mode 660 level admin
 stats timeout 30s
 user haproxy
 group haproxy
 daemon
defaults
 log global
 mode http
 option httplog
 option dontlognull
 timeout connect 5000
 timeout client 50000
 timeout server 50000
frontend http_front
 bind *:1080
 stats uri /haproxy?stats
 default_backend http_back
backend http_back
 balance roundrobin
 server WebServer03A 192.168.201.31:80 check
 server WebServer03B 192.168.201.32:80 check

Config file is as follows haproxy-wi.cfg:
[main]
#Path to files destination
fullpath = /var/www/haproxy-wi
cgi_path = ${fullpath}/app/
log_path = ${fullpath}/log/
cert_local_dir = ${cgi_path}/certs/

[configs]
#Dir where configs will be save
haproxy_save_configs_dir = ${main:fullpath}/configs/hap_config/
kp_save_configs_dir = ${main:fullpath}/configs/kp_config/

[mysql]
#Enable MySQL DB. Default will be used Sqlite DB. Default disable
enable = 0
mysql_user = haproxy-wi
mysql_password = haproxy-wi
mysql_db = haproxywi
mysql_host = 127.0.0.1

In haproxy-wi.error.log I can see (cuted first part):
AH01215: Traceback (most recent call last):
AH01215:   File "/var/www/haproxy-wi/app/overview.py", line 46, in <module>
AH01215:     token = token)
AH01215:   File "/usr/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
AH01215:     return self.environment.handle_exception(exc_info, True)
AH01215:   File "/usr/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
AH01215:     reraise(exc_type, exc_value, tb)
AH01215:   File "/usr/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
AH01215:     raise value.with_traceback(tb)
AH01215:   File "templates/ovw.html", line 1, in top-level template code
AH01215:     {% extends "base.html" %}
AH01215:   File "templates/base.html", line 215, in top-level template code
AH01215:     {% block content %}{% endblock %}
AH01215:   File "templates/ovw.html", line 6, in block "content"
AH01215:     {% if role <= 1 %}
AH01215: TypeError: unorderable types: NoneType() <= int()
AH01215: Traceback (most recent call last):
AH01215:   File "/var/www/haproxy-wi/app/overview.py", line 37, in <module>
AH01215:     role = sql.get_user_role_by_uuid(user_id.value),
AH01215: AttributeError: 'NoneType' object has no attribute 'value'

Best regards,
Alex

**Comment by Aidaho12** [comment]
Hello

Show me please the servers page

**Comment by aperezaudifilm** [comment]
Thanks for quick answer... :)
Servers page is empty, do I need to add a server to connect to a localhost haproxy?
![03](https://user-images.githubusercontent.com/47574253/52662702-2beff980-2f05-11e9-931f-08bc89476633.png)

**Comment by Aidaho12** [comment]
Add server before start admin them :)

**Comment by aperezaudifilm** [comment]
I added a server with propper credentials to connect to localhost, but I can't choose any server in Configs menu:
![05a - auth ok](https://user-images.githubusercontent.com/47574253/52664189-aa9a6600-2f08-11e9-8ee5-c6f3d3c5c46e.png)
![05b - auth ok](https://user-images.githubusercontent.com/47574253/52664195-ad955680-2f08-11e9-9e81-4806cd49fb49.png)

**Comment by Aidaho12** [comment]
try use IP address

**Comment by aperezaudifilm** [comment]
Same result, server says "Connect accept" but then I can't choose it:
![05c - auth ok](https://user-images.githubusercontent.com/47574253/52664841-53959080-2f0a-11e9-8c2d-774a1083c376.png)

**Comment by Aidaho12** [comment]
It because you checked "Virt", uncheck it

**Comment by aperezaudifilm** [comment]
Fantastic, server appears now!! I'll start testing all the configurations...
![06a - server ok](https://user-images.githubusercontent.com/47574253/52665441-e3880a00-2f0b-11e9-896f-fc57bdafe1c7.png)
![06b - server ok](https://user-images.githubusercontent.com/47574253/52665447-e5ea6400-2f0b-11e9-884c-d0a40cab46ea.png)


Thanks very much.

**Comment by Ravan18** [comment]
Hi,
I got this error during am testing, could you help me pls
![HA](https://user-images.githubusercontent.com/58604104/70553454-bd73da80-1bad-11ea-9e65-0524158ab519.JPG)

**Comment by Aidaho12** [comment]
Hi,

Show apache error log

**Comment by Ravan18** [comment]
![logs](https://user-images.githubusercontent.com/58604104/70554393-9fa77500-1baf-11ea-8459-96588e36696a.JPG)

**Comment by Ravan18** [comment]
it's there something wrong with my configure?

**Comment by Aidaho12** [comment]
🤦 error log, not access log

**Comment by Aidaho12** [comment]
Without log I can't say anything, I'm not telepathic

**Comment by Ravan18** [comment]
![error](https://user-images.githubusercontent.com/58604104/70554853-80f5ae00-1bb0-11ea-80d7-a3adb66d6297.JPG)

**Comment by Aidaho12** [comment]
Not that error log, try again)

**Comment by Ravan18** [comment]
![logs1](https://user-images.githubusercontent.com/58604104/70555291-5a844280-1bb1-11ea-9edd-86776a550b54.JPG)
which one?

**Comment by Aidaho12** [comment]
Let's think... We are going to use haproxy-wi, according haproxy-wi.error.log

**Comment by Ravan18** [comment]
![HA-log](https://user-images.githubusercontent.com/58604104/70555558-dbdbd500-1bb1-11ea-9496-66e1e7875a23.JPG)
here HA error log

**Comment by Aidaho12** [comment]
Read how set mysql db correct

**Comment by Ravan18** [comment]
I'm checking

**Comment by Aidaho12** [comment]
You can donate to support project and I will set for you it. And will support haproxy-wi

**Comment by Ravan18** [comment]
any advice to fix this issue pls?

**Comment by Aidaho12** [comment]
Read manuals carefully, there is all the information

**Comment by Ravan18** [comment]
let me re-check it
