### ISSUE TITLE
Active internet connection is required

### ISSUE THREAD

**Issue by v-masterman** [Aidaho12/haproxy-wi#103]
Can you please provide some info regarding HAproxy-wi works fine when I have active internet connection but nothing works when no internet ?

**Comment by v-masterman** [comment]
Great tool amazing but  cant use it since internet is is required for all JS-jquery , well I downloaded and modified each html where .JS and .CSS required to go out internet, now I can login but rest of the feature does not work like over view , config view etc.. it says authentication failed.etc..

**Comment by Aidaho12** [comment]
May be you forgot or mistake with js-cookie lib
--
Отправлено из Mail.Ru для Android суббота, 16 февраля 2019г., 06:10 +03:00 от v-masterman  notifications@github.com :

**Comment by v-masterman** [comment]
Thanks for the response Aidaho12 , can you please tell me where do I reference js-coolie Lib ?

**Comment by Aidaho12** [comment]
It's sets in head teg

**Comment by v-masterman** [comment]
Aidaho12 , thanks for great help, almost there , the only last issue if you can help me with,
   metrics_out.html I believe get generated each time i go to metrics page and it re-rights to go to 
Can you please help me to find out where that' s coming from ? once I correct that I can then have fully working haproxy-wi without internet, I really appreciate your help and time .  

<!DOCTYPE html>
<html lang="en">
  
  <head>
    
      <meta charset="utf-8">
      <title>Bokeh Plot</title>
      
      
        
          
        <link rel="stylesheet" href="https://cdn.pydata.org/bokeh/release/bokeh-0.13.0.min.css" type="text/css" />
        
        
          
        <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-0.13.0.min.js"></script>
        <script type="text/javascript">
            Bokeh.set_log_level("info");
        </script>
        
      
      
    
  </head>
  
  
  <body>

**Comment by Aidaho12** [comment]
Ou... This code generate python lib... and I even don't know how do it without internet... may be put JS code in bottom metrics.html and code will be do that will change ```https://cdn.pydata.org/...``` to local scripts

**Comment by v-masterman** [comment]
Thank you Aidaho12,
      I found the solution searching google for Bokeh lib offline. simply changed output_file with mode='inline'  creates the code in side the html instead of cdn ref. so basically I had to modify options.py for both output_file ( "metrics_out.html") to output_file ("metrics_out.html", mode='inline') did the trick.
    So now I have a solution that I can use in closed environment without internet . I am so happy to see your project . your work is amazing , Thank you

**Comment by Aidaho12** [comment]
It's cool!
 
Maybe you will fork the project, and add your changes to them and after do pull request?

**Comment by v-masterman** [comment]
Aidaho12,
    I do not know how to fork the project , its your great work , so I would send it to you directly and if you can test verify and upload ?
   Let me know if it good , I can send you all the steps I took to make it work offline , you than test\verify and upload ?

**Comment by ducttapecoder-vt** [comment]
@v-masterman Were you to able to make it work as is? I'm still seeing calls to code.jquery.com due to the app/template/base.html file. Seems like this is duplicate issue of https://github.com/Aidaho12/haproxy-wi/issues/86

**Comment by Aidaho12** [comment]
I have made mistake with base.html, now will be fine
