### ISSUE TITLE
cannot install WAF/HAproxy/Keepalive

### ISSUE THREAD

**Issue by prinsd001** [Aidaho12/haproxy-wi#104]
Hi,

i cannot install anything from the GUI. is there any log i can check?

**Comment by Aidaho12** [comment]
You can check apache errors log or run scripts manually. They're in /tmp at the servers
--
Отправлено из Mail.Ru для Android суббота, 16 февраля 2019г., 13:12 +03:00 от prinsd001  notifications@github.com :
