### ISSUE TITLE
Docker volume for persistence

### ISSUE THREAD

**Issue by PaulGrimshaw** [Aidaho12/haproxy-wi#105]
In the docker service create command, it suggests mounting an external drive into `/var/www/haproxy-wi/app`, however when we do this none of the python files appear there and it doesn't run.

Removing the volume works fine.

Is it possible to move the sql lite db by configuration to a different location, i.e. an empty directory, so we can mount to it without affecting the rest of the app?

**Comment by Aidaho12** [comment]
I am sad, but no (

Only if you edit the code to find sql db and add path in the haproxy-wi.cfg... or you can use Mysql :)

**Comment by PaulGrimshaw** [comment]
ok.  I could mount the db file in specifically i guess, rather than the directory.  Will try this, copying a blank db out of the container and mounting it back in directly

**Comment by PaulGrimshaw** [comment]
This worked great.  See below a script to help others:

```
mkdir -p "$PWD/haproxy-wi/"

if [[ ! -f "$PWD/haproxy-wi/haproxy-wi.db" ]]; then
    cp "$PWD/blank-haproxy-wi.db" "$PWD/haproxy-wi/haproxy-wi.db"
fi

docker service create \
    --name haproxy-wi \
    --mount type=bind,source="$PWD/haproxy-wi/haproxy-wi.db",target=/var/www/haproxy-wi/app/haproxy-wi.db \
    -p 8080:80 \
aidaho/haproxy-wi
```
