### ISSUE TITLE
Installer issues

### ISSUE THREAD

**Issue by Flashtekuk** [Aidaho12/haproxy-wi#107]
Greetings,

A couple of issues found in the install.sh script when installing on Debian stable.

1, sudo not present by default, and not added by script... but presumed to be present. Consider adding this to the apt-get install
2, openldap-dev package not available, may not even be required as the ldap dev packages are added in as dependents

HTH

**Comment by Aidaho12** [comment]
Hi
1. In the instructions say ''' sudo install.sh '''...
2. Ok, thank you
--
Отправлено из Mail.Ru для Android среда, 27 февраля 2019г., 23:36 +03:00 от Flashtekuk  notifications@github.com :

**Comment by Flashtekuk** [comment]
Greetings,

So, you want me to 'sudo' run a script that then invokes 'sudo' multiple
times...? Doesn't make much sense to me. Why not take a belt and braces
approach and try to install it regardless... if it's already installed apt
will ignore your request and continue, if it's not installed it'll install
it...

Neil

**Comment by Flashtekuk** [comment]
Additionally, you mention 'socat' as a requirement, I notice this is also not installed... perhaps add that to the "apt-get install" ?

**Comment by Aidaho12** [comment]
if it doesn't make sense to you, why are you doing this? do not install and problems with meaning will not be

And what do you suggest? if you want to fix something with sudo or apt-get, correct it and make a pool request, and this is idle chatter
