### ISSUE TITLE
the Haproxy-wi was blocking when 'converting file'

### ISSUE THREAD

**Issue by erpkot** [Aidaho12/haproxy-wi#108]
When dos2unix is converting the file, the HAproxy-wi is blocked, the terminal printed the log message, I tried to find the error of CGI or HAproxy-wi, but I found nothing, did any guy know how do I resolve this problem? thanks.

_this case will reproduce when adding Listeners._

My system:
Ubuntu 18.04.2 LTS 64-bit

Terminal Message : 
`[Mon Apr 01 11:14:30.535329 2019] [cgi:error] [pid 832:tid 139996765857536] [client 127.0.0.1:42846] AH01215: converting file /var/www/haproxy-wi/configs/hap_config/192.168.126.173-2019-04-01.03:14:29.cfg to Unix format...: /var/www/haproxy-wi/app/add.py, referer: http://localhost:19977/app/add.py`

pls see my gif:
![myp](https://user-images.githubusercontent.com/40824621/55301628-2d9f5d80-5470-11e9-98fc-52ad9a25c2fb.gif)
HAproxy-WI is blocking, the config wasn't saved, 
btw: the haproxy has been in the sbin folder, the javascript didn't print any error log.

I saw the #80 and #85, #78, but they didn't resolve my problem.

**Comment by Aidaho12** [comment]
Problem not in dos2unix, that is normally message from dos2unix... There is something another

**Comment by cryogenx** [comment]
im seeing a similar issue when saving, was there ever a resolution to this?
