### ISSUE TITLE
Broken links in install scripts

### ISSUE THREAD

**Issue by SysadminEU1** [Aidaho12/haproxy-wi#111]
Hey

I am using Centos 7 and the links you are using no longer works, script to install waf nolonger works.

[root@localhost tmp]# ./waf.sh
error: Need HAProxy version 1.8 or later <a title="Close" id="errorMess"><b>X</b></a>
[root@localhost tmp]# haproxy -ver
HA-Proxy version 1.8.1 2017/12/03
Copyright 2000-2017 Willy Tarreau <willy@haproxy.org>

The link are broken
wget -O /tmp/yajl-devel-2.0.4-4.el7.x86_64.rpm http://rpmfind.net/linux/centos/

It is true on many links, much is broken in this version.

**Comment by SysadminEU1** [comment]
Even if you find a replacement path, waf does not work

2019-05-03 10:05:02 (1.58 MB/s) - ‘/tmp/modsecurity-2.9.2.tar.gz’ saved [4298993/4298993]

configure: error: pcre library is required
Can't compile waf application

**Comment by Aidaho12** [comment]
Install pcre-devel first
--
Отправлено из Mail.ru для Android пятница, 03 мая 2019г., 11:06 +03:00 от SysadminEU1  notifications@github.com :

**Comment by Aidaho12** [comment]
Fixed broken links

**Comment by SysadminEU1** [comment]
I used 
yum install pcre-devel

The result is
Can't compile waf application

More detailed output here.
[root@localhost tmp]# ./waf.sh
error: Need HAProxy version 1.8 or later <a title="Close" id="errorMess"><b>X</b                                                                                                                                                             ></a>
--2019-05-03 10:21:54--  http://rpmfind.net/linux/centos/7.6.1810/os/x86_64/Pack                                                                                                                                                             ages/yajl-devel-2.0.4-4.el7.x86_64.rpm
Resolving rpmfind.net (rpmfind.net)... 195.220.108.108
Connecting to rpmfind.net (rpmfind.net)|195.220.108.108|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13792 (13K) [application/x-rpm]
Saving to: ‘/tmp/yajl-devel-2.0.4-4.el7.x86_64.rpm’

100%[======================================>] 13,792      --.-K/s   in 0s

2019-05-03 10:21:54 (70.9 MB/s) - ‘/tmp/yajl-devel-2.0.4-4.el7.x86_64.rpm’ saved                                                                                                                                                              [13792/13792]

--2019-05-03 10:21:54--  http://mirror.centos.org/centos/7/os/x86_64/Packages/li                                                                                                                                                             bevent-devel-2.0.21-4.el7.x86_64.rpm
Resolving mirror.centos.org (mirror.centos.org)... 195.154.220.72, 2001:49f0:d03                                                                                                                                                             4:1::10
Connecting to mirror.centos.org (mirror.centos.org)|195.154.220.72|:80... connec                                                                                                                                                             ted.
HTTP request sent, awaiting response... 200 OK
Length: 86564 (85K) [application/x-rpm]
Saving to: ‘/tmp/libevent-devel-2.0.21-4.el7.x86_64.rpm’

100%[======================================>] 86,564      --.-K/s   in 0.05s

2019-05-03 10:21:54 (1.67 MB/s) - ‘/tmp/libevent-devel-2.0.21-4.el7.x86_64.rpm’                                                                                                                                                              saved [86564/86564]

--2019-05-03 10:21:55--  https://www.modsecurity.org/tarball/2.9.2/modsecurity-2                                                                                                                                                             .9.2.tar.gz
Resolving www.modsecurity.org (www.modsecurity.org)... 204.13.200.240
Connecting to www.modsecurity.org (www.modsecurity.org)|204.13.200.240|:443... c                                                                                                                                                             onnected.
HTTP request sent, awaiting response... 200 OK
Length: 4298993 (4.1M) [application/x-gzip]
Saving to: ‘/tmp/modsecurity-2.9.2.tar.gz’

100%[======================================>] 4,298,993   2.83MB/s   in 1.5s

2019-05-03 10:21:57 (2.83 MB/s) - ‘/tmp/modsecurity-2.9.2.tar.gz’ saved [4298993                                                                                                                                                             /4298993]

config.c: In function ‘process_command_config’:
config.c:1107:5: warning: passing argument 1 of ‘apr_filepath_root’ from incompa                                                                                                                                                             tible pointer type [enabled by default]
     status = apr_filepath_root(&rootpath, &incpath, APR_FILEPATH_TRUENAME | APR                                                                                                                                                             _FILEPATH_NATIVE, ptemp);
     ^
In file included from /usr/include/apr-1/apr_file_io.h:29:0,
                 from /usr/include/apr-1/apr_network_io.h:26,
                 from /usr/include/apr-1/apr_buckets.h:29,
                 from /usr/include/httpd/util_filter.h:26,
                 from /usr/include/httpd/http_core.h:32,
                 from config.c:18:
/usr/include/apr-1/apr_file_info.h:336:27: note: expected ‘const char **’ but ar                                                                                                                                                             gument is of type ‘char **’
 APR_DECLARE(apr_status_t) apr_filepath_root(const char **rootpath,
                           ^
config.c:1107:5: warning: passing argument 2 of ‘apr_filepath_root’ from incompa                                                                                                                                                             tible pointer type [enabled by default]
     status = apr_filepath_root(&rootpath, &incpath, APR_FILEPATH_TRUENAME | APR                                                                                                                                                             _FILEPATH_NATIVE, ptemp);
     ^
In file included from /usr/include/apr-1/apr_file_io.h:29:0,
                 from /usr/include/apr-1/apr_network_io.h:26,
                 from /usr/include/apr-1/apr_buckets.h:29,
                 from /usr/include/httpd/util_filter.h:26,
                 from /usr/include/httpd/http_core.h:32,
                 from config.c:18:
/usr/include/apr-1/apr_file_info.h:336:27: note: expected ‘const char **’ but ar                                                                                                                                                             gument is of type ‘char **’
 APR_DECLARE(apr_status_t) apr_filepath_root(const char **rootpath,
                           ^
--2019-05-03 10:22:38--  http://www.haproxy.org/download/src/haproxy-.tar.gz
Resolving www.haproxy.org (www.haproxy.org)... 51.15.8.218
Connecting to www.haproxy.org (www.haproxy.org)|51.15.8.218|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-03 10:22:38 ERROR 404: Not Found.

tar: This does not look like a tar archive

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
./waf.sh: line 80: cd: /tmp/haproxy-/contrib/modsecurity: No such file or direct                                                                                                                                                             ory
make: *** No targets specified and no makefile found.  Stop.
mv: cannot stat ‘/tmp/haproxy-/contrib/modsecurity/modsecurity’: No such file or                                                                                                                                                              directory
Can't compile waf application
