### ISSUE TITLE
Install_haproxy.sh - many errors cannot install haproxy

### ISSUE THREAD

**Issue by SysadminEU1** [Aidaho12/haproxy-wi#112]
The Default install script does not work on Centos 7 with yum update -y

Broken Links and WAF conflicts, that ensures that you cannot install haproxy.

And variables does not function as expected.
When the scripts create

bash -c 'echo "" > /tmp/haproxy.cfg'
bash -c cat << EOF > /tmp/haproxy.cfg
global

The variables 
stats socket *:$SOCK_PORT level admin
server-state-file $STAT_FILE 
bind *:$STAT_PORT
stats auth $STATS_USER:$STATS_PASS

Does not work and the results are that you are left with "Haproxy cannot connect", correcting these mistakes manually - will get haproxy to report the version.

But you cannot see the statitics
/app/viewsttats.py?serv=

Reports
You need a valid user and password to access this content.

**Comment by SysadminEU1** [comment]
No solution - bug persists.

**Comment by Aidaho12** [comment]
Hi,

Now it's installs with ansible, and errors has to gone
