### ISSUE TITLE
Workers Down

### ISSUE THREAD

**Issue by MichaelCowe** [Aidaho12/haproxy-wi#114]
metrics workers and checker workers are down.

First time install

**Comment by Aidaho12** [comment]
You enabled metrics and checkers at least on one server?

**Comment by MichaelCowe** [comment]
I know this might sound simple but how do you do that, I am very new to Linux and Linux based apps.

I have the stats page enabled for Haproxy





Michael Cowe | Technical Manager

Phone: 01915193700

[cid:DiamondGroupLogo_eea6fb67-6314-41e6-8a8c-65afce129474.png]<https://diamond-group.net/>


Follow us:
[cid:fb-icon_67a6dda4-5f36-472e-9c8c-929c1320b95c.gif]<https://www.facebook.com/DiamondGroupNE>
[cid:tw-icon_1f3adbae-e673-40f9-a1bd-b94098f068db.gif]<https://twitter.com/diamondgroupne>
[cid:Instagram_faebfdc1-366b-4672-831a-8bd47ed5c713.png]<https://www.instagram.com/diamonditne/>
[cid:LinkedIn_6dcebfaa-96d9-4e26-b317-abcd5f4d8982.png]<https://uk.linkedin.com/company/diamond-group-ltd><https://www.youtube.com/user/CodeTwoChannel#p/u>


[cid:DiamondLogoDivisionsBannerMarch2016PNG_99fc9e53-6303-455c-8c49-5253054c1237.png]<https://Diamond-group.net>

[cid:3CX_1d62d835-72f3-42c3-87c7-df2ef6d1e1c4.png]<https://www.diamond-group.net/about-us/accreditations/diamond-have-been-awarded-3cx-silver-partner-status/>


[cid:CySA+cecertifiedlogo_68111118-960a-4c9a-97da-2287951fa48c.png]<https://www.diamond-group.net/news/cyber-security-accreditation/>


[cid:GOLD-customer-service-logo_6318178a-ac18-4b27-8390-3fb9c44f9d9f.jpg]<https://www.diamond-group.net/news/diamond-awarded-gold/>


Diamond Group, Diamond House, Kingsway North, Team Valley, Gateshead, NE11 0JH

Diamond Group accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. If you are not the intended recipient, you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.


<https://www.diamond-group.net/news/diamond-awarded-gold/>

On Mon, May 27, 2019 at 12:00 PM +0100, "Pavel Loginov" <notifications@github.com<mailto:notifications@github.com>> wrote:


You enabled metrics and checkers at least on one server?

-

**Comment by Aidaho12** [comment]
You have to enable it on the page where you added servers

**Comment by MichaelCowe** [comment]
Got it, thanks, didn’t realise what they did

Regards


Michael Cowe | Technical Manager

Phone: 01915193700

[cid:DiamondGroupLogo_eea6fb67-6314-41e6-8a8c-65afce129474.png]<https://diamond-group.net/>


Follow us:
[cid:fb-icon_67a6dda4-5f36-472e-9c8c-929c1320b95c.gif]<https://www.facebook.com/DiamondGroupNE>
[cid:tw-icon_1f3adbae-e673-40f9-a1bd-b94098f068db.gif]<https://twitter.com/diamondgroupne>
[cid:Instagram_faebfdc1-366b-4672-831a-8bd47ed5c713.png]<https://www.instagram.com/diamonditne/>
[cid:LinkedIn_6dcebfaa-96d9-4e26-b317-abcd5f4d8982.png]<https://uk.linkedin.com/company/diamond-group-ltd><https://www.youtube.com/user/CodeTwoChannel#p/u>


[cid:DiamondLogoDivisionsBannerMarch2016PNG_99fc9e53-6303-455c-8c49-5253054c1237.png]<https://Diamond-group.net>

[cid:3CX_1d62d835-72f3-42c3-87c7-df2ef6d1e1c4.png]<https://www.diamond-group.net/about-us/accreditations/diamond-have-been-awarded-3cx-silver-partner-status/>


[cid:CySA+cecertifiedlogo_68111118-960a-4c9a-97da-2287951fa48c.png]<https://www.diamond-group.net/news/cyber-security-accreditation/>


[cid:GOLD-customer-service-logo_6318178a-ac18-4b27-8390-3fb9c44f9d9f.jpg]<https://www.diamond-group.net/news/diamond-awarded-gold/>


Diamond Group, Diamond House, Kingsway North, Team Valley, Gateshead, NE11 0JH

Diamond Group accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. If you are not the intended recipient, you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.


<https://www.diamond-group.net/news/diamond-awarded-gold/>
