### ISSUE TITLE
A 500 error page at apps/overview.py

### ISSUE THREAD

**Issue by zenny** [Aidaho12/haproxy-wi#116]
Hi,

The necessary stuffs got installed including db creation, however visiting the page at 8080 redirects the page to app/overview.py which gives 500 error, instead. 

Any clue?

A quick look at the error log shows:

```
[Thu Jun 20 14:30:12.828803 2019] [cgi:error] [pid 1077:tid 140361989080832] [client ::1:39132] End of script output before headers: overview.py, referer: https://haprox-wi.example.com:8080/
```

**Comment by Aidaho12** [comment]
Look errors in apache error log file

**Comment by Aidaho12** [comment]
Another pages come backs 500 error too?

**Comment by zenny** [comment]
all pages, cannot find anything in the apache's error.log. Reissued the self-signed certificates, too (https://raw.githubusercontent.com/fabianlee/blogcode/master/haproxy/selfsigned.sh) that matches the hostname of the computer and the domain inside the vhosts file. Yet no luck.

Thanks for taking time. Have a nice midsummer, @Aidaho12

**Comment by Aidaho12** [comment]
When you deleted "import html" maybe you added something wrong?

**Comment by zenny** [comment]
Nope nothing as such. Just added a hash (#) in the front to comment/disable that line. createdb.py went without segmentation fault and also verified whether the db was created in mysql manually (mysql -u root -p), fyi.

**Comment by Aidaho12** [comment]
Post overview.py here please

**Comment by zenny** [comment]
Please find attached overview.py:

```
# cat /var/www/haproxy-wi/app/overview.py 
#!/usr/bin/env python3
import funct, sql
import create_db
import os, http.cookies
from jinja2 import Environment, FileSystemLoader
env = Environment(loader=FileSystemLoader('templates/'))
template = env.get_template('ovw.html')
	
print('Content-type: text/html\n')
if create_db.check_db():
	if create_db.create_table():	
		create_db.update_all()
create_db.update_all_silent()
funct.check_login()

try:
	cookie = http.cookies.SimpleCookie(os.environ.get("HTTP_COOKIE"))
	user_id = cookie.get('uuid')
	user = sql.get_user_name_by_uuid(user_id.value)
	users = sql.select_users()
	groups = sql.select_groups()
	token = sql.get_token(user_id.value)
	cmd = "ps ax |grep checker_mas |grep -v grep |wc -l"
	checker_master, stderr = funct.subprocess_execute(cmd)
	cmd = "ps ax |grep checker_worker |grep -v grep |wc -l"
	checker_worker, stderr = funct.subprocess_execute(cmd)
	cmd = "ps ax |grep metrics_master |grep -v grep |wc -l"
	metrics_master, stderr = funct.subprocess_execute(cmd)
	cmd = "ps ax |grep -e 'metrics_worker\|metrics_waf_worker.py' |grep -v grep |wc -l"
	metrics_worker, stderr = funct.subprocess_execute(cmd)
except:
	pass

template = template.render(h2 = 1,
							autorefresh = 1,
							title = "Overview",
							role = sql.get_user_role_by_uuid(user_id.value),
							user = user,
							users = users,
							groups = groups,
							metrics_master = ''.join(metrics_master),
							metrics_worker = ''.join(metrics_worker),
							checker_master = ''.join(checker_master),
							checker_worker = ''.join(checker_worker),
							error = stderr,
							token = token)
print(template)						
```

Thanks for prompt response.

**Comment by Aidaho12** [comment]
comment it and try:
'''
if create_db.check_db():
	if create_db.create_table():	
		create_db.update_all()
create_db.update_all_silent()
'''

**Comment by zenny** [comment]
Commenting those four lines didn't make any difference, fyi.

Anyway thanks a gazillion for your efforts.
