### ISSUE TITLE
SSH Reverse Proxy

### ISSUE THREAD

**Issue by marrobHD** [Aidaho12/haproxy-wi#117]
How can I make it that who I ssh1.mydomain.tk calls are forwarded to a ssh server on the local network? 
Thanks :)

**Comment by Aidaho12** [comment]
Forward 22 port from your ext server to your local server
--
Отправлено из Mail.ru для Android пятница, 28 июня 2019г., 10:37 +03:00 от Marlon  notifications@github.com :

**Comment by marrobHD** [comment]
But I have to access more than one
SSH1 -> ssh1.mydomain.tk 
SSH2 -> ssh2.mydomain.tk
....
I only have one ip.
What do I have to change the web interface
