### ISSUE TITLE
Unsecure apache config

### ISSUE THREAD

**Issue by soulblader** [Aidaho12/haproxy-wi#119]
I've used ./install.sh script and started application with default settings.
It is possible to get private key without authentication:
`curl -k https://[HAPROXY-WI_ADDRESS]/keys/[KEY_NAME].pem`

Keys should be never saved to directory visible by web server!

UPD: This may be not so critical, but any file is available. For example, sqlite database file:
`curl -k https://[HAPROXY-WI_ADDRESS]/app/haproxy-wi.db`
It should be mentioned that passwords are stored in plaintext format in the database =/

And even Apache server private key file:
`curl -k https://[HAPROXY-WI_ADDRESS]/app/certs/haproxy-wi.key`

**Comment by Aidaho12** [comment]
Thank you!

I updated apache config, now all these folders and files are forbiddens
