### ISSUE TITLE
name 'conf' is not defined

### ISSUE THREAD

**Issue by Theoooooo** [Aidaho12/haproxy-wi#120]
Following of the issue : #116 
Exact same configuration as before.

After i configured a group, a server, SSH credentials for this specific server and apply specific right for the account i configure to allow this account to read the haproxy.conf file on a distant server, i got the following error when i try to show the config from HAPaoryx --> Config Menu : 

```
[Mon Jul 01 10:02:11.815221 2019] [cgi:error] [pid 102213:tid 140391256938240] [client 172.10.1.1:57313] AH01215: Traceback (most recent call last):: /var/www/haproxy-wi/app/options.py, referer: http://172.10.1.252:8081/app/config.py
[Mon Jul 01 10:02:11.815389 2019] [cgi:error] [pid 102213:tid 140391256938240] [client 172.10.1.1:57313] AH01215:   File "/var/www/haproxy-wi/app/options.py", line 339, in <module>: /var/www/haproxy-wi/app/options.py, referer: http://172.10.1.252:8081/app/config.py
[Mon Jul 01 10:02:11.815635 2019] [cgi:error] [pid 102213:tid 140391256938240] [client 172.10.1.1:57313] AH01215:     template = template.render(conf=conf, view=form.getvalue('view'), serv=serv, configver=form.getvalue('configver'), role=funct.is_admin(level=2))\t\t\t\t\t\t\t\t\t\t\t: /var/www/haproxy-wi/app/options.py, referer: http://172.10.1.252:8081/app/config.py
[Mon Jul 01 10:02:11.815703 2019] [cgi:error] [pid 102213:tid 140391256938240] [client 172.10.1.1:57313] AH01215: NameError: name 'conf' is not defined: /var/www/haproxy-wi/app/options.py, referer: http://172.10.1.252:8081/app/config.py

```
I also check the settings section to see if the haproxy.conf path is correct and the default one is correct

**Comment by Aidaho12** [comment]
User whom connect to remote server has root permissions?

**Comment by Theoooooo** [comment]
@Aidaho12 
Even if i'm trying with root user (for testing purpose only), i still got the error (i also allow root to connect though SSH).

**Comment by Aidaho12** [comment]
for some reason haproxy-wi can't download or save haproxy.conf from remote server.... Check if exists save configs at /var/www/haproxy-wi/configs
