### ISSUE TITLE
Can not connect to HAP server

### ISSUE THREAD

**Issue by p57p57** [Aidaho12/haproxy-wi#121]
Hi,
just installed all the stuff.
trying to add server through admin page.
First i created a group then a credential with ssh login and password. Added it to the server.
CLicked check connection and i got the error message: can not connect to server.

HAP-wi is installed on the same machine than the hap server. i gave the root credential.
I 've tried to sshconnect directly with terminal, it is working.

If i understand well, at this stage i do not need to modify hap conf ? i have to later when i 'll be able to successfully sshconnect ?

Regards

**Comment by Aidaho12** [comment]
Check apache error log, and yes, edit now haproxy config not need
--
Отправлено из Mail.ru для Android понедельник, 08 июля 2019г., 18:37 +03:00 от p57p57  notifications@github.com :
