### ISSUE TITLE
It does not detect haproxy servers

### ISSUE THREAD

**Issue by jcarlosg87** [Aidaho12/haproxy-wi#123]
Hello, I am delighted with this great software that you have developed, I would like to use it but I am having problems, I can not see any configuration of the haproxy within the platform and they also appear as down the servers that I load. thank you

**Comment by Aidaho12** [comment]
Hi, 
Your config in default place /etc/haproxy/haproxy.cfg?
--
Отправлено из Mail.ru для Android вторник, 16 июля 2019г., 00:42 +03:00 от jcarlosg87  notifications@github.com :

**Comment by jcarlosg87** [comment]
hello if my configuration is in /etc/haproxy/haproxy.cfg, as data the verification I have of is HA-Proxy version 1.6.3 2015/12/25
Copyright 2000-2015 Willy Tarreau <willy@haproxy.org>
thank you very much for your help

**Comment by Aidaho12** [comment]
Then maybe problem with permission
