### ISSUE TITLE
Issues with metrics worker not starting and metrics not being displayed

### ISSUE THREAD

**Issue by Kromatix87** [Aidaho12/haproxy-wi#124]
Hi, really happy to find this web interface for haproxy, great project and thanks for putting the time in to develop it!

I've been trying for a number of days to get this to work, and although most things are working the metrics are not.

I've read through the readme file, and have socat installed and the config file as suggested. I've also read the other issues posted about metrics, and tried systemctl start metrics_haproxy.service. Unfortunately the metrics page doesn't display information on my lb.

There are errors in the /var/www/haproxy-wi/log/metrics-error.log as follows:

Jul 16 03:10:55 LB1 metrics: Traceback (most recent call last):
Jul 16 03:10:55 LB1 metrics: File "tools/metrics_worker.py", line 62, in <module>
Jul 16 03:10:55 LB1 metrics: main(args.IP, args.port)
Jul 16 03:10:55 LB1 metrics: File "tools/metrics_worker.py", line 42, in main
Jul 16 03:10:55 LB1 metrics: sql.insert_mentrics(serv, metrics[0], metrics[1], metrics[2], metrics[3])
Jul 16 03:10:55 LB1 metrics: IndexError: list index out of range

This repeats every 30 seconds whilst the server is running.

On the overview page, the Metrics workers are shown as down, with 0 processes running. Although the Metrics master is up running 1 processes.

Interestingly, if I install haproxy using haproxy-wi, the metrics worker runs fine, but I need to use version >1.8 as opposed to the 1.5.18 version it installs by itself so need to do this manually. I have replicated the issue I'm seeing with a manual install of haproxy 1.5.19, 1.6.14, 1.7.11 and 1.8.20 though, so I'm pretty sure I have a configuration issue as opposed to a version issue.

Please can you help resolve the problem, or let me know what I need to change to get it working?

**Comment by Aidaho12** [comment]
Hi,
It is seems like haproxy sends not full static data, can you run command in metrics_worker.py manually and check it?
--
Отправлено из Mail.ru для Android вторник, 16 июля 2019г., 05:37 +03:00 от Kromatix87  notifications@github.com :

**Comment by Aidaho12** [comment]
I meen execute the command: 
```
echo show info | nc "+serv+" "+port+" |grep -e 'CurrConns\|CurrSslConns\|MaxSessRate:\|SessRate:'|awk '{print $2}'
```
Instead +serv+ and +port+ specify IP and port your haproxy server

**Comment by Kromatix87** [comment]
Thanks for responding! I've run the command suggested, and the output is as follows:

0
0
2

The statistic CurrSslConns doesn't exist, probably because I'm not using SSL yet. But the others come back ok. If I remove the awk command it shows:

CurrConns: 0
SessRate: 0
MaxSessRate: 2

Is this not as expected?

**Comment by Aidaho12** [comment]
Problem with count returned values... Program waits 4, but returned only 3

**Comment by Aidaho12** [comment]
You can edit app/tools/metric_worker.py, instead:
```
sql.insert_mentrics(serv, metrics[0], metrics[1], metrics[2], metrics[3])
```
must be:
```
sql.insert_mentrics(serv, metrics[0], 0, metrics[1], metrics[2])
```

But you will have to edit it each time, when you will be update

**Comment by Kromatix87** [comment]
Thanks for your response, much appreciated.

Do you know why this statistic isn't showing for me? It seems like the solution would be to fix the root cause - the missing statistic - as opposed to changing the code you've written.

Let me know what you think please.

**Comment by Aidaho12** [comment]
Maybe you installed haproxy without ssl support... Check it with command haproxy -vvv
--
Отправлено из Mail.ru для Android среда, 17 июля 2019г., 00:54 +03:00 от Kromatix87  notifications@github.com :

**Comment by Kromatix87** [comment]
When compiling the source for haproxy, I followed a guide that said to use the following:

make TARGET=linux2628

Looks like I should have used:

make TARGET=linux2628 USE_PCRE=1 USE_OPENSSL=1 USE_ZLIB=1 USE_CRYPT_H=1 USE_LIBCRYPT=1

I'll give that a try and feed back!

**Comment by Kromatix87** [comment]
Worked like a charm, metrics worker running with haproxy 1.9.8, no errors.

Thank you so much for your help!
