### ISSUE TITLE
SSL file upload failed

### ISSUE THREAD

**Issue by wangjunking** [Aidaho12/haproxy-wi#126]
SSL file upload prompt was successful, but there were no files on the corresponding server.

**Comment by Aidaho12** [comment]
Show me the apache error log, and check ssl path in settings

**Comment by Aidaho12** [comment]
Check permissions for user who connect to the server
--
Отправлено из Mail.ru для Android вторник, 16 июля 2019г., 12:16 +03:00 от wangjunking  notifications@github.com :

**Comment by wangjunking** [comment]
This problem has been resolved,thanks!
permission problem.
