### ISSUE TITLE
haproxy-wi support which haproxy version

### ISSUE THREAD

**Issue by wangjunking** [Aidaho12/haproxy-wi#127]
haproxy-wi support which haproxy versions?

**Comment by Aidaho12** [comment]
Basically any, but tested with 1.5-1.9. last one is better
--
Отправлено из Mail.ru для Android среда, 17 июля 2019г., 04:10 +03:00 от wangjunking  notifications@github.com :

**Comment by wangjunking** [comment]
now i manual installation 1.9.8,but can't edit haproxy.cfg.

error.log
Wed Jul 17 10:11:35.980317 2019] [cgi:error] [pid 35457] [client 10.171.23.14:57253] AH01215: raise value.with_traceback(tb), referer: http://10.222.11.56:8080/app/config.py
[Wed Jul 17 10:11:35.980373 2019] [cgi:error] [pid 35457] [client 10.171.23.14:57253] AH01215: File "templates/ajax/config_show.html", line 14, in top-level template code, referer: http://10.222.11.56:8080/app/config.py
[Wed Jul 17 10:11:35.980396 2019] [cgi:error] [pid 35457] [client 10.171.23.14:57253] AH01215: {% for line in conf %}, referer: http://10.222.11.56:8080/app/config.py
[Wed Jul 17 10:11:35.980448 2019] [cgi:error] [pid 35457] [client 10.171.23.14:57253] AH01215: File "/usr/lib/python3.5/site-packages/jinja2/runtime.py", line 435, in __init__, referer: http://10.222.11.56:8080/app/config.py
[Wed Jul 17 10:11:35.980471 2019] [cgi:error] [pid 35457] [client 10.171.23.14:57253] AH01215: self._after = self._safe_next(), referer: http://10.222.11.56:8080/app/config.py
[Wed Jul 17 10:11:35.980523 2019] [cgi:error] [pid 35457] [client 10.171.23.14:57253] AH01215: File "/usr/lib/python3.5/site-packages/jinja2/runtime.py", line 455, in _safe_next, referer: http://10.222.11.56:8080/app/config.py
[Wed Jul 17 10:11:35.980544 2019] [cgi:error] [pid 35457] [client 10.171.23.14:57253] AH01215: return next(self._iterator), referer: http://10.222.11.56:8080/app/config.py

**Comment by Aidaho12** [comment]
Show me haproxy config
--
Отправлено из Mail.ru для Android среда, 17 июля 2019г., 05:36 +03:00 от wangjunking  notifications@github.com :

**Comment by wangjunking** [comment]
global

    log         127.0.0.1 local2

    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon


    stats socket /var/lib/haproxy/stats
    stats socket *:1999 level admin
    stats socket /var/run/haproxy.sock mode 600 level admin
    server-state-file /etc/haproxy/haproxy.state

defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000
    load-server-state-from-file global

listen admin_stats
        stats   enable
        bind    *:8085
        mode    http
        #option  httplog 
        log     global
        maxconn 10
        stats   refresh 30s
        #http-request use-service prometheus-exporter if { path /metrics }
        stats   uri /stats
        stats   realm haproxy
        stats   hide-version
        stats   admin if TRUE

**Comment by Aidaho12** [comment]
You cannot edit or show config doesn't work?

**Comment by wangjunking** [comment]
yes

**Comment by Aidaho12** [comment]
Both?

**Comment by wangjunking** [comment]
both, now i copy the 1.8.20 haproxy config into the 1.9.8 haproxy,it's work.

**Comment by Aidaho12** [comment]
Show me please config from 1.8

**Comment by wangjunking** [comment]
haproxy 1.8.20 config

global
    log         127.0.0.1 local2
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon
    stats socket /var/lib/haproxy/stats
    stats socket *:1999 level admin
    stats socket /var/run/haproxy.sock mode 600 level admin
    server-state-file /etc/haproxy/haproxy.state 

defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

listen stats 
    bind *:8085 
    stats enable
    stats uri /stats
    stats realm HAProxy-04\ Statistics
    stats auth admin:password
    stats admin if TRUE

**Comment by Aidaho12** [comment]
I think problem in the line:
'''
#http-request use-service prometheus-exporter if { path /metrics }
'''

**Comment by wangjunking** [comment]
delete it ,working now,thanks!

other question,haproxy 1.9.8 services management is systemd?

**Comment by Aidaho12** [comment]
Yes
--
Отправлено из Mail.ru для Android среда, 17 июля 2019г., 10:13 +03:00 от wangjunking  notifications@github.com :

**Comment by wangjunking** [comment]
pls help analyze the haproxy.services config,always start failed.

[Unit]
Description=HAProxy Load Balancer
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=/usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid
ExecReload=/usr/sbin/haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -sf $(cat /var/run/haproxy.pid)
Type=notify

[Install]
WantedBy=multi-user.target

**Comment by Aidaho12** [comment]
I don't remember how it should be, use google

And update HAProxy-WI yesterday was update, that fix your problem

**Comment by wangjunking** [comment]
thanks!
