### ISSUE TITLE
Get haproxy-wi version number

### ISSUE THREAD

**Issue by lcami** [Aidaho12/haproxy-wi#128]
More of a how-to than an issue, but is there anyway to get the current version number of haproxy-wi?

**Comment by Aidaho12** [comment]
See files descriptions on "Code" page

**Comment by lcami** [comment]
I mean get the version number of haproxy-wi from within a centos 7 machine with haproxy-wi running....

**Comment by Aidaho12** [comment]
Left down corner?
--
Отправлено из Mail.ru для Android среда, 24 июля 2019г., 16:33 +03:00 от lcami  notifications@github.com :

**Comment by lcami** [comment]
I need to get it from a script to display it on a different dashboard with the version number of haproxy.

For haproxy I use haproxy –v and then store the output in a variable.

Anyway to get the version number for haproxy-wi?

**Comment by Aidaho12** [comment]
Aaa... You about this... No, you can't
--
Отправлено из Mail.ru для Android среда, 24 июля 2019г., 16:36 +03:00 от lcami  notifications@github.com :

**Comment by lcami** [comment]
Is there maybe a version number inside one of the files that I can grep?

Or is there the possibility to implement this small change?

**Comment by Aidaho12** [comment]
You may parse the file: app/templates/base.html, string:
```
					<a href="https://github.com/aidaho12/haproxy-wi/" title="Github repo" target="_blank" style="color: #fff">HAproxy-WI v3.4.4.5</a>
```

**Comment by lcami** [comment]
it might be cumbersome but this just works, thought of sharing it in case someone needs somethiung similar:

grep -i "https://github.com/aidaho12/haproxy-wi/" /var/www/haproxy-wi/app/templates/base.html | cut -d ">" -f 2 |cut -d "<" -f 1

HAproxy-WI v3.4.4.5

Thanks a lot for your help
