### ISSUE TITLE
Get "Authentication failed, please verify your credentials " during compare configs 

### ISSUE THREAD

**Issue by oy1978** [Aidaho12/haproxy-wi#13]
Hi ,
I get "Authentication failed, please verify your credentials" when run compare configs
I am use mysql to be DB , and have checked there have correct user information in there .
I can get device config by "Show config" , but can compare configs .

Thanks

**Comment by Aidaho12** [comment]
You added ssh creds?
--
Отправлено из Mail.Ru для Android среда, 23 мая 2018г., 07:21 +04:00 от oy1978  notifications@github.com :

**Comment by oy1978** [comment]
I have not creds , I just use password

**Comment by Aidaho12** [comment]
user have sudo without passwd?

**Comment by Aidaho12** [comment]
and where you get error? on compare or get config?

**Comment by oy1978** [comment]
on compare , get config is work , and i have  not set sudo without password

**Comment by Aidaho12** [comment]
it's root user? Show me error log, when compare

**Comment by oy1978** [comment]
The user is sudoer , for the error log is "haproxy-wi.error.log" ? if yes , I have observed the log in real time , there have error log when compare error  . 
There have a lot log about :
[Tue May 22 08:18:08.973537 2018] [cgi:error] [pid 25155] [client 172.18.255.65:65311] AH01215: dos2unix: converting file /var/www/haproxy-wi/configs/hap_config/172.31.248.129-2018-05-22.12:11:25.cfg to Unix format ..., referer: http://172.31.248.128:8080/app/configver.py?serv=172.31.248.129&open=open&configver=172.31.248.129-2018-05-22.12:11:25.cfg
but the log not happen during test compare config

**Comment by oy1978** [comment]
your mean is the user on my haproxy server also need exist on haproxy-wi ?

**Comment by Aidaho12** [comment]
yes. It will be necessary to rewrite, that it was not necessary to create the user locally

**Comment by oy1978** [comment]
I have create the same user on haproxy-wi , it is work now , thank you a lot , this UI is helpful for us , thank you again :)

**Comment by Aidaho12** [comment]
welcome ) put your favorite, subscribe to my channel and send donations)
