### ISSUE TITLE
[Errno 2] No such file or directory: '/var/www/haproxy-wi/keys/root.pem'

### ISSUE THREAD

**Issue by albevt** [Aidaho12/haproxy-wi#130]
Hi, after start haproxy-wi with docker, add localhost server but in overview hompage view this error
![Cattura](https://user-images.githubusercontent.com/53815085/62527073-c38e2f00-b83a-11e9-8846-7e82838f2ac0.PNG)
.

**Comment by Aidaho12** [comment]
it's seems like haproxy-wi can't save your pem file... try use password

**Comment by albevt** [comment]
Where use password ? I use root to connect haproxy-wi to local server (Centos 7)
![Cattura](https://user-images.githubusercontent.com/53815085/62532679-43b99200-b845-11e9-9bdd-97b260bbfbde.PNG)

**Comment by Aidaho12** [comment]
Hmmm... Show me error log 
--
Отправлено из Mail.ru для Android вторник, 06 августа 2019г., 13:25 +03:00 от albevt  notifications@github.com :

**Comment by albevt** [comment]
This is error.log file from haproxy-wi.
I have haproxy installed on my server with yum install haproxy.

[error.log](https://github.com/Aidaho12/haproxy-wi/files/3471694/error.log)

**Comment by Aidaho12** [comment]
In that log all right... You add your cert in credential tab?

**Comment by albevt** [comment]
you mean ssh cert? I have do not have any cert.

**Comment by Aidaho12** [comment]
Yes, ssh. You use auth by password?

**Comment by albevt** [comment]
> 
> 
> Yes, ssh. You use auth by password?

Yes i use root password no cert.

**Comment by Aidaho12** [comment]
Can you show me print screen from cred tab?

**Comment by albevt** [comment]
> 
> 
> Can you show me print screen from cred tab?

![Cattura](https://user-images.githubusercontent.com/53815085/62533870-01de1b00-b848-11e9-96de-7e3c22cecadb.PNG)

**Comment by Aidaho12** [comment]
And how you can use password if "ssh key" enabled?

**Comment by albevt** [comment]
> 
> 
> And how you can use password if "ssh key" enabled?

Thanks!!!!!!!!!!
