### ISSUE TITLE
all colums are collapsed

### ISSUE THREAD

**Issue by TheMrg** [Aidaho12/haproxy-wi#132]
nit real issue, but how can i not colaps all menu items. it is hard to navigate so. i like the menu unfolded.
Thanks. in screenshots all menu items are unfolded in left menu.
May there is a config value.

**Comment by Aidaho12** [comment]
now it's impossible, but maybe I will do it

**Comment by Aidaho12** [comment]
How about this menu https://demo.haproxy-wi.org ?
