### ISSUE TITLE
Install custom dir

### ISSUE THREAD

**Issue by terafirmanz** [Aidaho12/haproxy-wi#134]
When running the install script if you select a custom directory e.g. "myserver" the apache vhosts file is not updated for the certificate path it still references the /var/www/haproxy-wi/app/certs/ path not /var/www/myserver/app/certs/

**Comment by terafirmanz** [comment]
Also some of the directory switches for the deny access do not update the correct patch name still referencing /haproxy-wi/

**Comment by Aidaho12** [comment]
Thank you, problem with certs I have fixed. Tell me please exactly which directories switched for deny access?

**Comment by terafirmanz** [comment]
Hi, same file just referring to the directory sections lower down that control access to the directories.

The path does not update correctly on them. Also the key path referred to does not exist.

**Comment by Aidaho12** [comment]
Ok, with the new install script all will be ok, I think so)
--
Отправлено из Mail.ru для Android среда, 14 августа 2019г., 00:35 +03:00 от terafirmanz  notifications@github.com :
