### ISSUE TITLE
paypal donation doesn't work

### ISSUE THREAD

**Issue by scwall** [Aidaho12/haproxy-wi#135]
Hello, paypal doesn't work, when i tried to create a donation. Can you possibility to create a one shot donation in the patreon ?? Thank's

**Comment by Aidaho12** [comment]
Hello, I think there are only one way:

https://support.patreon.com/hc/en-us/articles/204606215-Can-I-make-a-one-time-payment-

:(

**Comment by Aidaho12** [comment]
And about paypal... there were some problems, but people somehow sent donations

**Comment by Aidaho12** [comment]
You can donation by email: buffoon2001@gmail.com
