### ISSUE TITLE
Possible plugin option - Cockpit

### ISSUE THREAD

**Issue by terafirmanz** [Aidaho12/haproxy-wi#136]
Hi, wanted to ask this no idea on possibility or effort required.

Would it at all be possible to have this as a Cockpit plugin? We are keen to shift a lot of management towards Cockpit and based on the pace of dev it looks like many others are.

Would be willing to sponsor the effort if possible.

If not then at least a package from repo would be nice for simple install when not using a container.

**Comment by Aidaho12** [comment]
Hi, yes, I think it's possible.
How many you want sponsored?
--
Отправлено из Mail.ru для Android среда, 14 августа 2019г., 00:40 +03:00 от terafirmanz  notifications@github.com :

**Comment by terafirmanz** [comment]
what would the effort be? would a cockpit plugin be something supported or would it become a custom fork?

I was happy to sponsor the UI designer you mention on your Patron page plus the cost of the conversion to a cockpit plugin. If the effort is reasonable let me know what you think it would take and I will see if I can make the donation for both.

**Comment by Aidaho12** [comment]
I am going to read about cockpit and how integration works. I think do fork it's not good idea, because you can't update in the future

> I was happy to sponsor the UI designer you mention on your Patron page
You have already supported the project on the Patreon?

**Comment by terafirmanz** [comment]
thanks, not yet sponsored the UI project but will look into it. Can I do via 1 off payment in PayPal for full amount?

**Comment by Aidaho12** [comment]
Of course, only your wish
--
Отправлено из Mail.ru для Android среда, 14 августа 2019г., 02:59 +03:00 от terafirmanz  notifications@github.com :

**Comment by Aidaho12** [comment]
>Would it at all be possible to have this as a Cockpit plugin? 

I have read about cockpit, unfortunately they accept only C language :(
What about rpm?

**Comment by terafirmanz** [comment]
yes an RPM would be enough as it would take care of dependencies and basic setup.

**Comment by Aidaho12** [comment]
Ok, which OS you use?
--
Отправлено из Mail.ru для Android среда, 14 августа 2019г., 12:35 +03:00 от terafirmanz  notifications@github.com :

**Comment by terafirmanz** [comment]
Hi,

Fedora/Centos

Also I had a look at Cockpit dev and unless I read wrong from what I can see you just deploy HTML/CSS/JSS files to the plugin directory that creates the web interface that can then call any API. Take it this would be a re-write of this as you use a webserver and serve dynamic content.

**Comment by Aidaho12** [comment]
In that way you need install backend and this is not automatic
>Centos
Ok, when you sponsored me, then I will start to do RPM
--
Отправлено из Mail.ru для Android четверг, 15 августа 2019г., 05:54 +03:00 от terafirmanz  notifications@github.com :

**Comment by terafirmanz** [comment]
ok let me know what you think cost would be for RPM and for the graphic/web design and I'll put that through paypal.

**Comment by Aidaho12** [comment]
I even don't know.... Maybe 100$?
--
Отправлено из Mail.ru для Android четверг, 15 августа 2019г., 08:32 +03:00 от terafirmanz  notifications@github.com :
