### ISSUE TITLE
Mounting /var/www/haproxy-wi/app to a host directory fails

### ISSUE THREAD

**Issue by ducttapecoder-vt** [Aidaho12/haproxy-wi#137]
Hello,

I would like to mount the /var/www/haproxy-wi/app location to a system location, e.g. /data/haproxy-wi instead of a docker volume "haproxy-wi". I get the "Forbidden: You don't have permission to access /app/overview.py on this server" error when accessing the page. I tried `chown -R apache:apache /data/haproxy-wi` but it errors with "invalid user: 'apache:apache'" since I don't have that user on my host system.

I tried `docker exec haproxy-wi cat /etc/passwd` and saw apache is 48:48 so I tried `chown -R 48:48 /data/haproxy-wi` but now the message is "Not Found: the request URL /users.py was not found on this server" and the directory is still empty.

Is it possible to switch the docker container to use user ID instead of named user? Artifactory Nginx example uses 104:107 for example. Or maybe there is some other easy answer?

**Comment by Aidaho12** [comment]
>Or maybe there is some other easy answer?

Yes, you can add apache user to your host system

>Is it possible to switch the docker container to use user ID instead of named user? 

I think it's possible. You can fork docker repo, and change docker file to use ID
