### ISSUE TITLE
Stats summary and privilege escalation

### ISSUE THREAD

**Issue by brunolima1989** [Aidaho12/haproxy-wi#138]
Hi! @Aidaho12 

I've been testing haproxy-wi on my personal environment and all my needs have been met, but on my corporative environment I have some security policies that I need to respect.
For example, I cannot use the user "root" for ssh credentials on haproxy-wi. I have to use another user with privilege escalation with sudo or dzdo command. 'Cause this, my tests on corporative environment doesn't works very well.

The option like a "privilege escalation / become method" on settings was attempt this needs. Maybe this option can be included when we include a new server or edit another server that was be included. (like a become method on ansible https://docs.ansible.com/ansible/2.3/become.html).

Another issue is a summarry for the stats. I have too many processes on the same server and stats page show only stats of one process for every refresh.

This is my needs, but another people can have the same needs.

Congratulations for this beautiful project and Sorry for my bad english.

**Comment by Aidaho12** [comment]
> I cannot use the user "root" for ssh credentials on haproxy-wi

You can use sudo user, just use "nopassword" option for sudo

>Another issue is a summarry for the stats. I have too many processes on the same server and stats page show only stats of one process for every refresh.

Maybe have some special settings for stats page. I don't know, read the manual
