### ISSUE TITLE
waf.sh - v3.4.4.5 - compile fails on Centos

### ISSUE THREAD

**Issue by SysadminEU1** [Aidaho12/haproxy-wi#139]
It needs 
sudo yum install pcre-devel

When it tries to compile on line 52,53,54,55

Even when it pcre-devel is installed - it still 

```
`> sudo make -C standalone install >> /dev/null'

config.c: In function ‘process_command_config’:
config.c:1107:5: warning: passing argument 1 of ‘apr_filepath_root’ from incompatible pointer type [enabled by default]
     status = apr_filepath_root(&rootpath, &incpath, APR_FILEPATH_TRUENAME | APR_FILEPATH_NATIVE, ptemp);
     ^
In file included from /usr/include/apr-1/apr_file_io.h:29:0,
                 from /usr/include/apr-1/apr_network_io.h:26,
                 from /usr/include/apr-1/apr_buckets.h:29,
                 from /usr/include/httpd/util_filter.h:26,
                 from /usr/include/httpd/http_core.h:32,
                 from config.c:18:
/usr/include/apr-1/apr_file_info.h:336:27: note: expected ‘const char **’ but argument is of type ‘char **’
 APR_DECLARE(apr_status_t) apr_filepath_root(const char **rootpath,
                           ^
config.c:1107:5: warning: passing argument 2 of ‘apr_filepath_root’ from incompatible pointer type [enabled by default]
     status = apr_filepath_root(&rootpath, &incpath, APR_FILEPATH_TRUENAME | APR_FILEPATH_NATIVE, ptemp);
     ^
In file included from /usr/include/apr-1/apr_file_io.h:29:0,
                 from /usr/include/apr-1/apr_network_io.h:26,
                 from /usr/include/apr-1/apr_buckets.h:29,
                 from /usr/include/httpd/util_filter.h:26,
                 from /usr/include/httpd/http_core.h:32,
                 from config.c:18:
/usr/include/apr-1/apr_file_info.h:336:27: note: expected ‘const char **’ but argument is of type ‘char **’
 APR_DECLARE(apr_status_t) apr_filepath_root(const char **rootpath,
                           ^
[root@localhost modsecurity]#
`
```

Is this for Ubuntu or Centos.

The problem begins at the start when you do not want to post the result of what it finds.

```
`#!/bin/bash

for ARGUMENT in "$@"
do

    KEY=$(echo $ARGUMENT | cut -f1 -d=)
    VALUE=$(echo $ARGUMENT | cut -f2 -d=)

    case "$KEY" in
            PROXY)              PROXY=${VALUE} ;;
            VERSION)            VERSION=${VALUE} ;;
            HAPROXY_PATH)       HAPROXY_PATH=${VALUE} ;;
            *)
    esac


done
VERSION=$(echo $VERSION | awk -F"-" '{print $1}')
VERSION_MAJ=$(echo $VERSION | awk -F"." '{print $1"."$2}')

if (( $(awk 'BEGIN {print ("'$VERSION'" < "'1.8'")}') )); then
	echo 'error: Need HAProxy version 1.8 or later <a title="Close" id="errorMess"><b>X</b></a>'
	exit 1
`
```

The system is running 
[root@localhost modsecurity]# haproxy -v
HA-Proxy version 1.8.17 2019/01/08
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

**Comment by SysadminEU1** [comment]
So according to your text, it should work, but it does not.

This error breaks the system, and I have to go back to an older version, where I fixed some of these errors.

The application design flaw and added complexity comes when you add Centos and Ubuntu in the same code.
Actually your code design requires that Centos fails on apt-get, but they are similar on Bash commands which leads to this problem.

You have to maintain control and have Ubuntu for Ubuntu and Centos for Epel/Redhat.

**Comment by Aidaho12** [comment]
How says in Readme with Ubuntu maybe problem.... And will be better if you do fork and pull request with your changes instead of write here large, angry posts

**Comment by SysadminEU1** [comment]
I am not angry, only frustrated.

**Comment by Aidaho12** [comment]
Ok, instead of write here frustrated posts

**Comment by SysadminEU1** [comment]
How can I write to you without beeing angry/frustrated, can I beta test your application development, I have a real production enviroment to do it in.

So what do you need from me?

**Comment by Aidaho12** [comment]
There is simple guide how create polite issues:
```
Hi, your project is [cool,good, awesome,normal] but I have some problem. Can you help to solve me?
```
or
```
I have some problem there are solution how to solve them. Check out please
```

This is free project and no one sponsor it. And I don't want to read angry/frustrated posts. With that kind of posts I will do nothing to solve your problems. Or if you want to write angry/frustrated posts pay me and I will solve your problems with patience and smile

**Comment by SysadminEU1** [comment]
I cannot pay you, but you are not reading it correctly as I newer intended to be angry.

Frustrated yes, as I believed that your development was all about fixing issues.

**Comment by Aidaho12** [comment]
Yes, to all about fixing my issues. If it will fix your problems I will be happy, if not, than ok

**Comment by SysadminEU1** [comment]
Many many thanks for the updates :-) :-)
You are the best
I will try them out.

**Comment by Aidaho12** [comment]
Sarcasm I don't like too )
