### ISSUE TITLE
Rest api support ?

### ISSUE THREAD

**Issue by icassano** [Aidaho12/haproxy-wi#14]
Hello, does it support configuration using rest api ?
If yes .....any example ?
Thanks
Ignazio

**Comment by Aidaho12** [comment]
No support, think you should do it
--
Отправлено из Mail.Ru для Android

**Comment by gianfebrian** [comment]
+1 It would be nice

**Comment by Aidaho12** [comment]
is there an example for what and how can this be used?
--
Отправлено из Mail.Ru для Android пятница, 25 мая 2018г., 13:15 +04:00 от Gian Febrian  notifications@github.com :

**Comment by Aidaho12** [comment]
After 1.5 year it is happened! Next release will be with REST API

And my previous question still make sense... Can you give me any cases what REST API has to have?
