### ISSUE TITLE
v3.4.4.5 - keepalive fails

### ISSUE THREAD

**Issue by SysadminEU1** [Aidaho12/haproxy-wi#140]
from the Centos where haproxy-wi is installed 
from /var/log/messages.

it keeps repeating
Aug 27 13:35:19 localhost systemd: Stopped Keep Alive Haproxy.
Aug 27 13:35:19 localhost systemd: Started Keep Alive Haproxy.
Aug 27 13:35:19 localhost systemd: Failed at step CHDIR spawning /var/www/app/tools/keep_alive.py: No such file or directory
Aug 27 13:35:19 localhost systemd: keep_alive.service: main process exited, code=exited, status=200/CHDIR
Aug 27 13:35:19 localhost systemd: Unit keep_alive.service entered failed state.
Aug 27 13:35:19 localhost systemd: keep_alive.service failed.
Aug 27 13:35:21 localhost systemd: keep_alive.service holdoff time over, scheduling restart.
Aug 27 13:35:21 localhost systemd: Stopped Keep Alive Haproxy.
Aug 27 13:35:21 localhost systemd: Started Keep Alive Haproxy.
Aug 27 13:35:21 localhost systemd: Failed at step CHDIR spawning /var/www/app/tools/keep_alive.py: No such file or directory
Aug 27 13:35:21 localhost systemd: keep_alive.service: main process exited, code=exited, status=200/CHDIR
Aug 27 13:35:21 localhost systemd: Unit keep_alive.service entered failed state.
Aug 27 13:35:21 localhost systemd: keep_alive.service failed.
Aug 27 13:35:24 localhost systemd: keep_alive.service holdoff time over, scheduling restart.
Aug 27 13:35:24 localhost systemd: Stopped Keep Alive Haproxy.
Aug 27 13:35:24 localhost systemd: Started Keep Alive Haproxy.
Aug 27 13:35:24 localhost systemd: Failed at step CHDIR spawning /var/www/app/tools/keep_alive.py: No such file or directory
Aug 27 13:35:24 localhost systemd: keep_alive.service: main process exited, code=exited, status=200/CHDIR
Aug 27 13:35:24 localhost systemd: Unit keep_alive.service entered failed state.
Aug 27 13:35:24 localhost systemd: keep_alive.service failed.
Aug 27 13:35:26 localhost systemd: keep_alive.service holdoff time over, scheduling restart.
Aug 27 13:35:26 localhost systemd: Stopped Keep Alive Haproxy.
Aug 27 13:35:26 localhost systemd: Started Keep Alive Haproxy.
Aug 27 13:35:26 localhost systemd: Failed at step CHDIR spawning /var/www/app/tools/keep_alive.py: No such file or directory
Aug 27 13:35:26 localhost systemd: keep_alive.service: main process exited, code=exited, status=200/CHDIR
Aug 27 13:35:26 localhost systemd: Unit keep_alive.service entered failed state.
Aug 27 13:35:26 localhost systemd: keep_alive.service failed.
Aug 27 13:35:28 localhost systemd: keep_alive.service holdoff time over, scheduling restart.
Aug 27 13:35:28 localhost systemd: Stopped Keep Alive Haproxy.
Aug 27 13:35:28 localhost systemd: Started Keep Alive Haproxy.

**Comment by Aidaho12** [comment]
Thanks. I have seen this problem, but can't reproduce, because install script work fine

**Comment by Aidaho12** [comment]
I have found out this bug, and fix it
