### ISSUE TITLE
Metrics workers doesn't enable

### ISSUE THREAD

**Issue by albevt** [Aidaho12/haproxy-wi#142]
Hi,
i add a server in haproxy-wi and enable the metrics on this server but in dashboard metrics are down.
where am I wrong?
I have docker installation.
Thanks for support.
![1](https://user-images.githubusercontent.com/53815085/64532416-ba005700-d311-11e9-9db6-e0bc73fb8e25.PNG)
![2](https://user-images.githubusercontent.com/53815085/64532417-ba98ed80-d311-11e9-9a84-420b3fbaaf5c.PNG)

**Comment by Aidaho12** [comment]
Hi,
You didn't run metric master
--
Отправлено из Mail.ru для Android понедельник, 09 сентября 2019г., 15:54 +03:00 от albevt  notifications@github.com :

**Comment by albevt** [comment]
Hi, 
how install and start metrics?
Thanks for support.

**Comment by Aidaho12** [comment]
At first check metric's error log. If there isn't errors try run:
```
systemctl restart metrics_haproxy.service
```

**Comment by albevt** [comment]
When run command the os return:
[root@ha-proxy ~]# systemctl restart metrics_haproxy.service
Failed to restart metrics_haproxy.service: Unit not found.

**Comment by Aidaho12** [comment]
Run next commands and try again:
```
export HOME_HAPROXY_WI=haproxy-wi
cat << EOF > /etc/systemd/system/multi-user.target.wants/metrics_haproxy.service
[Unit]
Description=Haproxy metrics
After=syslog.target network.target
[Service]
Type=simple
WorkingDirectory=/var/www/$HOME_HAPROXY_WI/app/
ExecStart=/var/www/$HOME_HAPROXY_WI/app/tools/metrics_master.py
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=metrics
RestartSec=2s
Restart=on-failure
TimeoutStopSec=1s
[Install]
WantedBy=multi-user.target
EOF

cat << 'EOF' > /etc/rsyslog.d/metrics.conf 
if $programname startswith 'metrics' then /var/www/__HOME_HAPROXY_WI__/log/metrics-error.log
& stop
EOF
sed -i -e "s/__HOME_HAPROXY_WI__/$HOME_HAPROXY_WI/g" /etc/rsyslog.d/metrics.conf

cat << EOF > /etc/logrotate.d/metrics
/var/www/$HOME_HAPROXY_WI/log/metrics-error.log {
    daily
    rotate 10
    missingok
    notifempty
	create 0644 apache apache
	dateext
    sharedscripts
}
EOF
```

or use rpm

**Comment by albevt** [comment]
After this command the result not changed.....

[root@ha-proxy ~]# systemctl restart metrics_haproxy.service
Failed to restart metrics_haproxy.service: Unit not found.
[root@ha-proxy ~]#

**Comment by Aidaho12** [comment]
Do please:
```
systemctl daemon-reload
```

**Comment by albevt** [comment]
Ok! I forgot this step!!

**Comment by Aidaho12** [comment]
Now check errors log

**Comment by Aidaho12** [comment]
> Its possible the reason is i have a docker installation.

Yes, it can be... I haven't test these servers on docker, and I actually don't know works it or not....

**Comment by albevt** [comment]
Ok! Thanks for your support!
