### ISSUE TITLE
Problem with users and servers page in Admin Area

### ISSUE THREAD

**Issue by szupanic** [Aidaho12/haproxy-wi#143]
Hi
I started haproxy-wi with a docker. I opened the homepage without any problems and all the tabs in the application work except users and servers. I have a blank screen. Can he help me?

**Comment by Aidaho12** [comment]
Hi

Show me logs, please

**Comment by szupanic** [comment]
[logs.txt](https://github.com/Aidaho12/haproxy-wi/files/3634752/logs.txt)

**Comment by Aidaho12** [comment]
Try open users.py and add next:
ldap_enable = ""
In the begin of file, where all vars defined
--
Отправлено из Mail.ru для Android пятница, 20 сентября 2019г., 10:48 +03:00 от szupanic  notifications@github.com :

**Comment by szupanic** [comment]
Thanks a lot, it works now. :)

**Comment by Aidaho12** [comment]
I fixed this bug and in the futures releases would be ok
