### ISSUE TITLE
Can not connect to server via SSH using key or password

### ISSUE THREAD

**Issue by jdquad** [Aidaho12/haproxy-wi#146]
Hello, I cannot connect via ssh to my servers by using sshkeys or password for the server.  I am using the haproxy user, i have also tried the root user, and still no connections.  

I am using verison 3.4.89.1 on CentOS 7.7.1908

Any ideas please?

Thanks

**Comment by Aidaho12** [comment]
Hi,

show me please apache error log, and sshd log

**Comment by jdquad** [comment]
all fixed now, for future reference this was the issue:

we installed the RPM onto the latest version 3.4.9.1 but that didnt pull in any requirements from requirements.txt.  As SSH is handed off and used via a python module and as that wasn't installed it caused failures.  By manually installing the packages via pip3 in requirements.txt and restart httpd the issue went away.

Sorry to bother you and thanks for replying :-)

**Comment by Aidaho12** [comment]
I think problem was because of rpm uses pip3.5 and you use pip3. I will add both options in the rpm...
No problems, feel free writing me, and leave your feedbacks ;)
--
Отправлено из Mail.ru для Android пятница, 27 сентября 2019г., 10:49 +03:00 от jdquad  notifications@github.com :
