### ISSUE TITLE
Unknown keyword 'server-state-file' in 'global' section

### ISSUE THREAD

**Issue by yusufsetyaa** [Aidaho12/haproxy-wi#148]
Good morning,

I was installed Haproxy-wi, and your project very cool. But I find some issues, there are :
1. We installed Haproxy from Haproxy-Wi Management to Server, and the server gets Haproxy version 1.5, can we change version Haproxy on Server?
2. After we installed Haproxy on Server via Haproxy-Wi Management, on Server get issues like this : 
 parsing [/etc/haproxy/haproxy.cfg:4] : unknown keyword 'server-state-file' in the 'global' section
Sep 30 00:25:03 host-116-254-101-22.mybati.co.id haproxy-systemd-wrapper[12029]: [ALERT] 272/002503 (12030) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg

We check it and found. This issue effect because of file haproxy.state missing on directory /etc/haproxy/. If we close script about Server State File in the global. Service haproxy on the server can run. Please help this issues.

**Comment by Aidaho12** [comment]
Hi,

>can we change version Haproxy on Server?

Yes, you can, and after you update haproxy second issue will gone or you can comment in this line

**Comment by yusufsetyaa** [comment]
Hi Aidaho12,

We have installed an HAProxy manual with version 2.0.6. But on Server Master, Haproxy didn't start, this example status Haproxy 2.0.6 :

Redirecting to /bin/systemctl status haproxy.service
● haproxy.service - HAProxy Load Balancer
   Loaded: loaded (/usr/lib/systemd/system/haproxy.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Wed 2019-10-02 10:59:58 EDT; 430ms ago
  Process: 39473 ExecStartPre=/usr/local/sbin/haproxy -f $CONFIG -c -q $EXTRAOPTS (code=exited, status=203/EXEC)

[root@~]#.: haproxy.service: control process exited, code=exited status=203
[root@~]#.: Failed to start HAProxy Load Balancer.
[root@~]#.: Unit haproxy.service entered failed state.
[root@~]#.: haproxy.service failed.
[root@~]#.: haproxy.service holdoff time over, scheduling restart.
[root@~]#.: Stopped HAProxy Load Balancer.
[root@~]#.: start request repeated too quickly for haproxy.service
[root@~]#.: Failed to start HAProxy Load Balancer.
[root@~]#.: Unit haproxy.service entered failed state.
[root@~]#.haproxy.service failed.

We confuse why Haproxy cant running if we install manually on Master Server. Any update on this?
Thank you

**Comment by Aidaho12** [comment]
Hi,
Show me messages log, or where haproxy is puts his logs. I need errors, or you can run haproxy -t -c -f /config/file
--
Отправлено из Mail.ru для Android среда, 02 октября 2019г., 18:04 +03:00 от yusufsetyaa  notifications@github.com :

**Comment by Aidaho12** [comment]
I think I know problem, edit service script and delete "local" from paths

**Comment by yusufsetyaa** [comment]
Hi,

This message log while cant start HAProxy manual on Master server : 

[root@]#.: Starting HAProxy Load Balancer...
[root@]#.: Failed at step EXEC spawning /usr/local/sbin/haproxy: No such file or directory
[root@]#.: haproxy.service: control process exited, code=exited status=203
[root@]#.: Failed to start HAProxy Load Balancer.
[root@]#.: Unit haproxy.service entered failed state.
[root@]#.: haproxy.service failed.
[root@]#.: haproxy.service holdoff time over, scheduling restart.
[root@]#.: Stopped HAProxy Load Balancer.
[root@]#.: start request repeated too quickly for haproxy.service
[root@]#.: Failed to start HAProxy Load Balancer.
[root@]#.: Unit haproxy.service entered failed state.
[root@]#.: haproxy.service failed.

And, where we should edit service script and delete local? on cfg haproxy Master? or on Script install remote on Haproxy-wi?

**Comment by Aidaho12** [comment]
Systemd script
--
Отправлено из Mail.ru для Android среда, 02 октября 2019г., 19:16 +03:00 от yusufsetyaa  notifications@github.com :

**Comment by yusufsetyaa** [comment]
Hi,

Edit systemd/script/haproxy.service? like this?

Screenshot : https://ibb.co/5hDWbFf

And what we should do?

**Comment by Aidaho12** [comment]
Yes, delete each local do systemctl daemon-reload and start service
--
Отправлено из Mail.ru для Android среда, 02 октября 2019г., 19:22 +03:00 от yusufsetyaa  notifications@github.com :

**Comment by Aidaho12** [comment]
You are welcome :)

**Comment by yusufsetyaa** [comment]
Hi,

we have to delete each local on systemd/haproxy.services, but still cant, this message log : 

[root@]#.systemd: start request repeated too quickly for haproxy.service
[root@]#.: Failed to start HAProxy Load Balancer.
[root@]#.: Unit haproxy.service entered failed state.
[root@]#.: haproxy.service failed.
[root@]#.: Reloading.
[root@]#.: haproxy.service lacks both ExecStart= and ExecStop= setting. Refusing.

**Comment by Aidaho12** [comment]
Google please or donate to project and I will configure for you your systems :)
--
Отправлено из Mail.ru для Android среда, 02 октября 2019г., 21:02 +03:00 от yusufsetyaa  notifications@github.com :

**Comment by yusufsetyaa** [comment]
Hi Aidaho12,

Well done, thanks for your insight. Now HAProxy Version 2.0.6 has run on Master Server. But on HAProxy-WI still down? and cant see config Master Server from HAProxy-WI?

**Comment by Aidaho12** [comment]
my conditions are still as they were
--
Отправлено из Mail.ru для Android среда, 02 октября 2019г., 22:06 +03:00 от yusufsetyaa  notifications@github.com :

**Comment by yusufsetyaa** [comment]
I see, thanks Aidaho12 for your help.

**Comment by Aidaho12** [comment]
You are welcome :)

**Comment by Aidaho12** [comment]
I have fixed your problem with config
