### ISSUE TITLE
Add ability to reload instead of restart

### ISSUE THREAD

**Issue by rabievdm** [Aidaho12/haproxy-wi#149]
Is there any reason why when editing configs that we do a full restart of the process instead of a reload?
eg 'systemctl reload haproxy' vs 'systemctl restart haproxy' ?

Would be nice to have both options.

**Comment by Aidaho12** [comment]
No any reason why uses restart, it's just my habit, but you can change restart command in the settings page, and use reload instead restart. Or you want both at the same time?

The need parameter of setting: https://demo.haproxy-wi.org/app/settings.py#restart_command

**Comment by rabievdm** [comment]
I did consider changing the command in the settings, but both would be nice.

A reload is much less 'destructive' as oppose to a full restart.

I have seen situations where doing a restart on the primary node causes keepalived to failover to the second node only to fail back again.

But also having the ability to restart is nice if you have a need to force the process to quit and restart.

**Comment by Aidaho12** [comment]
Ok, I will add it one day

**Comment by rabievdm** [comment]
Thanks!

One more reason to consider reload as opposed to a full restart is:
https://www.haproxy.com/blog/truly-seamless-reloads-with-haproxy-no-more-hacks/
See towards the end where they talk about v1.8

For now I'll change the restart to reload in the haproxy-wi config :)

**Comment by Aidaho12** [comment]
I have already read the article )

And i added ablity to reload, you may update and try. And don't forget change back restart command )

**Comment by rabievdm** [comment]
Awesome, thanks!
I'll check it out when you push the next rpm release.

**Comment by Aidaho12** [comment]
It's already happened :)
--
Отправлено из Mail.ru для Android вторник, 01 октября 2019г., 10:05 +03:00 от rabievdm  notifications@github.com :
