### ISSUE TITLE
Installation problem on Ubuntu 16.04

### ISSUE THREAD

**Issue by lgoehrs** [Aidaho12/haproxy-wi#15]
I am having issues on Ubuntu 16.04
There were a few missing modules, an when trying to run it, with the python debugger, I had:

python -m pdb login.py

```
root@par01-man01:/var/www/haproxy/app# python -m pdb login.py
> /var/www/haproxy/app/login.py(2)<module>()
-> import cgi
(Pdb) cont
Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "login.py", line 2, in <module>
    import cgi
  File "funct.py", line 5, in <module>
    import http.cookies
ImportError: No module named cookies
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /var/www/haproxy/app/funct.py(5)<module>()
-> import http.cookies
(Pdb) 
```

root@par01-man01:/var/www/haproxy/app# python --version
Python 2.7.12
root@par01-man01:/var/www/haproxy/app#

Can you help ?

**Comment by Aidaho12** [comment]
Need python 3

**Comment by lgoehrs** [comment]
my bad, it is running python 3

root@par01-man01:/var/www/haproxy/app# /usr/bin/env python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by Aidaho12** [comment]
Ok, try 
```
pip3 install http
```
May be it's not standart python ubuntu module

**Comment by lgoehrs** [comment]
Well, still no luck, I have a 500 error

Tried to launch, as per the documentation the update.py

root@par01-man01:/var/www/haproxy/app# python3 -m pdb update_db.py
> /var/www/haproxy/app/update_db.py(3)<module>()
-> import create_db
(Pdb) cont
Segmentation fault (core dumped)
root@par01-man01:/var/www/haproxy/app#

any idea ?
