### ISSUE TITLE
Yum haproxy-wi-release-7-1-0.noarch.rpm contains incorrect path

### ISSUE THREAD

**Issue by rabievdm** [Aidaho12/haproxy-wi#150]
Hi,

The haproxy-wi-release-7-1-0 rpm contains an incorrect repo path.
The file has /etc/yum.repo.d/ as the location for the repo definition whilst /etc/yum.repos.d/ is the correct location on EL7. (note the missing "s" in repos)

If I 'mv /etc/yum.repo.d/haproxy-wi.repo /etc/yum.repos.d/' and then do a yum update I now get haproxy-wi updates :)

Please update the RPM and the install instructions on the main page.

**Comment by Aidaho12** [comment]
Oh... I'm fixed it. Thank you
