### ISSUE TITLE
metrics page timing out

### ISSUE THREAD

**Issue by dniasoff** [Aidaho12/haproxy-wi#151]
Hi,

Thanks for an absolutely amazing product!

Got all working. Using haproxy version 2.0.7 and latest haproxy-wi from git.

All services running ok including metrics_haproxy service.

But when I try to show metrics it just times out.

Using latest Centos 7.

Any ideas?

Thanks

Daniel

**Comment by dniasoff** [comment]
And WAF page as well. WAF is installed and running.

**Comment by Aidaho12** [comment]
Hi, thanks)
Thw whole pages are timeout or only that part where metrics? And show me Apache error log
--
Отправлено из Mail.ru для Android пятница, 04 октября 2019г., 04:12 +03:00 от Daniel Niasoff  notifications@github.com :

**Comment by dniasoff** [comment]
It seems it's only occuring when I use mysql not sqlite. Using AWS aurora and the mysql threads are hanging.

There is a couple of bugs with WAF though

line 788 in sql.py has an extraneous %s which is breaking the query and I had to manually create the entries in the waf table

**Comment by Aidaho12** [comment]
Thank you, I will delete it
--
Отправлено из Mail.ru для Android пятница, 04 октября 2019г., 19:12 +03:00 от Daniel Niasoff  notifications@github.com :
