### ISSUE TITLE
HA>Edit Config missing edit button

### ISSUE THREAD

**Issue by rabievdm** [Aidaho12/haproxy-wi#152]
Hi,

First off love the changes to the interface, looks awesome.

It looks like the edit button is missing on the HA > Edit Config page.
The servers are listed and available from the drop down, but you cant edit.
That's on v3.5.1

R

**Comment by Aidaho12** [comment]
Thank you)
I will check it and fix
--
Отправлено из Mail.ru для Android понедельник, 07 октября 2019г., 10:01 +03:00 от rabievdm  notifications@github.com :

**Comment by Aidaho12** [comment]
I fixed it, please update and try

**Comment by rabievdm** [comment]
Working
