### ISSUE TITLE
Peers not recognized as a section

### ISSUE THREAD

**Issue by rabievdm** [Aidaho12/haproxy-wi#153]
v3.5.1
In the config you can define named peers and then have stick tables use the peers list.
If you edit the config then it will add the 'peers' into the previous section as oppose to having it has a separate expandable section:

Peers details:
https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#3.5

**Comment by Aidaho12** [comment]
Thank you, I will fix it too
--
Отправлено из Mail.ru для Android понедельник, 07 октября 2019г., 11:37 +03:00 от rabievdm  notifications@github.com :

**Comment by Aidaho12** [comment]
I fixed it, please update and try

**Comment by rabievdm** [comment]
Working
