### ISSUE TITLE
Config files save gets wrong timestamp

### ISSUE THREAD

**Issue by rabievdm** [Aidaho12/haproxy-wi#154]
Current local time (GMT+2) 13:36
Current system time on haproxy-wi 11:36 (GMT) with regional setting of GMT+2 (thus `date` = 13:36)
Config files gets saved with timestamp of 09:36
/var/www/haproxy-wi/configs/hap_config/192.168.110.11-2019-10-07.09:36:32.cfg 

That's a 4 hour difference.

Changing haproxy-wi from "etc/gmt+2" to "etc/gmt" results in a 2 hour difference.
Changing haproxy-wi from "etc/gmt+2" to "etc/gmt-2" results in a zero hour difference.

Almost looks like it's inverse of what it should be.

**Comment by Aidaho12** [comment]
Try change timezone in the settings

**Comment by rabievdm** [comment]
Hi,

I did, that's how I worked out that setting the timezone in settings to GMT_minus_value resulted in a config with GMT_plus_value timestamp :)

--snip--
Changing haproxy-wi from "etc/gmt+2" to "etc/gmt" results in a 2 hour difference.
Changing haproxy-wi from "etc/gmt+2" to "etc/gmt-2" results in a zero hour difference.
--snip--

R

**Comment by Aidaho12** [comment]
Interesting... Did you tried sets exactly in timezone? I meen: USA/New-york for example

**Comment by rabievdm** [comment]
Very curious.
Yes that seemed to work, normally I can do Etc/GMT+2 or Africa/Johannesburg (both are GMT+2)
But now that you mention it I had a similar issue with another python based app which had the same issue and work around (the dev ended up fixing that one).
I needed the etc/gmt+2 working for the other app, but I am happy to use the full timezone name in this instance. You can close the bug if you want.
