### ISSUE TITLE
Upgrading from manual installation to rpm

### ISSUE THREAD

**Issue by SchutteDaniel** [Aidaho12/haproxy-wi#155]
What is the procedure to upgrade or migrate from an installed manual installation, to an rpm based installation?  Is it possible to do so without losing existing configuration information?

**Comment by Aidaho12** [comment]
Backup config folder, haproxy-wi.db and haproxy-wi.cfg and try install rpm

And please, provide me information how it was )

**Comment by SchutteDaniel** [comment]
I updated the manual installation to the newest version using the update script.
I then moved the manual installation directory  to a new location, and installed the RPM, then I copied the files / database as suggested from the old config over the newly installed directories.

I get this message at the top of the html screen:
Cannot insert version
Investigating further

**Comment by Aidaho12** [comment]
check DB owner and permissions

**Comment by Aidaho12** [comment]
How you doing? did you succeed?
