### ISSUE TITLE
Wont install on Ubuntu 18.04

### ISSUE THREAD

**Issue by SmoothAdmin** [Aidaho12/haproxy-wi#156]
![image](https://user-images.githubusercontent.com/37107447/66693056-a0389380-ec72-11e9-9bf8-1af8f48cb669.png)

This after doing the manual install at line - pip3 install -r haproxy-wi/requirements.txt 

Please resolve as soon as you can!

Thanks,

**Comment by Aidaho12** [comment]
Install before gcc
--
Отправлено из Mail.ru для Android суббота, 12 октября 2019г., 05:02 +03:00 от SmoothAdmin  notifications@github.com :

**Comment by SmoothAdmin** [comment]
Not sure what you mean by this? If I install Ubuntu 18.04 desktop, then install haproxy 1.8 and then do the manual install of haproxy-wi I get this problem. I haven't installed anything else other than what normally comes with the OS itself.

**Comment by Aidaho12** [comment]
I mean that you have to install gcc and  g++ 
--
Отправлено из Mail.ru для Android воскресенье, 13 октября 2019г., 00:32 +03:00 от SmoothAdmin  notifications@github.com :
