### ISSUE TITLE
Notice of new version, but no updated RPM...yet :)

### ISSUE THREAD

**Issue by rabievdm-apx** [Aidaho12/haproxy-wi#157]
Please build and deploy 4.5.3 to the yum repo.
Pretty please :)

**Comment by Aidaho12** [comment]
There is the new version. Please read https://haproxy-wi.org/updates.py

**Comment by rabievdm-apx** [comment]
Agreed, it's seeing the updates there, but now RPM is available.
Also I just tried going to the repo itself and it's prompting for a user/pass:
http://repo.haproxy-wi.org/el7/repodata/repomd.xml: [Errno 14] HTTP Error 401 - Unauthorized

**Comment by Aidaho12** [comment]
Have you read link? Now need have creds for access to repo

**Comment by rabievdm-apx** [comment]
:(
