### ISSUE TITLE
how to setup ssh credentials and setup servers?

### ISSUE THREAD

**Issue by genuiner** [Aidaho12/haproxy-wi#158]
please give a how-to-use guide.
I have complished installation and login into the website, but I have not idea how to setup basic parameters, for example, how to setup servers, what's the fuction of users and groups,ssh credentials...etc, thank you for your greate work, but I have met problems above, I hope you can help me, Thanks!

**Comment by Aidaho12** [comment]
Hi, thanks )

How setup servers and other stuff you can see in the video https://youtu.be/4IJuRrxcxcg?t=108

**Comment by Aidaho12** [comment]
Or here has full descriptions https://haproxy-wi.org/description.py
