### ISSUE TITLE
could not create haproxy in 3.5.4

### ISSUE THREAD

**Issue by genuiner** [Aidaho12/haproxy-wi#159]
Hi, Aidhao, thank you for your greate work, I have seen the demo video on Youtube, but after following your guide in the video: create group, create user, create ssh credential, create server... all of works above have been done,  and installed haproxy which version is 1.5.18, but I can not see the server in the overview page, clicking  the refresh button but the same result, then I want to create a haproxy in the haproxy menu, but I have not a server to choose, where is the server?   I see another server menu in the haproxy menu, how is the difference between this server and the server i have created in the admin area menu?
waiting for your help, thanks

**Comment by Aidaho12** [comment]
I can't help you without logs and screens 
And if you have so many problems at starts how about support? I mean donate and I will do everything

**Comment by genuiner** [comment]
I'd like to donate this project, but I have no paypal account and US$ because I live in China. Maybe I will donate this project if you have a wechat account Alipay account one day.
I am very glad because I have solved this problem because I did not enable this server, now this project is working perfectly, I will also contribute my code to this project.
Thank you very much!

**Comment by Aidaho12** [comment]
You are welcome)
--
Отправлено из Mail.ru для Android вторник, 15 октября 2019г., 09:03 +03:00 от genuiner  notifications@github.com :

**Comment by charnet1019** [comment]
Can Alipay or WeChat Pay be accessed, otherwise users in China cannot donate  @Aidaho12

**Comment by Aidaho12** [comment]
Unfortunately no, probably bank transfer? Try to write to sales@edgeam.am
