### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by tgi-itwhk** [Aidaho12/haproxy-wi#16]
I constantly get the below error message

What the fuck?! U r hacker Oo?!

Any ideas what can cause this?

**Comment by Aidaho12** [comment]
Try re-login, It error meens, what you didn't have token

**Comment by tgi-itwhk** [comment]
Still the same error. Even when trying to view SSL Certificates

**Comment by Aidaho12** [comment]
it's at all pages, or only wheh view ssl?

**Comment by Aidaho12** [comment]
Change this file at app folder
[add.zip](https://github.com/Aidaho12/haproxy-wi/files/2067757/add.zip)
