### ISSUE TITLE
Wont install on Ubuntu 18.04 still.

### ISSUE THREAD

**Issue by SmoothAdmin** [Aidaho12/haproxy-wi#162]
I did a sudo apt install gcc and sudo apt install g++ on my Ubuntu 18.04 desktop, even did some pending patching and restarted the VM. When I run the "pip3 install -r haproxy-wi/requirements.txt" this time I added "sudo" at the beginning once I went into "cd /var/www/". I get the same error message as before. 

![image](https://user-images.githubusercontent.com/37107447/67439590-a7da2f80-f5c4-11e9-92d9-4a1513fb1333.png)

**Comment by Aidaho12** [comment]
Try do next: apt-get install openldap-dev

**Comment by SmoothAdmin** [comment]
Will try it



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by SmoothAdmin** [comment]
Tried your command and got "unable to locate page openldap-dev"

![image](https://user-images.githubusercontent.com/37107447/67521989-e7168800-f679-11e9-9b47-23a6e042e6a9.png)

**Comment by SmoothAdmin** [comment]
Go further along when I removed the openldap-dev. 

But it still fails.

And I am running the command with "sudo" to install it. 

![image](https://user-images.githubusercontent.com/37107447/67522447-be42c280-f67a-11e9-8ca1-c9cb3c96ef14.png)

**Comment by Aidaho12** [comment]
Read please output again and find the reason
--
Отправлено из Mail.ru для Android четверг, 24 октября 2019г., 23:24 +03:00 от SmoothAdmin  notifications@github.com :

**Comment by SmoothAdmin** [comment]
I am doing this from a fresh Ubuntu install. It's clear you a special modified version of *nix installed on your machine otherwise your scripts would work flawlessly. I just tried this on centos fresh install and got the same errors... I guess I will have pay a company to host this. Thanks for wasting my time. Good luck!

**Comment by Aidaho12** [comment]
I'm use centos without any modification.

Read this, maybe you will recognize error https://github.com/Aidaho12/haproxy-wi/issues/164
