### ISSUE TITLE
create_db.py Fails

### ISSUE THREAD

**Issue by FvdLaar** [Aidaho12/haproxy-wi#163]
When I run create_db.py for a clean install I get:

sudo ./create_db.py

<div class="alert alert-danger">
An error occurred: 1067 (42000): Invalid default value for 'exp'
</div>
Updating... go to version 3.2
An error occurred: 1067
DB was update to 3.2.3
DB was update to 3.2.8
DB was update to 3.3
Updating... go to version 3.4.1
Updating... go to version  3.4.5.2
Cannot insert version
DB was update to 3.4.9.5
Traceback (most recent call last):
  File "./create_db.py", line 516, in <module>
    update_all()
  File "./create_db.py", line 491, in update_all
    update_to_hash()
  File "./create_db.py", line 450, in update_to_hash
    cur_ver = cur_ver.replace('.','')
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by Aidaho12** [comment]
Edit sql.py like this:
```
def update_db_v_3_4_5_22(**kwargs):
	con, cur = get_cur()
	sql = """insert into version ('version') values ('3.4.5.2'); """
	try:    
		cur.execute(sql)
		con.commit()
	except sqltool.Error as e:
		print('Cannot insert version %s' % e)
	cur.close() 
	con.close()
```
and try again

**Comment by FvdLaar** [comment]
Thanks for swift reply! Result is:

Updating... go to version  3.4.5.2
Cannot insert version 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''version') values ('3.4.5.2')' at line 1
DB was update to 3.4.9.5


Running MySQL Ver 14.14 Distrib 5.7.27, for Linux

**Comment by Aidaho12** [comment]
try this:
```
sql = """insert into `version` ('version') values ('3.4.5.2'); """
```

**Comment by FvdLaar** [comment]
Directly in MYSQL:

mysql> INSERT INTO version VALUES ('3.4.5.2');
Query OK, 1 row affected (0.00 sec)

But via script :

Cannot insert version 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''version') values ('3.4.5.2')' at line 1
DB was update to 3.4.9.5

**Comment by Aidaho12** [comment]
Thank you, I will fix it
--
Отправлено из Mail.ru для Android четверг, 24 октября 2019г., 13:38 +03:00 от Frank van de Laar  notifications@github.com :

**Comment by FvdLaar** [comment]
Changing to 

sql = """INSERT INTO version VALUES ('3.4.5.2'); """

seems to do the trick!

**Comment by Aidaho12** [comment]
afterward did ok? did create_db.py exit without errors?

**Comment by FvdLaar** [comment]
Yep, but ..

Running sudo -u www-data ./overview.py gives:

Content-type: text/html
Content-type: text/html
Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/sql.py", line 376, in delete_old_uuid
    cur.execute(sql)

mysql.connector.errors.ProgrammingError: 1146 (42S02): Table 'haproxywi.uuid' doesn't exist
And in MySQL a table UUID is missing as well as a table TOKEN.

In sql.py on line 376 following code is causing the issue:
sql = """ delete from uuid where exp < now() or exp is NULL """
sql1 = """ delete from token where exp < now() or exp is NULL """

**Comment by Aidaho12** [comment]
try insert into mysql haproxy-wi.db.sql

**Comment by FvdLaar** [comment]
Gives:

ERROR 1067 (42000) at line 12 in file: '/home/frank/haproxy-wi.db.sql': Invalid default value for 'exp'

Where line 12 is:

CREATE TABLE IF NOT EXISTS `uuid` (`user_id` INTEGER NOT NULL, `uuid` varchar ( 64 ),`exp` DATETIME default '0000-00-00 00:00:00');

**Comment by Aidaho12** [comment]
try this:
```
CREATE TABLE IF NOT EXISTS `uuid` (`user_id` INTEGER NOT NULL, `uuid` varchar ( 64 ),`exp` DATETIME default CURRENT_TIMESTAMP);
```

**Comment by Aidaho12** [comment]
It's hard live without server where I can test :)   :`(

**Comment by FvdLaar** [comment]
No problem, I can test directly

Works directly in mysql ! Should line 13 be chanced as well?

CREATE TABLE IF NOT EXISTS `token` (`user_id` INTEGER,  `token` varchar ( 64 ),`exp` DATETIME default CURRENT_TIMESTAMP);

**Comment by Aidaho12** [comment]
Yes, should
--
Отправлено из Mail.ru для Android четверг, 24 октября 2019г., 14:09 +03:00 от Frank van de Laar  notifications@github.com :

**Comment by FvdLaar** [comment]
And line 16 should be changed too I thing:

CREATE TABLE IF NOT EXISTS `metrics` (`serv` varchar(64), curr_con INTEGER, cur_ssl_con INTEGER, sess_rate INTEGER, max_sess_rate INTEGER,`date`  DATETIME default CURRENT_TIMESTAMP);

**Comment by Aidaho12** [comment]
Yes, all default value have to changed 
--
Отправлено из Mail.ru для Android четверг, 24 октября 2019г., 14:12 +03:00 от Frank van de Laar  notifications@github.com :

**Comment by FvdLaar** [comment]
And then line 18 give a problem:

CREATE TABLE IF NOT EXISTS `version` (`version` varchar(64), `hash` INTEGER NOT NULL DEFAULT 1,);

Because at the end ,); should be without , thus );

**Comment by Aidaho12** [comment]
Oh... How many errors (
--
Отправлено из Mail.ru для Android четверг, 24 октября 2019г., 14:19 +03:00 от Frank van de Laar  notifications@github.com :

**Comment by FvdLaar** [comment]
No problem, I you have the time, we'll fix them together. Here an other one:

Running create_db.py freshly now gives:

Updating... go to version  3.4.5.2
Cannot insert version 1136 (21S01): Column count doesn't match value count at row 1
DB was update to 3.4.9.5

**Comment by Aidaho12** [comment]
Line 18 should be:
```
CREATE TABLE IF NOT EXISTS `version` (`version` varchar(64));
```
without hash 

>No problem, I can test directly

I'm about that I cannot test it on my own, because I haven't enough servers for whole test

**Comment by Aidaho12** [comment]
>Cannot insert version 1136 (21S01): Column count doesn't match value count at row 1

Try delete this table, and re-create without hash

**Comment by FvdLaar** [comment]
Done. Just started fresh again. create_db.py executed without any errors.
But executing overview.py gives error on line 40 :

File "./overview.py", line 40, in <module>
    role = sql.get_user_role_by_uuid(user_id.value),
AttributeError: 'NoneType' object has no attribute 'value'

As there is no data in table UUID I can understant this.

**Comment by Aidaho12** [comment]
Yes, that's ok

**Comment by FvdLaar** [comment]
But visiting teh haproxy-wi website gives "download overviwe.py"  and that is because overview.py produces that error on line 40. So we should fix that first I think.

**Comment by Aidaho12** [comment]
No, show me please httpd config for haproxy-wi

**Comment by FvdLaar** [comment]
haproxy-wi.conf contains:

<VirtualHost *:8080>
#        SSLEngine on
#        SSLCertificateFile /var/www/haproxy-wi/app/certs/haproxy-wi.crt
#        SSLCertificateKeyFile /var/www/haproxy-wi/app/certs/haproxy-wi.key

        ServerName meterkast
        ErrorLog /var/log/apache2/haproxy-wi.error.log
        CustomLog /var/log/apache2/haproxy-wi.access.log "combined"
        TimeOut 600
        LimitRequestLine 16380

        DocumentRoot /var/www/haproxy-wi
        ScriptAlias /cgi-bin/ "/var/www/haproxy-wi/app/"

        <Directory /var/www/haproxy-wi/app>
                Options +ExecCGI
                AddHandler cgi-script .py
                Order deny,allow
                Allow from all
        </Directory>

        <Directory /var/www/haproxy-wi/app/certs>
                Options +ExecCGI -Indexes +MultiViews
                Order Deny,Allow
                Deny from all
        </Directory>

        <Directory /var/www/haproxy-wi/keys>
                Options +ExecCGI -Indexes +MultiViews
                Order Deny,Allow
                Deny from all
        </Directory>

        <FilesMatch "\.cfg$">
                Order Deny,Allow
                Deny from all
        </FilesMatch>

        <FilesMatch "\.db$">
                Order Deny,Allow
                Deny from all
        </FilesMatch>
LogLevel debug
</VirtualHost>

**Comment by Aidaho12** [comment]
Looks like normal... why apache can execute .py files... Have something in apache logs?

**Comment by FvdLaar** [comment]
I discovered something very very strange. I copied overview.py with p flag to test.py and opened [hostname]:8080/app/test.py

That works! (But I don't have any credentials hence can't pass beyond the Login screen.

I can also run[hostname]:8080 but with line 14 in index.html changed to url=/app/test.py

**Comment by Aidaho12** [comment]
Really strange...

Default login and pass are admin admin

**Comment by FvdLaar** [comment]
OK credentials are working. But it only works if I rename overview.py into something else. Don't know why. If I find the answer I'll come back here.

**Comment by Aidaho12** [comment]
check owners and permissions firstly

**Comment by FvdLaar** [comment]
Changed overview.py to mainview.py in /index.html and /app/template/base.html. No problems.

Ownership and permissions:
-rwxr-xr-x  1 www-data www-data  1876 Oct 24 11:41 overview.py
-rwxr-xr-x  1 www-data www-data  1877 Oct 24 14:23 mainview.py

The 1 byte size difference is "Overview" versus "Main view" which is 1 character longer

**Comment by Aidaho12** [comment]
Interesting why)
--
Отправлено из Mail.ru для Android четверг, 24 октября 2019г., 15:32 +03:00 от Frank van de Laar  notifications@github.com :

**Comment by FvdLaar** [comment]
I have no clue why overview.py is NOT being executed but DOWNLOADED while mainview.py (exactly the same script) is being executed. May there is still something in a cache?? Will check later.
