### ISSUE TITLE
error in centos 7

### ISSUE THREAD

**Issue by mgilank** [Aidaho12/haproxy-wi#164]
hi
i got this error 
`mkdir: cannot create directory ‘/var/www/haproxy-wi/app/certs’: File exists
An error occurred: 1045 (28000): Access denied for user 'haproxy-wi'@'localhost' (using password: YES)
Traceback (most recent call last):
  File "./create_db.py", line 515, in <module>
    create_table()
  File "./create_db.py", line 66, in create_table
    con, cur = get_cur()
TypeError: 'NoneType' object is not iterable
`

**Comment by Aidaho12** [comment]
hi

Do you use sudo to run install.sh ?

**Comment by Aidaho12** [comment]
if root user than don't

You want to use mysql DB?

**Comment by Aidaho12** [comment]
first off create user in mysql and DB for haproxy-wi :)

**Comment by Aidaho12** [comment]
```
Access denied for user
```

I think by this error must be clear where is error. Look for where exactly you were mistake

**Comment by mgilank** [comment]
i have grant all for user haproxy-wi

**Comment by Aidaho12** [comment]
Have you editted haproxy-wi.cfg?
--
Отправлено из Mail.ru для Android четверг, 24 октября 2019г., 13:30 +03:00 от Gilang  notifications@github.com :
