### ISSUE TITLE
Unable to add server (User not selectable)

### ISSUE THREAD

**Issue by xpingjockey** [Aidaho12/haproxy-wi#167]
![image](https://user-images.githubusercontent.com/1057073/67588914-81c3a500-f714-11e9-8e4f-75e14e0ff7be.png)

After installing on ubuntu 18.04, using mysql (maria), I"m seeing the issues as attached. I can't select a user to add a server.

[Fri Oct 25 16:33:53.667418 2019] [cgi:error] [pid 84966] [client 192.168.223.178:62987] AH01215: Traceback (most recent call last):: /var/www/haproxy-wi/app/overview.py, referer: https://192.168.223.5:8443/
[Fri Oct 25 16:33:53.667540 2019] [cgi:error] [pid 84966] [client 192.168.223.178:62987] AH01215:   File "/var/www/haproxy-wi/app/overview.py", line 40, in <module>: /var/www/haproxy-wi/app/overview.py, referer: https://192.168.223.5:8443/
[Fri Oct 25 16:33:53.667602 2019] [cgi:error] [pid 84966] [client 192.168.223.178:62987] AH01215:     role = sql.get_user_role_by_uuid(user_id.value),: /var/www/haproxy-wi/app/overview.py, referer: https://192.168.223.5:8443/
[Fri Oct 25 16:33:53.667669 2019] [cgi:error] [pid 84966] [client 192.168.223.178:62987] AH01215: AttributeError: 'NoneType' object has no attribute 'value': /var/www/haproxy-wi/app/overview.py, referer: https://192.168.223.5:8443/

**Comment by Aidaho12** [comment]
Did you add credentials before? 
--
Отправлено из Mail.ru для Android пятница, 25 октября 2019г., 19:48 +03:00 от Geoff  notifications@github.com :

**Comment by xpingjockey** [comment]
Yep.
![image](https://user-images.githubusercontent.com/1057073/67589369-8046ac80-f715-11e9-9078-83b6e421b007.png)

**Comment by Aidaho12** [comment]
I told about credentials, look at credentials tab
--
Отправлено из Mail.ru для Android пятница, 25 октября 2019г., 19:52 +03:00 от Geoff  notifications@github.com :
