### ISSUE TITLE
changes

### ISSUE THREAD

**Issue by SmoothAdmin** [Aidaho12/haproxy-wi#168]
I see you have updated the page and the installation notes. However the "sudo apt-get install...." fails. I am running a fresh copy of Ubuntu Server 18.04.3 LTS (located here - https://ubuntu.com/download/server)

This is what happens when I run the command. 

![image](https://user-images.githubusercontent.com/37107447/67613245-5921c680-f779-11e9-9a60-ba858679e55a.png)

**Comment by Aidaho12** [comment]
Yes, but there isn't package for Ubuntu, only for centos. And any way, before you have to have access to repository. You can get it only after donate
--
Отправлено из Mail.ru для Android суббота, 26 октября 2019г., 05:47 +03:00 от SmoothAdmin  notifications@github.com :

**Comment by Aidaho12** [comment]
Why you create new issues at the same title?)

Google please, I am not Google to solve your problems, if you cannot admin linux i think you should hire sysadmin :)
