### ISSUE TITLE
So you are...

### ISSUE THREAD

**Issue by SmoothAdmin** [Aidaho12/haproxy-wi#169]
So you are forcing people to pay for your product?

Thanks,

**Comment by Aidaho12** [comment]
A little bit... Project demands money for infrastructure, but nobody wants to donate.... And maybe their convenient will motivate them for donate. And also I can  support haproxy-wi for them

**Comment by SmoothAdmin** [comment]
Makes sense.

**Comment by Aidaho12** [comment]
I hope ) But now project still alive only because of  was 1 donate and I still want to work with haproxy-wi... but how long it will be... )

**Comment by Aidaho12** [comment]
By the way... it's one of the reasons why so bad support ubuntu

**Comment by SmoothAdmin** [comment]
Not to nit pick. $50 a month ($600 a year) is a bit too high for folks who aren't a enterprise class user/business. I use HAProxy on my pfSense on my homelab. I think maybe you might find yourself having more supporters if the price was geared to that. You could always limit it in some way for those who don't need everything, and unlock it for those who want to use it in their enterprise for a higher price. It's food for thought! :)

**Comment by Aidaho12** [comment]
50$ it's recommened price... I will reduce, I think so..

> and unlock it for those who want

Yes, I think about it, but it is open source, and anybody can read code and delete lock parts

**Comment by SmoothAdmin** [comment]
So there is a commercial HAProxy GUI, I suspect they host it, its called Snapt, but they least they charge is $450 USD a year. So as you mentioned you are open source. Can you see the dilemma of pay $50 a month for open source where it costs $450 a year for a commercial product? Both prices are out of my budget for homelab. 

Here is the site and their pricing. https://www.snapt.net/pricing/overview

I only use my pfSense / HAProxy when I need to add a new site, I don't ever use any of the monitoring features (though they aren't anything like what you have). I just set it and go.

**Comment by Aidaho12** [comment]
>its called Snapt, but they least they charge is $450 USD a year
450$ it's only for 5 Upstreams. If you look at enterprise tab you will surprised prices the most cheap is $4900

**Comment by Aidaho12** [comment]
By the way I reduced to $25
