### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by maartee** [Aidaho12/haproxy-wi#17]
This interface looks great. However, I am concerned about security, using either SSH root password or private key for root through web interface seems a risk. Where is the key stored then, can it be password protected with some timeout? I would like to use sudo, with limited rights. Is it possible? What would you recommend? Thanks!

**Comment by Aidaho12** [comment]
Yes, you can use sudo users starting with some version there, I do not remember with which one) Sudo users must be without password

**Comment by maartee** [comment]
Thanks, I think sudo and sshd_config additional options ('Match User / Address') will serve well my needs.
