### ISSUE TITLE
Metrics graph problems

### ISSUE THREAD

**Issue by LemurTech** [Aidaho12/haproxy-wi#172]
I am using HAProxy 1.5.18 to load balance SMTP connections (TCP 25, 465, 587). The metrics graph seems to display only connections for port 25. Also, the Y-axis is limited to 1, no matter there are more than 1 connection to graph. Any ideas would be appreciated.

![image](https://user-images.githubusercontent.com/3136325/67707932-97d19f80-f978-11e9-85a6-caac19d33767.png)

**Comment by Aidaho12** [comment]
>Also, the Y-axis is limited to 1

Y asix is auto-scalling 

>display only connections for port 25

There are all proxys. I think you can try do more often statistics fence in the metrics_worker.py and it will more points

**Comment by LemurTech** [comment]
I understand that the Y-axis should be auto-scaling when values are over 1.0, but it is not doing so for some reason.

**Comment by LemurTech** [comment]
I'm sorry... It started working. There seems to be some situation in which it does not auto-scale, but that is not yet clear to me. If I determine what that is, I will follow-up. Sorry for the confusion.
