### ISSUE TITLE
dont work for me please help

### ISSUE THREAD

**Issue by GermanKingYT** [Aidaho12/haproxy-wi#174]
- Unit checker_haproxy.service has finished shutting down.
Nov 04 00:13:58 kvm-4179-12187 systemd[1]: Started Haproxy backends state checker.
-- Subject: Unit checker_haproxy.service has finished start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit checker_haproxy.service has finished starting up.
--
-- The start-up result is done.
Nov 04 00:13:58 kvm-4179-12187 systemd[18669]: checker_haproxy.service: Failed at step EXEC spawning /var/www/haproxy-wi/app/tools
-- Subject: Process /var/www/haproxy-wi/app/tools/checker_master.py could not be executed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The process /var/www/haproxy-wi/app/tools/checker_master.py could not be executed and failed.
--
-- The error number returned by this process is 13.
Nov 04 00:13:58 kvm-4179-12187 systemd[1]: checker_haproxy.service: Main process exited, code=exited, status=203/EXEC
Nov 04 00:13:58 kvm-4179-12187 systemd[1]: checker_haproxy.service: Unit entered failed state.
Nov 04 00:13:58 kvm-4179-12187 systemd[1]: checker_haproxy.service: Failed with result 'exit-code'.

**Comment by GermanKingYT** [comment]
debian 9

**Comment by GermanKingYT** [comment]
and i becomme this error too 
root@kvm-4179-12187 ~ # apt-get install git  net-tools lshw dos2unix apache2 gcc netcat python3.5 python3.5-mod_wsgi mod_ssl python3-pip g++ freetype2-demos libatlas-base-dev openldap-dev libpq-dev python-dev libxml2-dev libxslt1-dev libldap2-dev libsasl2-dev libffi-dev python3-dev libssl-dev -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3.5-mod_wsgi
E: Couldn't find any package by glob 'python3.5-mod_wsgi'
E: Couldn't find any package by regex 'python3.5-mod_wsgi'
E: Unable to locate package mod_ssl
E: Unable to locate package openldap-dev

**Comment by GermanKingYT** [comment]
google dont help me dont find fixes for that i think i can add some links in the sources.list but dont know

**Comment by Aidaho12** [comment]
Hi,
Try find out who names exactly that packages names which didn't install, when you install them, try reinstall requirements. If won't help you should use centos 7
