### ISSUE TITLE
testing but adding a frontend fails

### ISSUE THREAD

**Issue by geosone** [Aidaho12/haproxy-wi#175]
[Wed Nov 06 11:07:37.032311 2019] [cgi:error] [pid 20489] [client 192.168.11.95:34264] AH01215:     backend = "    default_backend " + form.getvalue('backend') + "\\n", referer: http://haproxy-wi.....:8080/app/add.py
[Wed Nov 06 11:07:37.032396 2019] [cgi:error] [pid 20489] [client 192.168.11.95:34264] AH01215: TypeError: Can't convert 'NoneType' object to str implicitly, referer: http://haproxy-wi......:8080/app/add.py

**Comment by Aidaho12** [comment]
Where have you been taught courtesy ...

Hi,

edit please add.py:
```
backend = " default_backend " + form.getvalue('backend')
```
to
```
backend = " default_backend " + form.getvalue('backends')
```

**Comment by geosone** [comment]
thx for the quick reply 

its working now

**Comment by Aidaho12** [comment]
You are welcome )
