### ISSUE TITLE
Can't connect to HAproxy

### ISSUE THREAD

**Issue by cptLamo** [Aidaho12/haproxy-wi#176]
Hello! Thanks for your work but i have issue.
When i add server, and then go to Overview, i see "Can't connect to HAproxy"
I found out setting called " haproxy_sock_port", and when i'm changing it for example on 80, i go back to Overview and error disappear, but another error appear on column "Front/Back-ends" with error 400. 
So, where can i find information about sock port ? Thanks =)

**Comment by Aidaho12** [comment]
You are welcome :)

**Comment by cptLamo** [comment]
Sorry, there was a holiday, and i forgot about the problem =)
I saw this config earlier but there is a problem.
I have a block "Listen stats" and "bind :9000" in it, to open default gui. I check open ports by command "nestat -tulpn | grep LISTEN"  and see open port 9000. But when i apply your config and check open ports, i don't see 9000 and 1999 eather.
