### ISSUE TITLE
Fatal Error @CentOS7 installation

### ISSUE THREAD

**Issue by vlpeng** [Aidaho12/haproxy-wi#178]
Startup and install by Manual > CentOS, however experience the following error @ CentOS7

<img width="1384" alt="11" src="https://user-images.githubusercontent.com/806825/69118102-21cedd00-0acd-11ea-8f94-3d52ded8567d.png">

**Comment by Aidaho12** [comment]
Try to install linux-headers and libc-devel

**Comment by vlpeng** [comment]
> Try to install linux-headers and libc-devel

Bug fixed, installation is completed without any issue.
