### ISSUE TITLE
update_db.py

### ISSUE THREAD

**Issue by mattgreen80** [Aidaho12/haproxy-wi#18]
When this is run it returns an error "column email is not unique". I have been unable to add any frontends, backends etc through the wi and i think this might be the cause?

![image](https://user-images.githubusercontent.com/35184210/41829017-7b464078-788c-11e8-9cf5-b144a3711e44.png)

**Comment by Aidaho12** [comment]
No, it's normal. Show me apache error logs

**Comment by mattgreen80** [comment]
[haproxy-wi.error.log](https://github.com/Aidaho12/haproxy-wi/files/2131678/haproxy-wi.error.log)

**Comment by Aidaho12** [comment]
Check folder /var/www/haproxy-wi/configs/hap_config/ permisions and ssh cred, "Overview" page open normaly?

**Comment by mattgreen80** [comment]
Yes the overview page does. 
Here are permissions:
![image](https://user-images.githubusercontent.com/35184210/41830115-00998cd4-7893-11e8-89dc-d514d8871880.png)

ssh is configured with just user and password - no cert.

**Comment by mattgreen80** [comment]
That folder has rwx for owner (apache) rx for group and rwx for other

**Comment by mattgreen80** [comment]
I am working in centos. but using winscp to browse file system

**Comment by Aidaho12** [comment]
Ok, try:
```
# cd /var/www/haproxy-wi/app/
# sqlite3 haproxy-wi.db
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> .schema cred
CREATE TABLE "cred" (
                                `id` integer primary key autoincrement,
                                `name`  VARCHAR ( 64 ),
                                `enable`        INTEGER NOT NULL DEFAULT 1,
                                `username`      VARCHAR ( 64 ) NOT NULL,
                                `password`      VARCHAR ( 64 ) NOT NULL
                        );
sqlite> 
```

If there is another schema, run again update_db.py and show me output

**Comment by mattgreen80** [comment]
![image](https://user-images.githubusercontent.com/35184210/41830818-543a86f0-7897-11e8-9225-bcbe68867fd7.png)

**Comment by mattgreen80** [comment]
I did reinstall with MySQL to see if that would fix the problem. Should i run install.sh again and choose sqllite?

**Comment by Aidaho12** [comment]
No, you may change sql settings in config.

With mysql it work?

**Comment by mattgreen80** [comment]
No, still the same problem. It says success when adding a frontend but nothing changes in the config file and no frontend appears. Also I can't upload SSL certs.

**Comment by mattgreen80** [comment]
I'll try reinstalling everything from scratch. Thank you for your help.

**Comment by Aidaho12** [comment]
sudo user without password work or it root?

**Comment by mattgreen80** [comment]
I am logged in as root

**Comment by Aidaho12** [comment]
hm... interting...  Haproxy-WI can not upload haproxy config localy.. why? )

**Comment by mattgreen80** [comment]
![image](https://user-images.githubusercontent.com/35184210/41831147-81ab39ca-7899-11e8-95b6-3096928ed333.png)

**Comment by Aidaho12** [comment]
Owner same user as apache?

**Comment by mattgreen80** [comment]
![image](https://user-images.githubusercontent.com/35184210/41831309-529240ce-789a-11e8-814e-59c1ea903c2e.png)

**Comment by mattgreen80** [comment]
![image](https://user-images.githubusercontent.com/35184210/41831323-79216738-789a-11e8-9df8-58350d17b725.png)

**Comment by Aidaho12** [comment]
Change logs owner to apahce and check

**Comment by mattgreen80** [comment]
No luck.

**Comment by Aidaho12** [comment]
Very intersting...

**Comment by Aidaho12** [comment]
what was the problem?
--
Отправлено из Mail.Ru для Android вторник, 26 июня 2018г., 03:03 +06:00 от Matt  notifications@github.com :
