### ISSUE TITLE
Having some trouble configuring HAProxy from HAProxy-WI

### ISSUE THREAD

**Issue by abeeftaco** [Aidaho12/haproxy-wi#180]
When I add a server and then attempt installation of HAProxy nothing happens. I had an error message concerning permissions for ansible on /usr/share/httpd/.ansible so I created the folder with apache:apache permissions. Now the installation is just showing a green box with no text, however it does not apear to install HAProxy because any configurations I attempt afterwards do no seem to work.

![image](https://user-images.githubusercontent.com/56798515/69338152-89516d80-0c30-11ea-86d4-d1535c068951.png)

**Comment by Aidaho12** [comment]
Try give shell for Apache user

**Comment by Aidaho12** [comment]
I think, I have fixed the output, update and try again
