### ISSUE TITLE
Waf have strange behaviour

### ISSUE THREAD

**Issue by cptLamo** [Aidaho12/haproxy-wi#185]
Hello again.
You made a great work with this tool. Thank you!
But i have problem with WAF settings. When i install waf, everything was fine. I check service on my server, and waf is working well. Then i go on gui, and check haproxy/WAF, and it look like it work.
![Screenshot_20191129_101759](https://user-images.githubusercontent.com/48934152/69836143-82f76d00-1292-11ea-84d9-cb159339195f.png)

But when i go to Overview, i see that waf is not working.
![Screenshot_20191129_101745](https://user-images.githubusercontent.com/48934152/69836155-a4585900-1292-11ea-9ef3-68cbcd9ae279.png)

![Screenshot_20191129_105023](https://user-images.githubusercontent.com/48934152/69836664-10888c00-1296-11ea-8c63-618a99d8ff2d.png)
It looks like server-status doesn't pass some check.

Haproxy-wi version 3.6.1
Haproxy version 2.0.7

How can i solve this puzzle?)
Thank you=)

**Comment by cptLamo** [comment]
More than that...
If i install waf from gui, in haproxy/waf appear greenball like everything fine, but button "install" is still there.
![Screenshot_20191129_103746](https://user-images.githubusercontent.com/48934152/69836416-4cbaed00-1294-11ea-8423-a8849c5ad710.png)
It work only when i take your script from repository, made script on my server and run it. And only then something working )

**Comment by Aidaho12** [comment]
Hi, thanks )

Do you have /etc/haproxy/waf/modsecurity.conf ? And which the "haproxy_dir" in settings?

**Comment by cptLamo** [comment]
Before install waf, i edit .bashrc, and add two var path.
export VERSION=2.0.7
export HAPROXY_PATH=/etc/haproxy
Because waf will not install without them. And my system doesn't have them ¯\_(ツ)_/¯
Yes, i have modsecurity.conf. 
And what do you mean about haproxy_dir in settings?) where can i look for it?

**Comment by Aidaho12** [comment]
Show me http error log please

**Comment by cptLamo** [comment]
if you mean /var/log/httpd/..., then i don't have any log file in there =)

**Comment by Aidaho12** [comment]
Hm... it's very strange... They has to be there. There are not on the haproxy-wi server?

**Comment by cptLamo** [comment]
Of course =) sorry, tired a little bit.
I was on haproxy server.
The error log  haproxy-wi.error.log:
```
[Fri Nov 29 12:27:55.471012 2019] [cgi:error] [pid 113299] AH01215:     metrics['chartData']['server'] = server, referer: http://hawebsales.partner.ru/app/metrics.py
[Fri Nov 29 12:27:55.471031 2019] [cgi:error] [pid 113299] AH01215: NameError: name 'server' is not defined, referer: http://hawebsales.partner.ru/app/metrics.py
```
look like problem with variable "server"? (စ_စ)

**Comment by Aidaho12** [comment]
Check in db table waf, there should be id you waf server and "1"

А что можно было на русском?)

**Comment by cptLamo** [comment]
Можно, но я думал вдруг у кого такая же проблема будет. Прочтет, найдет ответ и порадуется =3
Не совсем понял где и что смотреть.

**Comment by Aidaho12** [comment]
Ну вообще да, английский больше понимают чем русский :( поэтому:

I meant:
```
cd /var/www/haproxy-wi/app
sqlite3 haproxy-wi.db
.table
Select * from waf;
```

**Comment by cptLamo** [comment]
well, nothing happend...
![Screenshot_20191129_155721](https://user-images.githubusercontent.com/48934152/69846815-f9ab5f00-12c0-11ea-8b8d-81def6ba60cc.png)

**Comment by Aidaho12** [comment]
Try:
```
insert into waf values ('id_server', '1');
```

**Comment by cptLamo** [comment]
Well, in error_log no more message about undefined "server"
But still, it does't work in Overview =(

**Comment by Aidaho12** [comment]
It's seems like hapwi doesn't have access to modsec config, check permission

**Comment by cptLamo** [comment]
If you mean mod_security, then i don't even have this package on my server.
Firewalld also disable.

**Comment by cptLamo** [comment]
Странно, после всех этих манипуляций, каждый раз когда я обновляю Overview, то Metricks masters и Metricks workers горят то зелеными то красными. А иногда даже и статус самого сервера Haproxy загорается красным...

**Comment by cptLamo** [comment]
В файлике /var/www/haproxy-wi/app/templates/ajax/overview.html осуществляется проверка:
{% elif service.5.0 != '' and service.4|int() >= 1 %}
Откуда он берет переменную service.5.0 и service.4?

**Comment by cptLamo** [comment]
Случайно =)

**Comment by Aidaho12** [comment]
Я имел ввиду конфиг, что лежит в дире хапрокси

Мы включили метрики добавив запись в таблицу, но так как видимо ваф бэкенда нет, то воркер не может стартануть

**Comment by cptLamo** [comment]
Но ведь раньше все воркеры горели зеленым постоянно.
Когда делал установку Waf на хапрокси, то в конце он сказал что waf backend теперь врублен.
Конфиг в дире хапрокси, или хапрокси ви?)
На всфкий случай выдал 777 права на haproxy.cfg на сервере хапрокси, но все равно не работает.

**Comment by Aidaho12** [comment]
By the way, do please next:
```
cat /etc/haproxy/waf/modsecurity.conf  |grep SecRuleEngine |grep -v '#' '"
```

I ment /etc/haproxy/waf/modsecurity.conf

There are metrics log in the "Internal logs" look through there

**Comment by cptLamo** [comment]
SecRuleEngine On
modsecurity.conf have 777 permission

**Comment by Aidaho12** [comment]
Interesting... 
Edit funct.py like this for more logging:
```
for line in stderr.read().decode(encoding='UTF-8'):
			if line:
				print("<div class='alert alert-warning'>"+line+"</div>")
				logging('localhost', ' '+line, haproxywi=1)
```

And after look through haproxy-wi log

**Comment by cptLamo** [comment]
After this, i have 500 error. Everything broken =)
In logs:
```
Fri Nov 29 17:30:22.172832 2019] [cgi:error] [pid 901] [client 10.10.228.134:49750] AH01215: TabError: inconsistent use of tabs and spaces in indentation, referer: http:///
[Fri Nov 29 17:30:22.172838 2019] [cgi:error] [pid 901] [client 10.10.228.134:49750] End of script output before headers: overview.py, referer: http:///
[Fri Nov 29 17:30:26.004641 2019] [cgi:error] [pid 3831] [client 10.10.228.134:49776] AH01215: Traceback (most recent call last):, referer: http:///
[Fri Nov 29 17:30:26.004693 2019] [cgi:error] [pid 3831] [client 10.10.228.134:49776] AH01215:   File "/var/www/haproxy-wi/app/overview.py", line 2, in <module>, referer: http:///
[Fri Nov 29 17:30:26.004704 2019] [cgi:error] [pid 3831] [client 10.10.228.134:49776] AH01215:     import funct, sql, referer: http:///
[Fri Nov 29 17:30:26.004725 2019] [cgi:error] [pid 3831] [client 10.10.228.134:49776] AH01215:   File "/var/www/haproxy-wi/app/funct.py", line 591, referer: http:///
[Fri Nov 29 17:30:26.004746 2019] [cgi:error] [pid 3831] [client 10.10.228.134:49776] AH01215:     logging('localhost', ' '+line, haproxywi=1), referer: http:///
[Fri Nov 29 17:30:26.004766 2019] [cgi:error] [pid 3831] [client 10.10.228.134:49776] AH01215:                                               ^, referer: http:///
```

**Comment by Aidaho12** [comment]
Yep, problems with tabs, do correct numbers of tabs and everything will works )

**Comment by cptLamo** [comment]
well... i don't know python actually...
I'l try with online validator.
for example i'll try here [](http://pep8online.com/checkresult) and no problem. all fine.
But here [](https://pythonbuddy.com/) it told me that:
> ImportError: No module named 'func'
Dunno what's is wrong)

**Comment by Aidaho12** [comment]
Ok, in next release I will add it

**Comment by cptLamo** [comment]
Can i paste my overview.py here, and you help me find, what wrong with tabs?)

**Comment by Aidaho12** [comment]
Problem in funct.py. in overview nothing necessary was do

I can connect to your environment and do that directly, if it possible off course... And if you donate to support project it will great )

**Comment by cptLamo** [comment]
Я ничего не понимаю.
Если сделать команду:
python3 funct.py то он укажет конкретно вот эту команду
`logging('localhost', ' '+line, haproxywi=1)`
Без этой команды сайт то работает, и все работает кроме waf =(

**Comment by Aidaho12** [comment]
Там не правильно указаны пробелы, поэтому ругается и эта строчка нужна для дополнительного логирования, чтобы понять в чем проблема.... А ваф и так должен работать, просто отображение кривое

**Comment by cptLamo** [comment]
Удалил строчку для логов, хотел порадоваться просто сайту запустившемуся, а error_log начал выдавать NameError: name 'metrics_master' is not defined ಥ_ಥ

**Comment by Aidaho12** [comment]
Перезапишите этот файл с гита )

**Comment by cptLamo** [comment]
Ладно, уже почти ночь =)
Огроменное спасибо за помощь. И спасибо за тулзу. Офигенная работа) 
Буду пробовать дальше. Если что, еще напишу =3

**Comment by Aidaho12** [comment]
Хорошо, пишите :)

**Comment by cptLamo** [comment]
Добрый день =)
Вообщем я слегка подредактировал файл overview.html, в том месте где происходит проверка service.5.0, и все заработало как часы.
Спасибо!

**Comment by Aidaho12** [comment]
Доброе утро. Тоже вариант)
