### ISSUE TITLE
Form Method Usability/Security Issue

### ISSUE THREAD

**Issue by sekot** [Aidaho12/haproxy-wi#186]
Hello,

Why do all "html forms" use the GET method?
The amount of data sent with GET is very limited.
The security problem is obvious.

Adding "environ={'REQUEST_METHOD': 'POST'}" in the FieldStorage method and "method='POST'" in the <form> HTML tag will solve this problem.

Regards,

**Comment by Aidaho12** [comment]
I have already answered on this question a few time... Because apache doesn't accept post form... And i don't know why

Try maybe it will work for you

**Comment by sekot** [comment]
Very strange, do you have the Error Log ?

**Comment by Aidaho12** [comment]
Unfortunately no... :(

**Comment by sekot** [comment]
ok this because you call FieldStorage in different files, with POST, probably for security reason, the first file with the call erase the datas. 
So the funct lib is call everywhere  and make the call, so all other file must call "funct.form"
I have attached a patch for that and modify too all GET on POST

**Comment by sekot** [comment]
[fix-method-post.txt](https://github.com/Aidaho12/haproxy-wi/files/3916967/fix-method-post.txt)

**Comment by Aidaho12** [comment]
Awesome ) Can you do pull request?

**Comment by sekot** [comment]
how i do that ? name of the branch, etc ...

**Comment by Aidaho12** [comment]
Just do fork, enter your changes, after create pull request
