### ISSUE TITLE
LDAP/AD configuration

### ISSUE THREAD

**Issue by sekot** [Aidaho12/haproxy-wi#187]
Hello,

That is possible to have LDAP and AD for authentication ?
with adding 3 parmeters  i think it spossible

[Class to search] 
[User attribute to search]
[LDAP search base]

login.py => bind = l.simple_bind_s([Class to search]+'='+user+','+[LDAP search base], password)
options.py => criteria = "(&(objectClass=[Class to search])([User attribute to search]="+username+"))"

Regards,

**Comment by Aidaho12** [comment]
Yes, it's possible

**Comment by Aidaho12** [comment]
And "LDAP search base" is not the same "Base domain. Example: dc=domain, dc=com"

**Comment by sekot** [comment]
I check it
