### ISSUE TITLE
Installation issue in Centos 7

### ISSUE THREAD

**Issue by hpandroid** [Aidaho12/haproxy-wi#188]
Hi I am trying to install haproxy-wi in centos 7 manually. In CentOS 7 python3.5 is not available for yum install then I tried installing 3.4 and tried to install the requirements.txt then I have the following log. Please check if I am doing something wrong.  

Thanks,
Harry

pip3 install -r haproxy-wi/requirements.txt
Collecting configparser==3.5.0
  Using cached https://files.pythonhosted.org/packages/7c/69/c2ce7e91c89dc073eb1aa74c0621c3eefbffe8216b3f9af9d3885265c01c/configparser-3.5.0.tar.gz
Collecting paramiko>=2.5.0
  Using cached https://files.pythonhosted.org/packages/4b/80/74dace9e48b0ef923633dfb5e48798f58a168e4734bca8ecfaf839ba051a/paramiko-2.6.0-py2.py3-none-any.whl
Collecting pytz==2017.3
  Using cached https://files.pythonhosted.org/packages/a3/7f/e7d1acbd433b929168a4fb4182a2ff3c33653717195a26c1de099ad1ef29/pytz-2017.3-py2.py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement requests>=2.22.0 (from -r haproxy-wi/requirements.txt (line 4)) (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.6, 0.10.7, 0.10.8, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9, 0.14.0, 0.14.1, 0.14.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 2.0.0, 2.0.1, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.8.0, 2.8.1, 2.9.0, 2.9.1, 2.9.2, 2.10.0, 2.11.0, 2.11.1, 2.12.0, 2.12.1, 2.12.2, 2.12.3, 2.12.4, 2.12.5, 2.13.0, 2.14.0, 2.14.1, 2.14.2, 2.15.1, 2.16.0, 2.16.1, 2.16.2, 2.16.3, 2.16.4, 2.16.5, 2.17.0, 2.17.1, 2.17.2, 2.17.3, 2.18.0, 2.18.1, 2.18.2, 2.18.3, 2.18.4, 2.19.0, 2.19.1, 2.20.0, 2.20.1, 2.21.0)
ERROR: No matching distribution found for requests>=2.22.0 (from -r haproxy-wi/requirements.txt (line 4))

**Comment by Aidaho12** [comment]
Hi, probably there isn't necessary version for python 3.4

**Comment by Aidaho12** [comment]
You have to install python3.5 or later, otherwise HAProxy-WI won't work

**Comment by hpandroid** [comment]
Hi, 

I tried installing Manually using the below guide.  
In order to install Python35u on a fresh centos installation We need to add the IUSC repo.

Please add the below steps to the Manual install this might be helpful for some people.
**sudo yum -y install yum-utils**
**sudo yum -y groupinstall development**
**sudo yum -y install https://centos7.iuscommunity.org/ius-release.rpm**


`CentOS:
$ sudo 	yum -y install git nmap-ncat net-tools python35u dos2unix python35u-pip mod_ssl httpd python35u-devel gcc-c++ openldap-devel python-devel python-jinja2 python35u-mod_wsgi ansible
$ cd /var/www/
$ git clone https://github.com/Aidaho12/haproxy-wi.git /var/www/haproxy-wi
$ chown -R apache:apache haproxy-wi/

Or if use Debian/Ubuntu:

$ sudo 	apt-get install git  net-tools lshw dos2unix apache2 gcc netcat python3.5 python3.5-mod_wsgi mod_ssl python3-pip g++ freetype2-demos libatlas-base-dev openldap-dev libpq-dev python-dev libxml2-dev libxslt1-dev libldap2-dev libsasl2-dev libffi-dev python3-dev libssl-dev ansible -y
$ git clone https://github.com/Aidaho12/haproxy-wi.git /var/www/haproxy-wi
$ chown -R www-data:www-data haproxy-wi/

Both

$ pip3 install -r haproxy-wi/requirements.txt 
$ chmod +x haproxy-wi/app/*.py 
$ sudo ln -s /usr/bin/python3.5 /usr/bin/python3

**Need to cd haproxy-wi/**

$ sudo cp config_other/logrotate/* /etc/logrotate.d/
$ sudo cp config_other/syslog/* /etc/rsyslog.d/
$ sudo cp config_other/systemd/* /etc/systemd/system/
$ sudo systemctl daemon-reload      
$ sudo systemctl restart httpd
$ sudo systemctl restart rsyslog
$ sudo systemctl restart metrics_haproxy.service
$ sudo systemctl restart checker_haproxy.service
$ sudo systemctl restart keep_alive.service
$ sudo systemctl enable metrics_haproxy.service
$ sudo systemctl enable checker_haproxy.service
$ sudo systemctl enable keep_alive.service
$ sudo mkdir /var/www/haproxy-wi/app/certs
$ sudo mkdir /var/www/haproxy-wi/keys
$ sudo mkdir /var/www/haproxy-wi/configs/
$ sudo mkdir /var/www/haproxy-wi/configs/hap_config/
$ sudo mkdir /var/www/haproxy-wi/configs/kp_config/
$ sudo mkdir /var/www/haproxy-wi/log/
`
After completing the installation.
I have added the vistual host to apache by copy pasting the information given in the instructions. Verified the 'cig-bin' permissions are set to apache.



 I am getting the following error.

Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

I had tried  running the following script, by cloning the project.

 ./create_db.py
Updating... go to version 3.2
DB was update to 3.2.3
DB was update to 3.2.8
DB was update to 3.3
Updating... go to version 3.4.1
Updating... go to version  3.4.5.2
Updating... go to version 3.8.1

Still getting the same error.

[Mon Dec 02 16:48:23.933257 2019] [cgi:error] [pid 43796] [client 192.168.20.177:53096] AH01215: (13)Permission denied: exec of '/var/www/haproxy-wi/app/overview.py' failed, referer: https://192.168.20.129/
[Mon Dec 02 16:48:23.934363 2019] [cgi:error] [pid 43796] [client 192.168.20.177:53096] End of script output before headers: overview.py, referer: https://192.168.20.129/
[Mon Dec 02 17:07:05.181246 2019] [cgi:error] [pid 43797] [client 192.168.20.177:53492] AH01215: (13)Permission denied: exec of '/var/www/haproxy-wi/app/overview.py' failed
[Mon Dec 02 17:07:05.182376 2019] [cgi:error] [pid 43797] [client 192.168.20.177:53492] End of script output before headers: overview.py
[root@localhost app]# ls -l
total 264
-rwxr-xr-x. 1 apache apache  7428 Dec  2 16:36 add.py
drwxr-xr-x. 2 apache apache    50 Dec  2 16:36 certs
-rwxr-xr-x. 1 apache apache  2219 Dec  2 16:36 config.py
-rwxr-xr-x. 1 apache apache 19007 Dec  2 16:36 create_db.py
-rwxr-xr-x. 1 apache apache  1137 Dec  2 16:36 edit.py
-rwxr-xr-x. 1 apache apache 21611 Dec  2 16:36 funct.py
-rw-r--r--. 1 apache apache   504 Dec  2 16:36 haproxy-wi.cfg
-rw-r--r--. 1 root   root   33792 Dec  2 16:48 haproxy-wi.db
-rw-r--r--. 1 apache apache  2973 Dec  2 16:36 haproxy-wi.db.sql
-rwxr-xr-x. 1 apache apache  2563 Dec  2 16:36 hapservers.py
-rwxr-xr-x. 1 apache apache   938 Dec  2 16:36 ha.py
-rw-r--r--. 1 apache apache  1078 Dec  2 16:36 index.html
-rwxr-xr-x. 1 apache apache  2543 Dec  2 16:36 keepalivedconfig.py
-rwxr-xr-x. 1 apache apache  1720 Dec  2 16:36 lists.py
-rwxr-xr-x. 1 apache apache  4913 Dec  2 16:36 login.py
-rwxr-xr-x. 1 apache apache  1507 Dec  2 16:36 logs.py
-rwxr-xr-x. 1 apache apache   798 Dec  2 16:36 metrics.py
-rwxr-xr-x. 1 apache apache 30263 Dec  2 16:36 options.py
-rwxr-xr-x. 1 apache apache  2001 Dec  2 16:36 overview.py
drwxr-xr-x. 2 root   root      92 Dec  2 16:48 __pycache__
drwxr-xr-x. 3 apache apache    90 Dec  2 16:36 scripts
-rwxr-xr-x. 1 apache apache  2593 Dec  2 16:36 sections.py
-rwxr-xr-x. 1 apache apache  1405 Dec  2 16:36 servers.py
-rwxr-xr-x. 1 apache apache 54007 Dec  2 16:36 sql.py
drwxr-xr-x. 4 apache apache  4096 Dec  2 16:36 templates
drwxr-xr-x. 2 apache apache   156 Dec  2 16:36 tools
-rwxr-xr-x. 1 apache apache  1268 Dec  2 16:36 users.py
-rwxr-xr-x. 1 apache apache  2459 Dec  2 16:36 versions.py
-rwxr-xr-x. 1 apache apache  2456 Dec  2 16:36 viewlogs.py
-rwxr-xr-x. 1 apache apache  1162 Dec  2 16:36 viewsttats.py
-rwxr-xr-x. 1 apache apache   839 Dec  2 16:36 waf.py


I had update the file owner for .db file but still the same error.

Can you please tell me what I am still missing.

**Comment by Aidaho12** [comment]
Hm... It's looks like everything is ok... Try execute: python3 and after ./overview.py

**Comment by sekot** [comment]
do you have deactivated selinux ?

**Comment by hpandroid** [comment]
Here is the error that I am getting.
[root@localhost app]# python3 ./overview.py
Content-type: text/html

<meta http-equiv="refresh" content="0; url=login.py?ref=None">
Traceback (most recent call last):
  File "./overview.py", line 42, in <module>
    role = sql.get_user_role_by_uuid(user_id.value),
AttributeError: 'NoneType' object has no attribute 'value'

**Comment by Aidaho12** [comment]
It's ok

What about https://github.com/Aidaho12/haproxy-wi/issues/188#issuecomment-561202992 ?

**Comment by hpandroid** [comment]
It is enabled

**Comment by Aidaho12** [comment]
Disable and try again

**Comment by hpandroid** [comment]
Hi it did worked. But the below error is still exist. is 3.8.1 is a stable version for production use? If not what is the stable version?

> Here is the error that I am getting.
> [root@localhost app]# python3 ./overview.py
> Content-type: text/html
> 
> Traceback (most recent call last): File "./overview.py", line 42, in role = sql.get_user_role_by_uuid(user_id.value), AttributeError: 'NoneType' object has no attribute 'value'

**Comment by Aidaho12** [comment]
Yes, it's stable version. How I sad below this error is ok and it doesn't occur any problems

**Comment by hpandroid** [comment]
@Aidaho12 Thank you so much it did worked. 
I am having trouble installing HAProxy 2.0.9 from the web UI but it keep on struck for ever.
In the credential I have used sudo user with No Password. Again I have given root user to see if it is an issue with permissions.  Even I was unable to load the Log it is giving me error saying "permission denied" I am sure Apache user has permission to read the files. 
Then I end up installing 1.5, But it is not detecting the Ha Proxy in the installation screen in WebUI.

If you have any suggestions please let me know.

Thanks,
Harry

**Comment by Aidaho12** [comment]
RTFM please https://haproxy-wi.org/settings.py
