### ISSUE TITLE
Unable to update haproxy version

### ISSUE THREAD

**Issue by killerunixos** [Aidaho12/haproxy-wi#190]
Please find the error on below 

error: Unhandled error: Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/ansible/config/manager.py", line 554, in update_config_data value, origin = self.get_config_value_and_origin(config, configfile) File "/usr/lib/python2.7/site-packages/ansible/config/manager.py", line 498, in get_config_value_and_origin value = ensure_type(value, defs[config].get('type'), origin=origin) File "/usr/lib/python2.7/site-packages/ansible/config/manager.py", line 121, in ensure_type makedirs_safe(value, 0o700) File "/usr/lib/python2.7/site-packages/ansible/utils/path.py", line 90, in makedirs_safe raise AnsibleError("Unable to create local directories(%s): %s" % (to_native(rpath), to_native(e))) AnsibleError: Unable to create local directories(/usr/share/httpd/.ansible/tmp): [Errno 13] Permission denied: '/usr/share/httpd/.ansible' Traceback (most recent call last): File "/usr/bin/ansible-playbook", line 62, in import ansible.constants as C File "/usr/lib/python2.7/site-packages/ansible/constants.py", line 174, in config = ConfigManager() File "/usr/lib/python2.7/site-packages/ansible/config/manager.py", line 290, in __init__ self.update_config_data() File "/usr/lib/python2.7/site-packages/ansible/config/manager.py", line 566, in update_config_data raise AnsibleError("Invalid settings supplied for %s: %s\n" % (config, to_native(e)), orig_exc=e) ansible.errors.AnsibleError: Invalid settings supplied for DEFAULT_LOCAL_TMP: Unable to create local directories(/usr/share/httpd/.ansible/tmp): [Errno 13] Permission denied: '/usr/share/httpd/.ansible'

**Comment by Aidaho12** [comment]
Create folder .ansible and do apache owner it

**Comment by killerunixos** [comment]
Where i need to create .ansible floder

**Comment by Aidaho12** [comment]
There is path in your log: /usr/share/httpd/.ansible/

**Comment by killerunixos** [comment]
['', 'PLAY [172.16.208.84] ***********************************************************', '', 'TASK [Gathering Facts] *********************************************************', 'fatal: [172.16.208.84]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Could not create directory \'/usr/share/httpd/.ssh\'.\\r\\nFailed to add the host to the list of known hosts (/usr/share/httpd/.ssh/known_hosts).\\r\\nno such identity: /var/www/haproxy-wi/keys/EUSAUTHXPRX01.pem: No such file or directory\\r\\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic,password).", "unreachable": true}', '', 'PLAY RECAP *********************************************************************', '172.16.208.84 : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0 ', '', "error: Can't install Haproxy service

**Comment by Aidaho12** [comment]
Your log has full problem description

**Comment by Aidaho12** [comment]
First of all create folder: /usr/share/httpd/.ssh like previous folder

**Comment by Aidaho12** [comment]
And second error is: no such identity: /var/www/haproxy-wi/keys/EUSAUTHXPRX01.pem: No such file or directory
