### ISSUE TITLE
Unable to create cluster

### ISSUE THREAD

**Issue by hpandroid** [Aidaho12/haproxy-wi#191]
Hi,

I am trying to create a cluster from the KeepAlived > HA but it is giving the below error. I do not have any thing like Manager.pem. I am not sure from where this pem file has been kept in the configuration. Can some one help me with this issue.
['', 'PLAY [192.168.5.7] *************************************************************', '', 'TASK [Gathering Facts] *********************************************************', 'fatal: [192.168.5.7]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: no such identity: /var/www/haproxy-wi/app/Manager.pem: No such file or directory\\r\\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic,password).", "unreachable": true}', '', 'PLAY RECAP *********************************************************************', '192.168.5.7 : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0 ', '', "error: Can't install keepalived service

"] ['', 'PLAY [192.168.5.9] *************************************************************', '', 'TASK [Gathering Facts] *********************************************************', 'fatal: [192.168.5.9]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: no such identity: /var/www/haproxy-wi/app/Manager.pem: No such file or directory\\r\\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic,password).", "unreachable": true}', '', 'PLAY RECAP *********************************************************************', '192.168.5.9 : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0 ', '', "error: Can't install keepalived service

"]

**Comment by Aidaho12** [comment]
Do you use password for access to the servers? Maybe it's bug, I will check

**Comment by Aidaho12** [comment]
For me everything works ok...

Show me your ssh credentials page

**Comment by Aidaho12** [comment]
And done :)

**Comment by hpandroid** [comment]
Hi @Aidaho12 
is there any documentation for manual upgrade of the haproxy-wi?
Thank you,

**Comment by Aidaho12** [comment]
manual upgrade unfortunately does not exist

**Comment by hpandroid** [comment]
Hi @Aidaho12 
Thank you for the quick response. I am able to update to 3.9.2.
When I am accessing both servers from UI, I am having trouble to see the other servers HAPROXY status. It is showing stopped. But I am able to stats for both servers form either of the web UI by opening 8085 port. Do I have to open any other port to access the HAProxy status on the other server? 
Thank you.

**Comment by Aidaho12** [comment]
Have you read https://haproxy-wi.org/settings.py ? I'm speaking about 1999 port

**Comment by hpandroid** [comment]
Sorry I have not enabled socket port 1999. After enabling the port it is working file. NameError: name 'proxy_serv' is not defined, referer: https://192.168.5.7:8443/app/ha.py

**Comment by Aidaho12** [comment]
Show me full error log

**Comment by hpandroid** [comment]
> Have you read https://haproxy-wi.org/settings.py ? I'm speaking about 1999 port

Sorry I figured it out I forget to open the port. 


Here is the error log 

[Mon Dec 16 11:57:12.346219 2019] [cgi:error] [pid 4172] [client 192.168.5.27:57138] AH01215: Traceback (most recent call last):, referer: https://192.168.5.18:8443/app/ha.py
[Mon Dec 16 11:57:12.346367 2019] [cgi:error] [pid 4172] [client 192.168.5.27:57138] AH01215: File "/var/www/haproxy-wi/app/options.py", line 670, in <module>, referer: https://192.168.5.18:8443/app/ha.py
[Mon Dec 16 11:57:12.346512 2019] [cgi:error] [pid 4172] [client 192.168.5.27:57138] AH01215: " USER="+str(ssh_user_name)+" PASS="+str(ssh_user_password)+" KEY="+str(ssh_key_name) ], referer: https://192.168.5.18:8443/app/ha.py
[Mon Dec 16 11:57:12.346585 2019] [cgi:error] [pid 4172] [client 192.168.5.27:57138] AH01215: NameError: name 'proxy_serv' is not defined, referer: https://192.168.5.18:8443/app/ha.py
[Mon Dec 16 11:59:46.480358 2019] [cgi:error] [pid 12441] [client 192.168.5.27:57201] AH01215: Traceback (most recent call last):, referer: https://192.168.5.7:8443/app/hapservers.py?serv=192.168.5.9
[Mon Dec 16 11:59:46.480433 2019] [cgi:error] [pid 12441] [client 192.168.5.27:57201] AH01215: File "/var/www/haproxy-wi/app/options.py", line 777, in <module>, referer: https://192.168.5.7:8443/app/hapservers.py?serv=192.168.5.9
[Mon Dec 16 11:59:46.480469 2019] [cgi:error] [pid 12441] [client 192.168.5.27:57201] AH01215: metrics['chartData']['server'] = server, referer: https://192.168.5.7:8443/app/hapservers.py?serv=192.168.5.9
[Mon Dec 16 11:59:46.480501 2019] [cgi:error] [pid 12441] [client 192.168.5.27:57201] AH01215: NameError: name 'server' is not defined, referer: https://192.168.5.7:8443/app/hapservers.py?serv=192.168.5.9
[Mon Dec 16 12:07:38.323611 2019] [cgi:error] [pid 4170] [client 192.168.5.27:57343] AH01215: Traceback (most recent call last):, referer: https://192.168.5.7:8443/app/viewsttats.py?serv=192.168.5.7
[Mon Dec 16 12:07:38.323766 2019] [cgi:error] [pid 4170] [client 192.168.5.27:57343] AH01215: File "/var/www/haproxy-wi/app/options.py", line 327, in <module>, referer: https://192.168.5.7:8443/app/viewsttats.py?serv=192.168.5.7
[Mon Dec 16 12:07:38.323818 2019] [cgi:error] [pid 4170] [client 192.168.5.27:57343] AH01215: data = response.content, referer: https://192.168.5.7:8443/app/viewsttats.py?serv=192.168.5.7
[Mon Dec 16 12:07:38.323889 2019] [cgi:error] [pid 4170] [client 192.168.5.27:57343] AH01215: NameError: name 'response' is not defined, referer: https://192.168.5.7:8443/app/viewsttats.py?serv=192.168.5.7
[Mon Dec 16 12:08:10.281061 2019] [cgi:error] [pid 4172] [client 192.168.5.27:57353] AH01215: Traceback (most recent call last):, referer: https://192.168.5.7:8443/app/viewsttats.py?serv=192.168.5.9
[Mon Dec 16 12:08:10.281271 2019] [cgi:error] [pid 4172] [client 192.168.5.27:57353] AH01215: File "/var/www/haproxy-wi/app/options.py", line 327, in <module>, referer: https://192.168.5.7:8443/app/viewsttats.py?serv=192.168.5.9
[Mon Dec 16 12:08:10.281344 2019] [cgi:error] [pid 4172] [client 192.168.5.27:57353] AH01215: data = response.content, referer: https://192.168.5.7:8443/app/viewsttats.py?serv=192.168.5.9
[Mon Dec 16 12:08:10.281439 2019] [cgi:error] [pid 4172] [client 192.168.5.27:57353] AH01215: NameError: name 'response' is not defined, referer: https://192.168.5.7:8443/app/viewsttats.py?serv=192.168.5.9
[Mon Dec 16 12:08:17.793637 2019] [cgi:error] [pid 4169] [client 192.168.5.27:57358] AH01215: Traceback (most recent call last):, referer: https://192.168.5.7:8443/app/viewsttats.py?serv=192.168.5.7
[Mon Dec 16 12:08:17.793838 2019] [cgi:error] [pid 4169] [client 192.168.5.27:57358] AH01215: File "/var/www/haproxy-wi/app/options.py", line 327, in <module>, referer: https://192.168.5.7:8443/app/viewsttats.py?serv=192.168.5.7
[Mon Dec 16 12:08:17.793913 2019] [cgi:error] [pid 4169] [client 192.168.5.27:57358] AH01215: data = response.content, referer: https://192.168.5.7:8443/app/viewsttats.py?serv=192.168.5.7
[Mon Dec 16 12:08:17.794035 2019] [cgi:error] [pid 4169] [client 192.168.5.27:57358] AH01215: NameError: name 'response' is not defined, referer: https://192.168.5.7:8443/app/viewsttats.py?serv=192.168.5.7
[Mon Dec 16 12:56:20.902520 2019] [cgi:error] [pid 4170] [client 192.168.5.27:57962] AH01215: Traceback (most recent call last):, referer: https://192.168.5.18:8443/app/ha.py
[Mon Dec 16 12:56:20.902715 2019] [cgi:error] [pid 4170] [client 192.168.5.27:57962] AH01215: File "/var/www/haproxy-wi/app/options.py", line 670, in <module>, referer: https://192.168.5.18:8443/app/ha.py
[Mon Dec 16 12:56:20.902914 2019] [cgi:error] [pid 4170] [client 192.168.5.27:57962] AH01215: " USER="+str(ssh_user_name)+" PASS="+str(ssh_user_password)+" KEY="+str(ssh_key_name) ], referer: https://192.168.5.18:8443/app/ha.py
[Mon Dec 16 12:56:20.903015 2019] [cgi:error] [pid 4170] [client 192.168.5.27:57962] AH01215: NameError: name 'proxy_serv' is not defined, referer: https://192.168.5.18:8443/app/ha.py
[Mon Dec 16 12:59:48.987808 2019] [cgi:error] [pid 17643] [client 192.168.5.27:58035] AH01215: Traceback (most recent call last):, referer: https://192.168.5.7:8443/app/ha.py
[Mon Dec 16 12:59:48.987947 2019] [cgi:error] [pid 17643] [client 192.168.5.27:58035] AH01215: File "/var/www/haproxy-wi/app/options.py", line 670, in <module>, referer: https://192.168.5.7:8443/app/ha.py
[Mon Dec 16 12:59:48.988093 2019] [cgi:error] [pid 17643] [client 192.168.5.27:58035] AH01215: " USER="+str(ssh_user_name)+" PASS="+str(ssh_user_password)+" KEY="+str(ssh_key_name) ], referer: https://192.168.5.7:8443/app/ha.py
[Mon Dec 16 12:59:48.988166 2019] [cgi:error] [pid 17643] [client 192.168.5.27:58035] AH01215: NameError: name 'proxy_serv' is not defined, referer: https://192.168.5.7:8443/app/ha.py

**Comment by Aidaho12** [comment]
Hmm... interesting... check proxy in the settings, if there is everythink ok, then edit options.py:

```
proxy_serv = ''
```

Add it to 856 line

**Comment by Aidaho12** [comment]
One was fixed another broke ))

**Comment by hpandroid** [comment]
This line is 590.
proxy_serv = proxy if proxy is not None else ""

I have added this line after 666.
```
line 666:  os.system("cp scripts/%s ." % script)
line 667: proxy_serv = proxy if proxy is not None else ""
```

**Comment by Aidaho12** [comment]
And it's work now?

**Comment by hpandroid** [comment]
It did worked. It is creating new config in Keepalived. 

I have stopped the HAProxy in server but it not failing over Ha Proxy server 2.

**Comment by Aidaho12** [comment]
No, it's normal behavior. Master-Slave has sense only when you edit configs

**Comment by hpandroid** [comment]
HA Proxy 1: 192.168.5.7
HA Proxy 2: 192.168.5.9
Shared IP: 192.168.5.18
I have stopped HAproxy service in HA Proxy 1 and trying to browse it from the shared IP.
Now I am getting error saying connection "ERR_CONNECTION_REFUSED" which means client is still hitting HA Proxy 1 instead of failing over to  HA Proxy 2 to serve the clients.

**Comment by Aidaho12** [comment]
Slave wil became master if master keepalived will fail... You can use autostart to prevent failing master haproxy. Or write script for keepalived to stop master if master haproxy fault

**Comment by hpandroid** [comment]
Ok Thank you @Aidaho12  for your quick response. I will write a script to work with Fail over.
