### ISSUE TITLE
Error in installing HAPROXY from web interface

### ISSUE THREAD

**Issue by atefibra** [Aidaho12/haproxy-wi#192]
So after installing HAPROXY-wi manually following your commands, 
i tried to install Haproxy on my host, but i got this error !!!! 
![image](https://user-images.githubusercontent.com/35434021/71154405-bf880a00-223b-11ea-8eb0-0961c8b85ca8.png)

**Comment by Aidaho12** [comment]
Maybe it's a bug, I will check

**Comment by atefibra** [comment]
okay, i hope you find a way out 
i'll be waiting for your feedback

**Comment by Aidaho12** [comment]
Wich ansible version do you use?

**Comment by atefibra** [comment]
i have updated my ansible version and now i get this problem 
![image](https://user-images.githubusercontent.com/35434021/71241317-9df65380-230b-11ea-8bad-bd52555ea19e.png)

**Comment by Aidaho12** [comment]
I cannot see text now, show me text

**Comment by atefibra** [comment]
error: Unhandled error: Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/ansible/config/manager.py", line 554, in update_config_data value, origin = self.get_config_value_and_origin(config, configfile) File "/usr/lib/python2.7/site-packages/ansible/config/manager.py", line 498, in get_config_value_and_origin value = ensure_type(value, defs[config].get('type'), origin=origin) File "/usr/lib/python2.7/site-packages/ansible/config/manager.py", line 121, in ensure_type makedirs_safe(value, 0o700) File "/usr/lib/python2.7/site-packages/ansible/utils/path.py", line 90, in makedirs_safe raise AnsibleError("Unable to create local directories(%s): %s" % (to_native(rpath), to_native(e))) AnsibleError: Unable to create local directories(/usr/share/httpd/.ansible/tmp): [Errno 13] Permission denied: '/usr/share/httpd/.ansible' Traceback (most recent call last): File "/usr/bin/ansible-playbook", line 62, in import ansible.constants as C File "/usr/lib/python2.7/site-packages/ansible/constants.py", line 174, in config = ConfigManager() File "/usr/lib/python2.7/site-packages/ansible/config/manager.py", line 290, in __init__ self.update_config_data() File "/usr/lib/python2.7/site-packages/ansible/config/manager.py", line 566, in update_config_data raise AnsibleError("Invalid settings supplied for %s: %s\n" % (config, to_native(e)), orig_exc=e) ansible.errors.AnsibleError: Invalid settings supplied for DEFAULT_LOCAL_TMP: Unable to create local directories(/usr/share/httpd/.ansible/tmp): [Errno 13] Permission denied: '/usr/share/httpd/.ansible'

**Comment by Aidaho12** [comment]
Create folder usr/share/httpd/.ansible with apache owner

**Comment by atefibra** [comment]
after creating the folder with apache owner i got this one 
*********************************************************', '', 'TASK [Gathering Facts] *********************************************************', 'fatal: [192.168.153.192]: UNREACHABLE! => {"changed": false, "msg": "Invalid/incorrect password: Failed to add the host to the list of known hosts (/usr/share/httpd/.ssh/known_hosts).\\r\\nPermission denied, please try again.", "unreachable": true}', '', 'PLAY RECAP *********************************************************************', '192.168.153.192 : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0 ', '', "error: Can't install Haproxy service

**Comment by Aidaho12** [comment]
Create the folder /usr/share/httpd/.ssh

**Comment by atefibra** [comment]
thank you so much for your help ! 
it all comes down to this one 

['', 'PLAY [192.168.153.192] *********************************************************', '', 'TASK [Gathering Facts] *********************************************************', 'fatal: [192.168.153.192]: UNREACHABLE! => {"changed": false, "msg": "Invalid/incorrect password: Permission denied, please try again.", "unreachable": true}', '', 'PLAY RECAP *********************************************************************', '192.168.153.192 : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0 ', '', "error: Can't install Haproxy service
and thank you !

**Comment by Aidaho12** [comment]
Here I think pretty obviously problem

**Comment by atefibra** [comment]
it looks so obvious but its not ! 
i dont know why it shows this error ! 
( btw when i added the server, ive done it using password and not ssh key )

**Comment by Aidaho12** [comment]
On the overview pages shows everything ok?

**Comment by atefibra** [comment]
its like this ! 
![image](https://user-images.githubusercontent.com/35434021/71360577-a6ab8b80-2590-11ea-9fa3-e0817bb86dca.png)

**Comment by Aidaho12** [comment]
It's seems like everything is ok, for me it's works fine... I cannot say anything use your logs

**Comment by atefibra** [comment]
when you add a server you use ssh credentials or password ?

**Comment by Aidaho12** [comment]
Both

**Comment by atefibra** [comment]
Thank you i have fixed to error with ssh key !
