### ISSUE TITLE
WAF installation problems 

### ISSUE THREAD

**Issue by atefibra** [Aidaho12/haproxy-wi#193]
when i try to install waf it stays like this : 
![image](https://user-images.githubusercontent.com/35434021/71478525-75c99180-27f0-11ea-8d5d-abf172e4ac1d.png)

when i try to install waf.sh manually it says : 
" error: Need HAProxy version 1.8 or later <a title="Close" id="errorMess"><b>X</b></a> "

**Comment by Aidaho12** [comment]
Can you write messages with full description.... I think you know my next question.... Which version haproxy do you use?

**Comment by atefibra** [comment]
Haproxy version :  
HA-Proxy version 2.0.11 2019/12/11 - https://haproxy.org/
( ive installed this one via web interface using ansible ) 
also the installation of HA have been successfully done
but waf wont install

**Comment by atefibra** [comment]
Haproxy version :
HA-Proxy version 2.0.11 2019/12/11 - https://haproxy.org/
( ive installed this one via web interface using ansible )
also the installation of KeepAlived have been successfully done
but waf wont install :/

**Comment by Aidaho12** [comment]
Go to the server where you try install to the /tmp and run:
```
./waf.sh VERSION=2.0.11 HAPROXY_PATH=/etc/haproxy/
```

**Comment by atefibra** [comment]
You're the GOAT bro ! 
![image](https://user-images.githubusercontent.com/35434021/71511758-bf1eed00-2893-11ea-99c0-45e58faa79b2.png)
but why from the overview page i cant see WAF is activated !!! 
![image](https://user-images.githubusercontent.com/35434021/71511787-d65dda80-2893-11ea-84e1-56b538f53bfe.png)

**Comment by Aidaho12** [comment]
It's because of you run installation manually and there aren't needs records in DB. You have to create property records like this:
```
sqlite> insert into waf values('server_id','0');
```

**Comment by atefibra** [comment]
its so weirdo !
[root@mastserv app]# sqlite3
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> insert into waf values('mastserv','0');
Error: no such table: waf
sqlite>

**Comment by atefibra** [comment]
after executing your command, Metrics master and Metrics workers sometimes in Red sometimes in Green !!! 
and no WAF apperance in overview as you can see in the picture :( 
![image](https://user-images.githubusercontent.com/35434021/71513456-b4b42180-289a-11ea-8d49-f372f9277a03.png)

**Comment by Aidaho12** [comment]
You have to always look logs before something write, I have no idea what there happens. Also show results after your actions it's a good idea :)

**Comment by atefibra** [comment]
Thanks for your comprehension,
this is the metrics-log : 
![image](https://user-images.githubusercontent.com/35434021/71521579-a3cad680-28c1-11ea-888b-76b9246fa270.png)

i dont know how to get the WAF errors or why he didnt show up in the overview page.

**Comment by Aidaho12** [comment]
First of all show me what exactly you added in the db

**Comment by atefibra** [comment]
Sorry for the late, 
this is what ive addded : 
sqlite> insert into waf values('masterServer','0');

**Comment by atefibra** [comment]
Sorry for the late,
$ cd /var/www/haproxy-wi/app
then : sqlite3 haproxy-wi.db
then : 
sqlite> insert into waf values('masterServer','0');

**Comment by Aidaho12** [comment]
I sad the server's id, not name... It's must be 1and 2 for example

**Comment by atefibra** [comment]
Done <3
