### ISSUE TITLE
problems after update

### ISSUE THREAD

**Issue by atefibra** [Aidaho12/haproxy-wi#196]
i've installe haproxy-wi on a new machine and this happened ! 
i cant log in 
![image](https://user-images.githubusercontent.com/35434021/71620017-b4cc5e00-2bc7-11ea-8e4a-5a753478afb3.png)

**Comment by Aidaho12** [comment]
Ok, let's start again..... before you will write something you must(!) look through logs. If there is something you have to show it me, if there isn't you have to say that logs are empty...

It's neccessery so that I have ablity give you advice I'm not telepat!
