### ISSUE TITLE
The "Show" command output information in the "Runtime API" section is not displayed

### ISSUE THREAD

**Issue by verdel** [Aidaho12/haproxy-wi#198]
The Runtime API section does not display the output of any Show command (info, stat, backend) executed over SSH.
<img width="1279" alt="Снимок экрана 2020-01-08 в 20 19 15" src="https://user-images.githubusercontent.com/869777/72000368-33726c80-3254-11ea-9f1c-db01cf984451.png">

**Comment by Aidaho12** [comment]
Thank you! )
