### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by sbhnet** [Aidaho12/haproxy-wi#203]
centos 7 run httpd
[root@ haproxy-wi]# journalctl -xe
Jan 20 14:09:52 192-168-40-107 keep_alive[5088]: Traceback (most recent call last):
Jan 20 14:09:52 192-168-40-107 keep_alive[5088]: File "/var/www/haproxy-wi/app/tools/keep_alive.py", line 53, in <module>
Jan 20 14:09:52 192-168-40-107 keep_alive[5088]: main()
Jan 20 14:09:52 192-168-40-107 keep_alive[5088]: File "/var/www/haproxy-wi/app/tools/keep_alive.py", line 29, in main
Jan 20 14:09:52 192-168-40-107 keep_alive[5088]: for serv in servers:
Jan 20 14:09:52 192-168-40-107 keep_alive[5088]: TypeError: 'NoneType' object is not iterable
Jan 20 14:09:52 192-168-40-107 systemd[1]: keep_alive.service: main process exited, code=exited, status=1/FAILURE
Jan 20 14:09:52 192-168-40-107 systemd[1]: Unit keep_alive.service entered failed state.
Jan 20 14:09:52 192-168-40-107 systemd[1]: keep_alive.service failed.
Jan 20 14:09:52 192-168-40-107 metrics[5087]: Content-type: text/html
Jan 20 14:09:52 192-168-40-107 metrics[5087]: <span class="alert alert-danger" style="height: 20px;margin-bottom: 20px;" id="error">An error occurred: no suc
Jan 20 14:09:52 192-168-40-107 metrics[5087]: Content-type: text/html
Jan 20 14:09:52 192-168-40-107 metrics[5087]: <span class="alert alert-danger" style="height: 20px;margin-bottom: 20px;" id="error">An error occurred: no suc
Jan 20 14:09:52 192-168-40-107 metrics[5087]: Content-type: text/html
Jan 20 14:09:52 192-168-40-107 metrics[5087]: <span class="alert alert-danger" style="height: 20px;margin-bottom: 20px;" id="error">An error occurred: no suc
Jan 20 14:09:52 192-168-40-107 metrics[5087]: Content-type: text/html
Jan 20 14:09:52 192-168-40-107 metrics[5087]: <span class="alert alert-danger" style="height: 20px;margin-bottom: 20px;" id="error">An error occurred: no suc
Jan 20 14:09:52 192-168-40-107 metrics[5087]: Content-type: text/html
Jan 20 14:09:52 192-168-40-107 metrics[5087]: <span class="alert alert-danger" style="height: 20px;margin-bottom: 20px;" id="error">An error occurred: no suc
Jan 20 14:09:52 192-168-40-107 metrics[5087]: Traceback (most recent call last):
Jan 20 14:09:52 192-168-40-107 metrics[5087]: File "/var/www/haproxy-wi/app/tools/metrics_master.py", line 116, in <module>
Jan 20 14:09:52 192-168-40-107 metrics[5087]: main()
Jan 20 14:09:52 192-168-40-107 metrics[5087]: File "/var/www/haproxy-wi/app/tools/metrics_master.py", line 28, in main
Jan 20 14:09:52 192-168-40-107 metrics[5087]: for serv in servers:
Jan 20 14:09:52 192-168-40-107 metrics[5087]: TypeError: 'NoneType' object is not iterable
Jan 20 14:09:52 192-168-40-107 checker[5089]: Content-type: text/html
Jan 20 14:09:52 192-168-40-107 checker[5089]: <span class="alert alert-danger" style="height: 20px;margin-bottom: 20px;" id="error">An error occurred: no suc
Jan 20 14:09:52 192-168-40-107 checker[5089]: Content-type: text/html
Jan 20 14:09:52 192-168-40-107 checker[5089]: <span class="alert alert-danger" style="height: 20px;margin-bottom: 20px;" id="error">An error occurred: no suc
Jan 20 14:09:52 192-168-40-107 checker[5089]: Content-type: text/html
Jan 20 14:09:52 192-168-40-107 checker[5089]: <span class="alert alert-danger" style="height: 20px;margin-bottom: 20px;" id="error">An error occurred: no suc
Jan 20 14:09:52 192-168-40-107 checker[5089]: Traceback (most recent call last):
Jan 20 14:09:52 192-168-40-107 checker[5089]: File "/var/www/haproxy-wi/app/tools/checker_master.py", line 72, in <module>
Jan 20 14:09:52 192-168-40-107 checker[5089]: main()
Jan 20 14:09:52 192-168-40-107 checker[5089]: File "/var/www/haproxy-wi/app/tools/checker_master.py", line 26, in main
Jan 20 14:09:52 192-168-40-107 checker[5089]: for serv in servers:
Jan 20 14:09:52 192-168-40-107 checker[5089]: TypeError: 'NoneType' object is not iterable
Jan 20 14:09:52 192-168-40-107 systemd[1]: metrics_haproxy.service: main process exited, code=exited, status=1/FAILURE
Jan 20 14:09:52 192-168-40-107 systemd[1]: Unit metrics_haproxy.service entered failed state.
Jan 20 14:09:52 192-168-40-107 systemd[1]: metrics_haproxy.service failed.
Jan 20 14:09:52 192-168-40-107 systemd[1]: checker_haproxy.service: main process exited, code=exited, status=1/FAILURE
Jan 20 14:09:52 192-168-40-107 systemd[1]: Unit checker_haproxy.service entered failed state.
Jan 20 14:09:52 192-168-40-107 systemd[1]: checker_haproxy.service failed.
[root@192-168-40-107 haproxy-wi]# journalctl -xe
Jan 20 14:10:12 192-168-40-107 checker[5222]: Content-type: text/html
Jan 20 14:10:12 192-168-40-107 checker[5222]: <span class="alert alert-danger" style="height: 20px;margin-bottom: 20px;" id="error">An error occurred: no suc
Jan 20 14:10:12 192-168-40-107 checker[5222]: Content-type: text/html
Jan 20 14:10:12 192-168-40-107 checker[5222]: <span class="alert alert-danger" style="height: 20px;margin-bottom: 20px;" id="error">An error occurred: no suc
Jan 20 14:10:12 192-168-40-107 checker[5222]: Traceback (most recent call last):
Jan 20 14:10:12 192-168-40-107 checker[5222]: File "/var/www/haproxy-wi/app/tools/checker_master.py", line 72, in <module>
Jan 20 14:10:12 192-168-40-107 checker[5222]: main()
Jan 20 14:10:12 192-168-40-107 checker[5222]: File "/var/www/haproxy-wi/app/tools/checker_master.py", line 26, in main
Jan 20 14:10:12 192-168-40-107 checker[5222]: for serv in servers:
Jan 20 14:10:12 192-168-40-107 checker[5222]: TypeError: 'NoneType' object is not iterable
Jan 20 14:10:12 192-168-40-107 systemd[1]: checker_haproxy.service: main process exited, code=exited, status=1/FAILURE
Jan 20 14:10:12 192-168-40-107 systemd[1]: Unit checker_haproxy.service entered failed state.
Jan 20 14:10:12 192-168-40-107 systemd[1]: checker_haproxy.service failed.
Jan 20 14:10:14 192-168-40-107 systemd[1]: keep_alive.service holdoff time over, scheduling restart.
Jan 20 14:10:14 192-168-40-107 systemd[1]: metrics_haproxy.service holdoff time over, scheduling restart.
Jan 20 14:10:14 192-168-40-107 systemd[1]: Started Haproxy metrics.

**Comment by Aidaho12** [comment]
First of all: hi

Show me your servers and which version of HAProxy-WI do you use?

**Comment by sbhnet** [comment]
ubuntu 16.04 & github the lastest version

**Comment by Aidaho12** [comment]
I meant the page servers
