### ISSUE TITLE
Cannot update version Content-type: text/html An error occurred: attempt to write a readonly database X Content-type: text/html An error occurred: attempt to write a readonly database X

### ISSUE THREAD

**Issue by sbhnet** [Aidaho12/haproxy-wi#204]
env：

ubuntu 16.04
apache2
libapache2-mod-wsgi-py3

Cannot update version Content-type: text/html An error occurred: attempt to write a readonly database X Content-type: text/html An error occurred: attempt to write a readonly database X

**Comment by Aidaho12** [comment]
No, thanks
