### ISSUE TITLE
v3.12.2.1 - Create new HA cluster broken

### ISSUE THREAD

**Issue by zx2slow** [Aidaho12/haproxy-wi#207]
CentOS 7 system - web interface shows error upon attempting to create keepalived HA

`
error: ./install_keepalived.sh: line 27: /var/www/haproxy-wi/app/scripts/ansible//192.168.0.4: Permission denied ./install_keepalived.sh: line 30: ansible-playbook: command not found error: ./install_keepalived.sh: line 27: /var/www/haproxy-wi/app/scripts/ansible//192.168.0.6: Permission denied ./install_keepalived.sh: line 30: ansible-playbook: command not found`

/var/www/haproxy-wi/app/scripts/ansible/install_keepalived.sh  owner/group is apache and script is executable.

`[root@proxy scripts]# pwd
/var/www/haproxy-wi/app/scripts

[root@proxy scripts]# ls -la install_keepalived.sh
-rwxrwxrwx. 1 apache apache 1365 Jan 29 12:50 install_keepalived.sh
`

**Comment by Aidaho12** [comment]
Install ansible please

**Comment by zx2slow** [comment]
Installed ansible and created /usr/share/httpd/.ansible with apache ownership/group.

New error:

`error: ./install_keepalived.sh: line 27: /var/www/haproxy-wi/app/scripts/ansible//192.168.0.4: Permission denied [WARNING]: Unable to parse /var/www/haproxy-wi/app/scripts/ansible/192.168.0.4 as an inventory source [WARNING]: No inventory was parsed, only implicit localhost is available [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all' [WARNING]: Could not match supplied host pattern, ignoring: 192.168.0.4 error: ./install_keepalived.sh: line 27: /var/www/haproxy-wi/app/scripts/ansible//192.168.0.6: Permission denied [WARNING]: Unable to parse /var/www/haproxy-wi/app/scripts/ansible/192.168.0.6 as an inventory source [WARNING]: No inventory was parsed, only implicit localhost is available [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all' [WARNING]: Could not match supplied host pattern, ignoring: 192.168.0.6


192.168.0.6`

**Comment by Aidaho12** [comment]
check all folders owner

**Comment by zx2slow** [comment]
Thank you, owner/group changed to apache for :
 /var/www/haproxy-wi/app/scripts/ansible
/var/www/haproxy-wi/app/scripts/ansible/roles

**Comment by Aidaho12** [comment]
Yes, it means auto start, not keepalived service
