### ISSUE TITLE
AH01215: (13)Permission denied: exec of '/var/www/haproxy-wi/app/overview.py' failed, referer: https

### ISSUE THREAD

**Issue by powerman2003** [Aidaho12/haproxy-wi#210]
Hello! Install haproxywi on cenos 7
Try to open web ui and have error
[Sun Feb 02 23:40:03.520780 2020] [cgi:error] [pid 3771] [client 10.100.0.252:53710] AH01215: (13)Permission denied: exec of '/var/www/haproxy-wi/app/overview.py' failed, referer: https://10.100.1.27/
[Sun Feb 02 23:40:03.521213 2020] [cgi:error] [pid 3771] [client 10.100.0.252:53710] End of script output before headers: overview.py, referer: https://10.100.1.27/

On web internal error 500

**Comment by Aidaho12** [comment]
Hi

Did you disable selinux?

**Comment by powerman2003** [comment]
No. Disable, and now work fine!
but have other problems.
When i try install haproxy, have error

error: [WARNING]: Unable to set correct type for configuration entry: DEFAULT_LOCAL_TMP ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path. The error appears to have been in '/var/www/haproxy-wi/app/scripts/ansible/roles/haproxy/tasks/main.yml': line 2, column 3, but may be elsewhere in the file depending on the exact syntax problem. The offending line appears to be: --- - name: check if HAProxy is installed ^ here The error appears to have been in '/var/www/haproxy-wi/app/scripts/ansible/roles/haproxy/tasks/main.yml': line 2, column 3, but may be elsewhere in the file depending on the exact syntax problem. The offending line appears to be: --- - name: check if HAProxy is installed ^ here exception type: exception: no action detected in task. This often indicates a misspelled module name, or incorrect module path. The error appears to have been in '/var/www/haproxy-wi/app/scripts/ansible/roles/haproxy/tasks/main.yml': line 2, column 3, but may be elsewhere in the file depending on the exact syntax problem. The offending line appears to be: --- - name: check if HAProxy is installed ^ here

**Comment by Aidaho12** [comment]
Update ansible to the last version

**Comment by powerman2003** [comment]
Update ansible via pip3
get 777 permission to /usr/share/httpd/.ansible

Now Error

['', 'PLAY [10.100.1.27] *************************************************************', '', 'TASK [Gathering Facts] *********************************************************', 'ok: [10.100.1.27]', '', 'TASK [haproxy : check if HAProxy is installed] *********************************', 'ok: [10.100.1.27]', '', 'TASK [haproxy : populate service facts] ****************************************', 'ok: [10.100.1.27]', '', 'TASK [haproxy : install EPEL Repository] ***************************************', 'changed: [10.100.1.27]', '', 'TASK [haproxy : install HAProxy 2.0.12-1 on EL7] *******************************', 'ok: [10.100.1.27]', '', 'TASK [haproxy : set_fact from wi`] *********************************************', 'ok: [10.100.1.27]', '', 'TASK [haproxy : install the latest version of HAProxy] *************************', 'ok: [10.100.1.27]', '', 'TASK [haproxy : Change wrong HAProxy service file] *****************************', 'ok: [10.100.1.27]', '', 'TASK [haproxy : Enable and start service HAProxy] ******************************', 'fatal: [10.100.1.27]: FAILED! => {"changed": false, "msg": "Unable to start service haproxy: Job for haproxy.service failed because the control process exited with error code. See \\"systemctl status haproxy.service\\" and \\"journalctl -xe\\" for details.\\n"}', '...ignoring', '', 'PLAY RECAP *********************************************************************', '10.100.1.27 : ok=9 changed=1 unreachable=0 failed=0 skipped=1 rescued=0 ignored=1 ', '']

**Comment by powerman2003** [comment]
Fix it! Thank's for help!

**Comment by Aidaho12** [comment]
How you fixed it?

**Comment by powerman2003** [comment]
grand permission to ./ansible folder and grand permission to  /var/www/haproxy-wi/app/tools/*.py 
Now, i take 777 permission. and change owner to apache:apache
