### ISSUE TITLE
SELinux support 

### ISSUE THREAD

**Issue by akram** [Aidaho12/haproxy-wi#212]
Hi @Aidaho12 , great job and thanks for sharing.

Is there any chance that we see  haproxy-wi intended to work with SELinux ?

**Comment by Aidaho12** [comment]
Hi, thank you)

I think about it lately, but there are few problems, maybe later, when I will have a free time

**Comment by Aidaho12** [comment]
I wanted to include it in 4.0 release, but selinux blokcs run sh scripts. Maybe you know selinux well?)

**Comment by Aidaho12** [comment]
Hi,

https://haproxy-wi.org/installation.py#selinux
