### ISSUE TITLE
ModuleNotFoundError: No module named 'funct'

### ISSUE THREAD

**Issue by BrixSat** [Aidaho12/haproxy-wi#214]
[root@master www]#  /var/www/haproxy-wi/app/tools/checker_master.py
Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/tools/checker_master.py", line 8, in <module>
    import funct
ModuleNotFoundError: No module named 'funct'

**Comment by Aidaho12** [comment]
So what?

**Comment by joeymk2000** [comment]
Hi, I'm having the same issue on Ubuntu 18.04. When I go to the Haproxy-WI I get an internal server error, and this is what the apache log says: 

> Traceback (most recent call last):
>   File "/var/www/haproxy-wi/app/login.py", line 6, in <module>
>     import funct
> ModuleNotFoundError: No module named 'funct'

Usually when I see this error it's easy to fix with pip3 install <modulename> but this module doesn't seem to exist when I try to install it.

**Comment by Aidaho12** [comment]
Hi
Yes, it's local module. Check funct.py if exists
