### ISSUE TITLE
4.0.0 install error

### ISSUE THREAD

**Issue by w6m6** [Aidaho12/haproxy-wi#215]
Hi, in CentOS, when trying to install haproxy to server, we got a error message from ansible. 
Any advices? thx a lot.

['', 'PLAY [172.20.228.199] **********************************************************', '', 'TASK [Gathering Facts] *********************************************************', 'fatal: [172.20.228.199]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "failed": true, "module_stderr": "Shared connection to 172.20.228.199 closed.\\r\\n", "module_stdout": "/usr/bin/python: can\'t open file \'/home/nfs/mchen/.ansible/tmp/ansible-tmp-1583488064.21-261115983648788/AnsiballZ_setup.py\': [Errno 13] Permission denied\\r\\n", "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error", "rc": 2}}, "msg": "The following modules failed to execute: setup\\n"}', '', 'PLAY RECAP

**Comment by Aidaho12** [comment]
Hi

Do you use user with sudo?

**Comment by w6m6** [comment]
yes, we setup a sudo user in credentials.

**Comment by Aidaho12** [comment]
It was clear os where you have installed HAProxy-WI? Why ansible tryes to use home dir?

**Comment by Aidaho12** [comment]
Ok, it's normal behavior... but something wrong with permissions

**Comment by w6m6** [comment]
Yep, in the target server(199), I just copied AnsiballZ_setup.py, and rerun the script , and no permission denied error was thrown. :(

**Comment by Aidaho12** [comment]
It's strange

Did you install haproxy?

**Comment by w6m6** [comment]
In 199? no,  it's a complete clear OS.

**Comment by Aidaho12** [comment]
I mean: have you installed successful haproxy Via HAProxy-WI?

**Comment by w6m6** [comment]
Not yet. still trying to figure out the root cause of "Permission denied".

**Comment by Aidaho12** [comment]
Try to use root user
