### ISSUE TITLE
Bad layout in haproxy overview page

### ISSUE THREAD

**Issue by lgrawet** [Aidaho12/haproxy-wi#216]
Hi,

Here is a screenshot that shows the problem :

![image](https://user-images.githubusercontent.com/10059091/76099441-696d6c00-5fcb-11ea-9126-c27613801008.png)

Thanks!

**Comment by Aidaho12** [comment]
Hi

Which version do you use?

**Comment by lgrawet** [comment]
4.0.0.0.
Pull from a few hours ago.

**Comment by lgrawet** [comment]
I think problem comes from the too long "Version" field. It is a Debian backport package.
A solution would be to add room for one more line dedicated to uptime.

**Comment by Aidaho12** [comment]
Yes, maybe... I will check it soon. Thank you for report

**Comment by lgrawet** [comment]
Another thing which isn't working is the radio buttons. Nothing happens when I click on them and settings aren't retained on page reload, unlike in you demo!

**Comment by Aidaho12** [comment]
I guess there is problem with javascript, try to open javascript console and refresh page

**Comment by lgrawet** [comment]
Here is the output:
```
script.js:209 Uncaught ReferenceError: showMetrics is not defined
    at startSetInterval (script.js:209)
    at HTMLDocument.<anonymous> (script.js:508)
    at fire (jquery-1.12.4.js:3232)
    at Object.fireWith [as resolveWith] (jquery-1.12.4.js:3362)
    at Function.ready (jquery-1.12.4.js:3582)
    at HTMLDocument.completed (jquery-1.12.4.js:3617)
startSetInterval @ script.js:209
(anonymous) @ script.js:508
fire @ jquery-1.12.4.js:3232
fireWith @ jquery-1.12.4.js:3362
ready @ jquery-1.12.4.js:3582
completed @ jquery-1.12.4.js:3617
```

**Comment by Aidaho12** [comment]
It's ok... Can you show me HTML code of the checkboxes?

**Comment by lgrawet** [comment]
![image](https://user-images.githubusercontent.com/10059091/76111023-d7bc2980-5fdf-11ea-8718-8032f1ad8a8e.png)

**Comment by Aidaho12** [comment]
It looks fine too... Can you provide me access to this server?

**Comment by lgrawet** [comment]
Not like this because the server is on private network inside our datacenter.
I also have the following warning 
```
fontawesome.min.js:5 [Violation] 'setTimeout' handler took 72ms
```

**Comment by Aidaho12** [comment]
It's ok too

Then check jQuery is ok or not and try reload checkbox widget

**Comment by lgrawet** [comment]
Hi, I've deleted browser cache and cookie and javascript works now.

**Comment by Aidaho12** [comment]
Awesome!)

**Comment by lgrawet** [comment]
Please note the main layout problem is still there.

**Comment by Aidaho12** [comment]
Can you show me it

**Comment by lgrawet** [comment]
See the first post for screenshot.
Here is a quick fix (increased width)
I've also tested line break after process number and increased height, it depends what you prefer.

**Comment by Aidaho12** [comment]
Can you show without modification?

**Comment by Aidaho12** [comment]
Ok. I understood problem. Thank you )
