### ISSUE TITLE
keepalived config: server list is empty

### ISSUE THREAD

**Issue by lgrawet** [Aidaho12/haproxy-wi#219]
Hi,

Server list is empty in keepalived config page.
I had to comment out line 31 in config.py to fix the issue (by comparison to versions.py)

```
if service == 'keepalived':
        title = "Working with Keepalived configs"
        action = "config.py?service=keepalived"
        configs_dir = funct.get_config_var('configs', 'kp_save_configs_dir')
        format = 'conf'
        #servers = sql.get_dick_permit(keepalived=1)
elif service == 'nginx':
```

**Comment by Aidaho12** [comment]
Hi

Have you updated from 3 to 4 version?

**Comment by lgrawet** [comment]
Yes, I was thinking about some missing attribute.

**Comment by Aidaho12** [comment]
There are.... Run keepalived installation on servers where keepalived are installed and attributes will added into db

**Comment by lgrawet** [comment]
It is ok now, thanks.
But this line is missing from versions.py then ?

**Comment by Aidaho12** [comment]
Hmmm... I don't remember my thoughts, but I think it should be there)

**Comment by Aidaho12** [comment]
And I have fixed it
