### ISSUE TITLE
haproxy installation hard coded to port 22.

### ISSUE THREAD

**Issue by thaylin** [Aidaho12/haproxy-wi#220]
I created a server in wi and specified port 1024. I went to install haproxy and it tells me that it cannot connect over port 22.  I have checked all the configs that I can see and nothing seems to override this.

![haproxy-port22install](https://user-images.githubusercontent.com/1175353/76688530-ef109d80-6603-11ea-8912-e012da42b8d2.png)
![haproxy-server](https://user-images.githubusercontent.com/1175353/76688536-f637ab80-6603-11ea-9158-9f51e02c606f.png)

**Comment by Aidaho12** [comment]
Thank you, I will fix it

**Comment by Aidaho12** [comment]
Done, Update please

**Comment by thaylin** [comment]
When will you be making the new versions available on the yum repo?

**Comment by Aidaho12** [comment]
It will be on 17.03

**Comment by Aidaho12** [comment]
There is a new version
