### ISSUE TITLE
Issue in config with happroxy-wi 

### ISSUE THREAD

**Issue by shreyanshu7101904** [Aidaho12/haproxy-wi#228]
i followed this [link](https://haproxy-wi.org/installation.py) for installation on my ubuntu 18. but after login, on this url /app/overview.py getting html as `Atata!` with no html page kindly check this attached image ![Screenshot](https://drive.google.com/file/d/1I4JW8RJsHFJcLYHIUN1nHIwzT73hU5gO/view)

**Comment by Aidaho12** [comment]
Check logs
