### ISSUE TITLE
Lesencrypt support?

### ISSUE THREAD

**Issue by blackyzero** [Aidaho12/haproxy-wi#229]
Hello,

Would it be nice to add support for Letenscrypt?
Thanks a lot for great project.

**Comment by Aidaho12** [comment]
Hi, and thanks

There are a lot of problems with integration let's encrypte :(

**Comment by blackyzero** [comment]
i see. Hope it would be supported soon :)
Thanks again.

**Comment by Aidaho12** [comment]
I don't know, maybe not

**Comment by Aidaho12** [comment]
Well... it happened! https://haproxy-wi.org/changelog.py#4_5
