### ISSUE TITLE
When I add a user it disappears right after

### ISSUE THREAD

**Issue by mageru** [Aidaho12/haproxy-wi#23]
I just installed the current version (10:00 am 7/25/2018) and every time I add a user and credential it disappears when I refresh the page. 

This is preventing me from being able to add a server (can't add tie to a credential, they disappear). 

tail config_edit-20180725.log
Jul 25 14:31:05 from 10.51.52.19 user: admin users.py#ssh upload new ssh cert /var/www/haproxy-wi/keys/root.pem for: local
Jul 25 14:33:33 from 10.51.52.19 user: admin users.py#ssh upload new ssh cert /var/www/haproxy-wi/keys/root-ssh.pem for: local

I have made a commitment to the Patreon page as well, this is an awesome project.

**Comment by Aidaho12** [comment]
Thank you. How i can have access to your server with HAProxy-WI?


>Среда, 25 июля 2018, 20:58 +06:00 от Justin Miller <notifications@github.com>:
>
>I just installed the current version (10:00 am 7/25/2018) and every time I add a user and credential it disappears when I refresh the page.
>This is preventing me from being able to add a server (can't add tie to a credential, they disappear).
>tail config_edit-20180725.log
>Jul 25 14:31:05 from 10.51.52.19 user: admin users.py#ssh upload new ssh cert /var/www/haproxy-wi/keys/root.pem for: local
>Jul 25 14:33:33 from 10.51.52.19 user: admin users.py#ssh upload new ssh cert /var/www/haproxy-wi/keys/root-ssh.pem for: local
>I have made a commitment to the Patreon page as well, this is an awesome project.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Павел.

**Comment by mageru** [comment]
We can do a quick screen share on here if you want to take a look. It is a corporate server that I cannot expose to the internet or give direct SSH access to, but if you can take a look over screen share that would be helpful 
https://cotiviti.zoom.us/my/jumiller

**Comment by Aidaho12** [comment]
Ok, Let's start


>Среда, 25 июля 2018, 21:03 +06:00 от Justin Miller <notifications@github.com>:
>
>We can do a quick screen share on here if you want to take a look. It is a corporate server that I cannot expose to the internet or give direct SSH access to, but if you can take a look over screen share that would be helpful
>https://cotiviti.zoom.us/my/jumiller
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Павел.

**Comment by mageru** [comment]
Great and fast help, thank you!

**Comment by Aidaho12** [comment]
You left so quickly and I did not have time to say: there will be some questions, problems or something else, welcome)
