### ISSUE TITLE
login refreshes with an error on the page

### ISSUE THREAD

**Issue by Chaffy-0** [Aidaho12/haproxy-wi#230]
Going through the manual install on Ubuntu 18.04.  When I try to login the page just refreshes and this message shows on the page. 

Cannot update version An error occurred: attempt to write a readonly database X

**Comment by Aidaho12** [comment]
Check permission for db

**Comment by Chaffy-0** [comment]
🤦‍♂️ It was set to root instead of www-data.  It takes the default creds now and I'm taking to overview.py but it's a blank page.  Forgive me if these are simple questions, I'm still a noob when it comes to linux.  Neither mysql nor sqlite was installed prior to running the create_db script.  Does that make a difference?  During my troubleshooting of the original login issue I had installed both of them.  Would that have ill effect on it?

**Comment by Aidaho12** [comment]
Show me haproxy-wi.error.log in /var/www/httpd

**Comment by Chaffy-0** [comment]
Does it matter that the log file was in /var/log/hhtpd?  I'm not concerned about the ssl errors unless you think it's causing an issue with the invalid character errors.  

[haproxy-wi.error.log](https://github.com/Aidaho12/haproxy-wi/files/4746241/haproxy-wi.error.log)

**Comment by Aidaho12** [comment]
It looks like something with DB, try deleting and re-create db again

**Comment by Chaffy-0** [comment]
I deleted haproxy-wi.db from /var/www/haproxy-wi/app and reran create_db.py.  It completed successfully but I had to update the db permissions for www-data.  Still a blank page.  

I really appreciate you helping me out with this!!

**Comment by Aidaho12** [comment]
BTW, have you disabled selinux?

**Comment by Chaffy-0** [comment]
It wasn't installed.  Just for giggles I installed it and disabled it but no dice.  Should msql or sqlite and selinux be added to the manual installation section of the install doc?  https://haproxy-wi.org/installation.py

**Comment by Aidaho12** [comment]
Selinux it's a part of the core, check enabled it or not.

What do you mean about adding in the manual?

**Comment by Chaffy-0** [comment]
I was referring to the manual installation steps on haproxy-wi.org.  I read that instead of selinux, Ubuntu 18 has apparmor.  Both are disabled right now.  

I was following the manual steps starting with the "Or if you use Debian/Ubuntu:" section after cloning to /var/www/.

**Comment by Aidaho12** [comment]
I see. Something with db, tomorrow I will update the part which shows error log. You should update it and try again

**Comment by Chaffy-0** [comment]
Will do.  I'm all for starting over if I need to.

**Comment by Aidaho12** [comment]
I think will be easier for you just change on string in app/funct.py. Find please:
```
def out_error(e)
```
and chnage from:
```
	print('<span class="alert alert-danger" style="height: 20px;margin-bottom: 20px;" id="error">An error occurred: ' + error + ' <a title="Close" id="errorMess"><b>X</b></a></span>')
```
to
```
print(error)
```
Try login again and check logs

**Comment by Chaffy-0** [comment]
I started from scratch again and now I'm up and running.  I think I missed a few permissions, swapping some of the httpd to apache2 paths, and the apache to www-data user.  Thank you again for your help!!

**Comment by Aidaho12** [comment]
You are welcome. I'm glad 😊

Do you want to have access to rpm repositories?

**Comment by Chaffy-0** [comment]
Maybe...  I wanted to get this spun up so my boss and I can play around with it.  We run 7 different pair of load balancers so having a central location to manage them all is a huge plus.  I'll def keep it in mind.

**Comment by Aidaho12** [comment]
I've sent it you

**Comment by Chaffy-0** [comment]
Thank you!!
