### ISSUE TITLE
HAProxy statistics  does not work

### ISSUE THREAD

**Issue by gorkovv** [Aidaho12/haproxy-wi#231]
![Снимок экрана от 2020-06-30 14-26-09](https://user-images.githubusercontent.com/7299332/86096625-b676d000-badd-11ea-8c2a-2fb1cb410c65.png)
Haroxy-wi version v4.3.2.0
Куда копать?

**Comment by Aidaho12** [comment]
Have you configured stat page properly?
https://haproxy-wi.org/settings.py#haproxy_config

**Comment by gorkovv** [comment]
Sorry. Not carefully read. Did according to the instructions - **it all worked**. -)
