### ISSUE TITLE
Does not save config to server

### ISSUE THREAD

**Issue by gorkovv** [Aidaho12/haproxy-wi#232]
<Working with HAProxy configs>
The config reads from the server but does not save the config to the server
None of the 3 buttons (<Jast save>, <Save an restart>, <Save and reload> ) work.
Haproxy-wi goes into a pensive state
Version v4.3.2.0

**Comment by Aidaho12** [comment]
Check HAProxy-WI logs and httpd error logs

**Comment by gorkovv** [comment]
![Снимок экрана от 2020-06-30 20-23-11](https://user-images.githubusercontent.com/7299332/86131899-6d8c3f00-bb10-11ea-8224-9ea42e369597.png)

**Comment by Aidaho12** [comment]
Strange address in the end of the sting

**Comment by gorkovv** [comment]
The problem is not solved. Everything works - statistics, map, etc... But the most important thing for which everything was started - editing configs - does not work.
Here is the **haproxy-wi** log
![Снимок экрана от 2020-07-03 09-44-01](https://user-images.githubusercontent.com/7299332/86426489-0c33be00-bd12-11ea-9dff-aa23262e54c8.png)
And here is the log on the **haproxy** side
The session opens but does **not close**.

июл 03 09:34:06 acs-haproxy2 sshd[18126]: Accepted password for asutp from 10.74.36.12 port 42162 ssh2
июл 03 09:34:06 acs-haproxy2 sshd[18126]: pam_unix(sshd:session): session opened for user asutp by (uid=0)
июл 03 09:34:06 acs-haproxy2 systemd-logind[782]: New session 90 of user asutp.
июл 03 09:34:06 acs-haproxy2 systemd[1]: Started Session 90 of user asutp.

**Comment by Aidaho12** [comment]
Try understand why timeout happens

**Comment by gorkovv** [comment]
Oh, I didn’t want to go into your source. -( Well, ok, I'll go dig.

**Comment by Aidaho12** [comment]
Maybe there isn't need permission. Is the user has sudo?

**Comment by gorkovv** [comment]
To **funct.py** file
To function **ssh_command**
Added debug line
  ```
  logging('localhost','ssh.exec_command:' + command, haproxy=1)
  stdin, stdout, stderr = ssh.exec_command(command, get_pty=True)
```
and a hundred I see?

Jul 03 13:52:48ssh.exec_command: sudo haproxy -q -c -f /tmp//2020-07-03.13:52:47.cfg&& sudo mv -f /tmp//2020-07-03.13:52:47.cfg /etc/haproxy/haproxy.cfg from 

Of course, nothing will work!

**Comment by Aidaho12** [comment]
Does it work now?

**Comment by gorkovv** [comment]
1. Need to remove the extra slash - '\\'
2. The sudo command requires a password - need to pass it additionally.
3. if haproxy is running on ubuntu (in my case) you need to replace everything 
sudo systemctl reload haproxy -> sudo service haproxy reload

I'll do it after the weekend

**Comment by Aidaho12** [comment]
Just create sudo user without password...

And Ubuntu has systemd too, if it not very old one of course

**Comment by gorkovv** [comment]
> Just create sudo user without password...

My colleagues will tell me - are you a fool? -)
 
> And Ubuntu has systemd too, if it not very old one of course

That yes. You can leave it that way.

**Comment by Aidaho12** [comment]
Why fool? How are you want to use password in not interactive program? Send it via echo? 

I mean not user without password, I mean sudo without password

**Comment by gorkovv** [comment]
1. It's a decrease in security anyway.
2. This will have to insist on all haproxy servers. And maintain it in the future.
3. It is absolutely easy to write two lines of code and pass the password.
I already checked it out. -)

**Comment by Aidaho12** [comment]
If you will use a ssh key, should you enter password too?

**Comment by gorkovv** [comment]
That's why he's ssh key so he won't ask for the password.
But my haproxy-wi ssh key authorization didn't work either. Although it's okay to log on from the terminal.
