### ISSUE TITLE
Atata! 

### ISSUE THREAD

**Issue by gorkovv** [Aidaho12/haproxy-wi#233]
![Снимок экрана от 2020-06-30 16-07-43](https://user-images.githubusercontent.com/7299332/86107379-efb63c80-baeb-11ea-94dc-baab5b1b25cd.png)
Создал нового админа и зашёл под ним. Появилось это.
Что делать с этим? Что не так? На какую кнопку нажать дальше?

**Comment by Aidaho12** [comment]
Группа у админа назначена?

**Comment by gorkovv** [comment]
Конечно! Причем мне и не нужно было заводить нового юзера, но в какие-то моменты лазанья по разделам меню и тыканья кнопок вылазит предупреждение что ничего делать не буду пока у тебя стоит группп ALL. Какой-то такой смысл.-) 
Не могу понять закономерность когда вылазит это Атата! Потому что вот перелогинился вроде работает. Потом перелогинися под админом вроде работает тоже. Но потом раз и уже словил двойное Атата! Атата! -)

**Comment by Aidaho12** [comment]
Атата работает, когда группа юзера не совпадает с текущей группой, возможно что-то с куками

**Comment by Aidaho12** [comment]
И предупреждение будет выскакивать, если будет группа all, нужно читать то что пишет, особенно то что пишет красным, чаще всего это что-то важное

**Comment by gorkovv** [comment]
А зачем собственно это ограничение? Я хочу зайти под админом и рулить всеми серверами без заморочек. Или я чего-то недопонял.

**Comment by Aidaho12** [comment]
Рули, только через админ ареа, этот раздел больше для едиторов, и для пользователей не с алл группой

**Comment by gorkovv** [comment]
![Снимок экрана от 2020-07-03 09-15-06](https://user-images.githubusercontent.com/7299332/86425028-48651f80-bd0e-11ea-8721-033eb0a93836.png)
Вот я не могу понять физический смысл, что не так. Я залогинен по admin/admin. 
Причем если ткнуть в Admin area  - Servers, там всё доступно для редактирования.

**Comment by Aidaho12** [comment]
Проблема в группах, тут ты не можешь группы редактировать

**Comment by gorkovv** [comment]
Нет мне не понять этого.-( 
Во-первых я админ. Почему мне нельзя чего-то? Хоть группы хоть подруппы.-)
Во-вторых какие группы? На этой странице я вижу Сервер. Какие-то свойства этого конкретного сервера. Кнопку Check...
Никаких здесь групп.

**Comment by Aidaho12** [comment]
В этом и суть: никаких здесь групп.

Хочешь редактировать именно там? поставь себе группу не алл и редактируй
