### ISSUE TITLE
use mysql

### ISSUE THREAD

**Issue by udee297** [Aidaho12/haproxy-wi#234]
hi,
i change mysql section on config to enable = 1 
i run create_db.py but it give me error
so i remove all tables and re instert db from haproxy-wi.db.sql and its run without error
but when i open the web i got atata!
its working fine if i change sql enable to 0 again..
is there any proper way to move sqlite to mysql ?

**Comment by Aidaho12** [comment]
Hi

Is there something in the logs?

**Comment by udee297** [comment]
this it the logs
Tue Jul 21 03:43:46.991022 2020] [cgi:error] [pid 23913] [client 103.119.62.126:10915] AH01215:     token = token), referer: https://202.3.166.81:20080/
[Tue Jul 21 03:43:46.991177 2020] [cgi:error] [pid 23913] [client 103.119.62.126:10915] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render, referer: https://202.3.166.81:20080/
[Tue Jul 21 03:43:46.991248 2020] [cgi:error] [pid 23913] [client 103.119.62.126:10915] AH01215:     self.environment.handle_exception(), referer: https://202.3.166.81:20080/
[Tue Jul 21 03:43:46.991429 2020] [cgi:error] [pid 23913] [client 103.119.62.126:10915] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception, referer: https://202.3.166.81:20080/
[Tue Jul 21 03:43:46.991527 2020] [cgi:error] [pid 23913] [client 103.119.62.126:10915] AH01215:     reraise(*rewrite_traceback_stack(source=source)), referer: https://202.3.166.81:20080/
[Tue Jul 21 03:43:46.991663 2020] [cgi:error] [pid 23913] [client 103.119.62.126:10915] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise, referer: https://202.3.166.81:20080/
[Tue Jul 21 03:43:46.991726 2020] [cgi:error] [pid 23913] [client 103.119.62.126:10915] AH01215:     raise value.with_traceback(tb), referer: https://202.3.166.81:20080/
[Tue Jul 21 03:43:46.991834 2020] [cgi:error] [pid 23913] [client 103.119.62.126:10915] AH01215:   File "templates/ovw.html", line 1, in top-level template code, referer: https://202.3.166.81:20080/
[Tue Jul 21 03:43:46.991889 2020] [cgi:error] [pid 23913] [client 103.119.62.126:10915] AH01215:     {% extends "base.html" %}, referer: https://202.3.166.81:20080/
[Tue Jul 21 03:43:46.992002 2020] [cgi:error] [pid 23913] [client 103.119.62.126:10915] AH01215:   File "templates/base.html", line 225, in top-level template code, referer: https://202.3.166.81:20080/
[Tue Jul 21 03:43:46.992069 2020] [cgi:error] [pid 23913] [client 103.119.62.126:10915] AH01215:     {% block content %}{% endblock %}, referer: https://202.3.166.81:20080/
[Tue Jul 21 03:43:46.992222 2020] [cgi:error] [pid 23913] [client 103.119.62.126:10915] AH01215:   File "templates/ovw.html", line 11, in block "content", referer: https://202.3.166.81:20080/
[Tue Jul 21 03:43:46.992306 2020] [cgi:error] [pid 23913] [client 103.119.62.126:10915] AH01215:     {% for s in servers %}, referer: https://202.3.166.81:20080/
[Tue Jul 21 03:43:46.992391 2020] [cgi:error] [pid 23913] [client 103.119.62.126:10915] AH01215: TypeError: 'NoneType' object is not iterable, referer: https://202.3.166.81:20080/

**Comment by Aidaho12** [comment]
have you run create_db.py after run haproxy-wi.db.sql?

**Comment by udee297** [comment]
yes i got this when running create_db.py
./create_db.py 
<div class="alert alert-danger">
An error occurred: 2014 (HY000): Commands out of sync; you can't run this command now
</div>
Updating... go to version 3.2
Updating... go to version 3.12.0.0
Updating... go to version 3.12.1.0
An error occurred: 1060 (42S21): Duplicate column name 'keepalived'
Updating... one more for version 4.0.0
An error occurred: 1060 (42S21): Duplicate column name 'nginx'
An error occurred: 1060 (42S21): Duplicate column name 'haproxy'
An error occurred: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'OR IGNORE into user_groups(user_id, user_group_id) select id, groups from user' at line 1
An error occurred: 1060 (42S21): Duplicate column name 'pos'
An error occurred: 1062 (23000): Duplicate entry 'ldap_type' for key 'param'

**Comment by udee297** [comment]
ah its because user_groups table is empty

**Comment by Aidaho12** [comment]
Yes, I wanted ask you run this command:
```insert OR IGNORE into user_groups(user_id, user_group_id) select user.id, user.groups from user;```
