### ISSUE TITLE
ssh ports other than 22

### ISSUE THREAD

**Issue by udee297** [Aidaho12/haproxy-wi#235]
hi,

i add server with ssh port other than 22 and its working fine when using check credentials
but i cant connect when i tried to install nginx and haproxy because its using default ssh port 22
'fatal: [192.168.100.21]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.100.21 port 22: Connection timed out", "unreachable": true}', '', 'PLAY RECAP

**Comment by Aidaho12** [comment]
Ou, thank you. I will fix it with the next release

**Comment by udee297** [comment]
@Aidaho12 how to manually install haproxy on the server?

**Comment by Aidaho12** [comment]
yum install haproxy

**Comment by Aidaho12** [comment]
BTW, it should work:

```'fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 127.0.0.1 port 26: Connection refused", "unreachable": true}',```

Did you have this row:

```'TASK [haproxy : Set SSH port] **************************************************', 'ok: [127.0.0.1]', '', 'TASK [haproxy : check if HAProxy is installed] *********************************', ```
?

**Comment by udee297** [comment]
TASK [haproxy : Set SSH port] **************************************************', 'ok: [127.0.0.1]', '', 'TASK [haproxy : check if HAProxy is installed] *********************************',

where is that row?

**Comment by Aidaho12** [comment]
It should be in output when you try install haproxy or nginx

**Comment by udee297** [comment]
i dont see that.. let me try install another..
current server installed manually already

**Comment by Aidaho12** [comment]
Previous installation doesn't depends on it
