### ISSUE TITLE
Problem adding SSH creds

### ISSUE THREAD

**Issue by henrygodwin** [Aidaho12/haproxy-wi#237]
Hello,

I've just installed HAProxyWi for the first time on Ubuntu server (Bionic Beaver) and I've run into a slight issue.

Using chrome Version 81.0.4044.92 (Official Build) (64-bit) and navigating to the app/users.py#ssh page to add some new SSH credentials. The following error appears in the console and I can't seem to add any credentials, nothing happens when clicking the tick button. 

![error](https://user-images.githubusercontent.com/129558/89310387-86869380-d66c-11ea-8447-2d22e45c0558.PNG)

**Comment by Aidaho12** [comment]
Hello

Interesting, I will check it

**Comment by henrygodwin** [comment]
Thanks - HAProxyWi version is showing as 4.4.1.0

**Comment by Aidaho12** [comment]
I've fixed it, update please
