### ISSUE TITLE
fresh install blank pages in admin area and logs not working

### ISSUE THREAD

**Issue by edwardbattye** [Aidaho12/haproxy-wi#238]
Hi Fresh install on ubuntu 18.04LTS, most pages in the admin area are blank. Users,Groups,Servers,SSH credentials,Settings,Services and update are all blank. 
Interal logs page loads but doesn't show the contents of the logs despite them having contents. I have attached log. 
[log.txt](https://github.com/Aidaho12/haproxy-wi/files/5027823/log.txt)
v4.4.1.0

**Comment by wannabeciso** [comment]
Same thing happening for me, just installed it - admin area basically useless because nothing loads. Though tit was my mistake, reset the machine and manually installed again - again only blank pages...

**Comment by Aidaho12** [comment]
Oh... sorry

I've fixed it, update please
