### ISSUE TITLE
python-passlib not found when installing NGINX

### ISSUE THREAD

**Issue by eisengrau** [Aidaho12/haproxy-wi#240]
Hello,

I was able to install haproxy with anslible on a remote server, however nginx failes, due to a missing python-passlib package. I have checked and installed python3-passlib manually (both haproxy-wi and remote machine is centos 8) but still does not work.

Is the dependency in the ansible rolebook is missing "3" for the packagename, or there are other issues?

**Comment by Aidaho12** [comment]
Hello

I think this problem because of el8 and there isn't python-passlib, only 3

Try editing the playbook and add 3. I will fix it

**Comment by eisengrau** [comment]
Oh, ok cool. Same thing with libselinux when I want to install haproxy exporter.

**Comment by Aidaho12** [comment]
Is it help?

**Comment by eisengrau** [comment]
Yes, that did the trick, thank you!

**Comment by Aidaho12** [comment]
Cool! What name for libselinux on el8?

**Comment by eisengrau** [comment]
It is python3-libselinux

Looks like python3-* is a standardised name now.

**Comment by Aidaho12** [comment]
Looks like

Thank you!

**Comment by Aidaho12** [comment]
I've fixed it
