### ISSUE TITLE
Permission denied overview.py

### ISSUE THREAD

**Issue by k0st1kLOL** [Aidaho12/haproxy-wi#243]
Добрый чистая ручная установка, CentOS8. 
в конфиге апача юзер/группа apache
ошибка 500 с пожарником и вот такая ошибка в логах: 
[Fri Sep 04 03:35:44.533359 2020] [cgid:error] [pid 3548:tid 139997915100928] [client 192.168.0.2:2781] AH01241: error spawning CGI child: exec of '/var/www/haproxy-wi/app/overview.py' failed (): /var/www/haproxy-wi/app/overview.py, referer: https://193.125.0.6/app/overview.py
[Fri Sep 04 03:35:44.533926 2020] [cgid:error] [pid 3548:tid 139997915100928] [client 192.168.0.2:2781] End of script output before headers: overview.py, referer: https://192.168.0.3/app/overview.py

-rwxr-xr-x. 1 apache apache   4445 Sep  4 03:01 overview.py

**Comment by Aidaho12** [comment]
Hi

Have you disabled SELinux?

**Comment by k0st1kLOL** [comment]
[Fri Sep 04 05:03:30.207343 2020] [cgid:error] [pid 1657:tid 140256888207104] [client 192.168.0.2:60073] Traceback (most recent call last):: /var/www/haproxy-wi/app/overview.py, referer: https://192.168.0.3/
[Fri Sep 04 05:03:30.207430 2020] [cgid:error] [pid 1657:tid 140256888207104] [client 192.168.0.2:60073]   File "/var/www/haproxy-wi/app/overview.py", line 7, in <module>: /var/www/haproxy-wi/app/overview.py, referer: https://192.168.0.3/
нужно было перезапустить систему)
Теперь вылезло:
[Fri Sep 04 05:03:30.207476 2020] [cgid:error] [pid 1657:tid 140256888207104] [client 192.168.0.2:60073]     from jinja2 import Environment, FileSystemLoader: /var/www/haproxy-wi/app/overview.py, referer: https://192.168.0.3/
[Fri Sep 04 05:03:30.207515 2020] [cgid:error] [pid 1657:tid 140256888207104] [client 192.168.0.2:60073] ModuleNotFoundError: No module named 'jinja2': /var/www/haproxy-wi/app/overview.py, referer: https://192.168.0.3/
[Fri Sep 04 05:03:30.217145 2020] [cgid:error] [pid 1657:tid 140256888207104] [client 192.168.0.2:60073] End of script output before headers: overview.py, referer: https://192.168.0.3/

делаю
 pip3 install jinja2 --user
получаю. 
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Requirement already satisfied: jinja2 in /root/.local/lib/python3.6/site-packages
Requirement already satisfied: MarkupSafe>=0.23 in /root/.local/lib/python3.6/site-packages (from jinja2)

**Comment by Aidaho12** [comment]
попробуйте сделать запустить python3 и посмотреть какую версию он показывает

**Comment by k0st1kLOL** [comment]
[root@haproxy-wi httpd]# python3
Python 3.6.8 (default, Apr 16 2020, 01:36:27)
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.

**Comment by Aidaho12** [comment]
хм... иногда такое случается, что питон не видит свои модули, но в чем проблема так и не разобрались, мне ее не удалось воспроизвести, видимо какие-то кастомные образа

**Comment by k0st1kLOL** [comment]
Да вот в том то и дело что с официального сайта, yum update сделал предварительно. Ошибок установки не было. Но есть одно НО, не использовал sudo, учетку простую не создавал, то есть в системе только одна учетная запись root. Это может быть проблемой?

**Comment by Aidaho12** [comment]
нет, не должно... хотя вот что странно: 
```
Requirement already satisfied: jinja2 in /root/.local/lib/python3.6/site-packages
```
обычно питон не хранит свои пакеты в папках пользователя... они должны быть глобально установлены в /usr/share чото там

попробуйте установить пакеты без --user

**Comment by k0st1kLOL** [comment]
Successfully uninstalled Jinja2-2.11.2
[root@haproxy-wi httpd]# pip3 install jinja2
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting jinja2
  Using cached https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl
Requirement already satisfied: MarkupSafe>=0.23 in /root/.local/lib/python3.6/site-packages (from jinja2)
Installing collected packages: jinja2
Successfully installed jinja2-2.11.2

Удалил и поставил и по умолчанию он запихнул все в папку /root/

**Comment by Aidaho12** [comment]
казлина... ну надо гуглить почему он так делает

**Comment by k0st1kLOL** [comment]
Видимо наличие в системе только root накладывает отпечаток 
сначала удалил pip3 uninstall jinja2
а затем уже поставитл из реп 
 yum install python3-jinja2
открылась страница мастера)

**Comment by Aidaho12** [comment]
видимо )

в инструкции вроде jinja2 из репозитория ставится...

**Comment by k0st1kLOL** [comment]
все просто для 7 centOS есть пункт про установку этого пакета, для 8 нет. поэтому он и был пропущен, но поставился согласно файлу зависимостей в root'а. Спасибо за продукт) будем курить мануалы по настройке.

**Comment by Aidaho12** [comment]
Надо будет добавить тогда

Пожалуйста, надеюсь понравится :)

**Comment by k0st1kLOL** [comment]
Добавьте в мануал для centos 

 /etc/selinux/config
SELINUX=disabled
чтобы точно не пропустили

**Comment by Aidaho12** [comment]
там есть ниже пункт про selinux, что его надо отключать при ручной установке
