### ISSUE TITLE
Config test fails when specifying cert folder

### ISSUE THREAD

**Issue by prowebuk** [Aidaho12/haproxy-wi#244]
Thanks for the nice gui

when specifying certs from a config folder rather than inline, the config test fails in WI but not in HAProxy:

bind 0.0.0.0:443 ssl crt /etc/ssl/haproxy_certs/

[ALERT] 254/095343 (9925) : parsing [/tmp//2020-09-11.08:53:43.cfg:79] : 'bind 0.0.0.0:443' : Didn't find any certificate for bundle '/etc/ssl/haproxy_certs/'. [ALERT] 254/095343 (9925) : Error(s) found in configuration file : /tmp//2020-09-11.08:53:43.cfg [ALERT] 254/095343 (9925) : Fatal errors found in configuration. None

haproxy -c -V -f /etc/haproxy/haproxy.cfg
Configuration file is valid

**Comment by Aidaho12** [comment]
Thank you :)

Hm... try check in this way:
```
su - haproxy-wi_user
sudo haproxy -q -c -f /etc/haproxy/haproxy.cfg
```

**Comment by prowebuk** [comment]
Hi,

This is running on Debian under apache2 as www-data and the following is ok

su - www-data -s /bin/bash -c  "/usr/sbin/haproxy -c -f /etc/haproxy/haproxy.cfg"
Configuration file is valid

**Comment by Aidaho12** [comment]
Hm...

Interesting... I supposed that the haproxy-wi user doesn't have necessary permissions for opening certs file, but it seems like it isn't

**Comment by prowebuk** [comment]
If you can tell me which file shells out haproxy, I'll do some digging

**Comment by Aidaho12** [comment]
sorry, but what do you mean " file shells out haproxy"?

**Comment by prowebuk** [comment]
Sorry, which python file executes /usr/sbin/haproxy to test the tmp file?

**Comment by Aidaho12** [comment]
funct.py executives bash command, which I send it above.  пятница, 11 сентября 2020г., 20:39 +06:00 от prowebuk  notifications@github.com :
