### ISSUE TITLE
Instruction reference missing directory

### ISSUE THREAD

**Issue by deweys** [Aidaho12/haproxy-wi#245]
On line 44 of the manual install instructions (https://haproxy-wi.org/installation.py#manual) it references a folder that doesn't exist.

44 $ sudo cp **haproxy-wi/config_other/systemd/*** /etc/systemd/system/

I assume this is the directory that provides the services later referenced like metrics_haproxy.service and keep_alive.service?

Any assistance would be appreciated!

**Comment by Aidaho12** [comment]
Yes, it was for services which provide now by RPM.

I will fix it, thank you :)

**Comment by deweys** [comment]
Thank you! I'm trying to get a functional demo for my team before we seek approval for a purchase.

**Comment by Aidaho12** [comment]
I can provide trial access to the rpm if you are interested

**Comment by deweys** [comment]
That would be great! I sent you an email last week asking if that might be possible.

**Comment by Aidaho12** [comment]
Sorry, I have not received it... Can you send me again on aidaho@haproxy-wi.org? понедельник, 21 сентября 2020г., 23:40 +06:00 от deweys  notifications@github.com :

**Comment by deweys** [comment]
Email resent, thank you!
