### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by krakazyabra** [Aidaho12/haproxy-wi#247]
При попытке открыть страницы /app/hapservers.py в консоли возникает ошибка `favicon.ico not found`. Сама страница не загружается.

**Comment by Aidaho12** [comment]
А в логах впача есть что-нибудь?

**Comment by krakazyabra** [comment]
Проверял, тишина.

**Comment by Aidaho12** [comment]
Тогда сложно что-то сказать... Должно работать...
