### ISSUE TITLE
Folder "tools" missing under app?

### ISSUE THREAD

**Issue by achtnullzwei** [Aidaho12/haproxy-wi#248]
Hi,

wanted to install manually from scratch, but I get some errors starting httpd. Seems like the folder "tools" under app is missing. It tries to call e.g. tools/keep_alive.py but the files are not there in the master branch. 

Not sure if I am doing something wrong but in earlier tags the folder was present. Now it is gone, and httpd cannot be started.

Thx.

**Comment by Aidaho12** [comment]
Tools has been deleted... what error does httpd show?

**Comment by achtnullzwei** [comment]
atm I am getting sth like this:
./run: line 5: /var/www/haproxy-wi/app/tools/checker_master.py: No such file or directory

I will create a new VM and test again. I scripted the installation a bit. Maybe my script is faulty. I will go through it step by step instead of the script and check if i still get this error.

**Comment by Aidaho12** [comment]
Yes, miss steps which are associated with tools folders.


Tools provides via rpm now

**Comment by achtnullzwei** [comment]
Still same result. But i think i understand now why it happens.

Just to be precise, i tried to do a manual installation, without rpm, according to the guide "manual installation" on the website. As you were saying, that tools are only coming via rpm, that means that a manual install without registration for rpm is not working any longer. 

Or is there a "switch" to turn off the tools during manual installation? Cannot find something specific in the manual installation guide referring to this.

**Comment by Aidaho12** [comment]
Hm... It's pretty strange. Tools shouldn't influence on httpd

**Comment by achtnullzwei** [comment]
You are right. My bad. I was checking the wrong log entries. I redirected stuff to console and just was looking at the wrong line. The log entries from above are from haproxy-wi, just mentioning that those files are not there. Seems it works just fine.

Thx anyay for your help. Great project 👍 :-)

**Comment by Aidaho12** [comment]
I'm glad that it nice for you 😊
