### ISSUE TITLE
master or 4.4.1.0 version doesn't load correctly in docker. 

### ISSUE THREAD

**Issue by bayeslearner** [Aidaho12/haproxy-wi#249]
It displays briefly a blue background and then redirects to 
"Not Found
The requested URL /app/overview.py was not found on this server."

**Comment by Aidaho12** [comment]
Try using the latest tag, it works fine

**Comment by bayeslearner** [comment]
I think the issue I encountered is with docker.  
I always thought when I declare a bind-mount in docker or docker-compose, I would be able to persist that mount.  So I did this: 

- ./haproxy-wi:  <path to the app folder> 

Strangely, what happens is that somehow it just shadows the app folder with an empty dir.

**Comment by Aidaho12** [comment]
Probably your folder "./haproxy-wi" is empty
