### ISSUE TITLE
你好，可否做个中文版本

### ISSUE THREAD

**Issue by 37705109** [Aidaho12/haproxy-wi#250]
你好，可否做个中文版本?

**Comment by Aidaho12** [comment]
你好。 原则上有可能有赞助商

**Comment by 37705109** [comment]
可以使用支付宝吗，我想买一个版本试试，如果能出中文版更好

**Comment by Aidaho12** [comment]
不，只有PayPal或patreon。 没有中文版 четверг, 29 октября 2020г., 16:02 +06:00 от 37705109  notifications@github.com :
