### ISSUE TITLE
servers --> servers click the page blank

### ISSUE THREAD

**Issue by sivanXu001** [Aidaho12/haproxy-wi#251]
Some functions are limited after deployment on your own virtual machine, could you please help to answer this question? Thank you very much. My operating system is centos7.7

Fri Oct 30 15:29:02.551541 2020] [cgi:error] [pid 10833] [client 10.122.107.250:61419] AH01215: Traceback (most recent call last):
[Fri Oct 30 15:29:02.551674 2020] [cgi:error] [pid 10833] [client 10.122.107.250:61419] AH01215:   File "/var/www/haproxy-wi/app/servers.py", line 39, in <module>
[Fri Oct 30 15:29:02.551711 2020] [cgi:error] [pid 10833] [client 10.122.107.250:61419] AH01215:     ldap_enable = ldap_enable)
[Fri Oct 30 15:29:02.551802 2020] [cgi:error] [pid 10833] [client 10.122.107.250:61419] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 989, in render
[Fri Oct 30 15:29:02.551869 2020] [cgi:error] [pid 10833] [client 10.122.107.250:61419] AH01215:     return self.environment.handle_exception(exc_info, True)
[Fri Oct 30 15:29:02.551968 2020] [cgi:error] [pid 10833] [client 10.122.107.250:61419] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 754, in handle_exception
[Fri Oct 30 15:29:02.552013 2020] [cgi:error] [pid 10833] [client 10.122.107.250:61419] AH01215:     reraise(exc_type, exc_value, tb)
[Fri Oct 30 15:29:02.552129 2020] [cgi:error] [pid 10833] [client 10.122.107.250:61419] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, inreraise
[Fri Oct 30 15:29:02.552178 2020] [cgi:error] [pid 10833] [client 10.122.107.250:61419] AH01215:     raise value.with_traceback(tb)
[Fri Oct 30 15:29:02.552263 2020] [cgi:error] [pid 10833] [client 10.122.107.250:61419] AH01215:   File "templates/include/admin_settings.html", line 18, in template
[Fri Oct 30 15:29:02.552319 2020] [cgi:error] [pid 10833] [client 10.122.107.250:61419] AH01215:     {% set section.section = set.2 %}
[Fri Oct 30 15:29:02.552432 2020] [cgi:error] [pid 10833] [client 10.122.107.250:61419] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 986, in render

**Comment by Aidaho12** [comment]
Hi,

Try to change in users.py the next row:
```
execpt:
     pass
```
to next one:
```
except Exception as e:
	print(str(e))
	pass
```

And check logs again after it

**Comment by sivanXu001** [comment]
I visited https://100.77.16.4/app/users.py#users , the log is as follows, please give some comments, thank you!



[Fri Oct 30 16:46:56.073581 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215: Traceback (most recent call last):
[Fri Oct 30 16:46:56.073699 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/var/www/haproxy-wi/app/users.py", line 78, in <module>
[Fri Oct 30 16:46:56.073740 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     ldap_enable=ldap_enable)
[Fri Oct 30 16:46:56.073855 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 989, in render
[Fri Oct 30 16:46:56.073942 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     return self.environment.handle_exception(exc_info, True)
[Fri Oct 30 16:46:56.074073 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 754, in handle_exception
[Fri Oct 30 16:46:56.074146 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     reraise(exc_type, exc_value, tb)
[Fri Oct 30 16:46:56.074247 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, inreraise
[Fri Oct 30 16:46:56.074307 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     raise value.with_traceback(tb)
[Fri Oct 30 16:46:56.074397 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "templates/include/admin_settings.html", line 18, in template
[Fri Oct 30 16:46:56.074456 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     {% set section.section = set.2 %}
[Fri Oct 30 16:46:56.074561 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 986, in render
[Fri Oct 30 16:46:56.074647 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     return concat(self.root_render_func(self.new_context(vars)))
[Fri Oct 30 16:46:56.074736 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "templates/admin.html", line 1, in top-level template code
[Fri Oct 30 16:46:56.074790 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     {% extends "base.html" %}
[Fri Oct 30 16:46:56.074877 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "templates/base.html", line 232, in top-level template code
[Fri Oct 30 16:46:56.074938 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     {% block content %}{% endblock %}
[Fri Oct 30 16:46:56.075031 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "templates/admin.html", line 180, in block "content"
[Fri Oct 30 16:46:56.075104 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     {% include 'include/admin_settings.html' %}
[Fri Oct 30 16:46:56.075224 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 754, in handle_exception
[Fri Oct 30 16:46:56.075286 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     reraise(exc_type, exc_value, tb)
[Fri Oct 30 16:46:56.075387 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, inreraise
[Fri Oct 30 16:46:56.075447 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     raise value.with_traceback(tb)
[Fri Oct 30 16:46:56.075537 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "templates/include/admin_settings.html", line 18, in template
[Fri Oct 30 16:46:56.075599 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     {% set section.section = set.2 %}
[Fri Oct 30 16:46:56.075702 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 470, in _parse
[Fri Oct 30 16:46:56.075795 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     return Parser(self, source, name, encode_filename(filename)).parse()
[Fri Oct 30 16:46:56.075895 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 897, inparse
[Fri Oct 30 16:46:56.075976 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     result = nodes.Template(self.subparse(), lineno=1)
[Fri Oct 30 16:46:56.076088 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 879, insubparse
[Fri Oct 30 16:46:56.076157 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     rv = self.parse_statement()
[Fri Oct 30 16:46:56.076264 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 121, inparse_statement
[Fri Oct 30 16:46:56.076351 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     return getattr(self, 'parse_' + self.stream.current.value)()
[Fri Oct 30 16:46:56.076454 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 189, inparse_for
[Fri Oct 30 16:46:56.076538 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     body = self.parse_statements(('name:endfor', 'name:else'))
[Fri Oct 30 16:46:56.076649 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 156, inparse_statements
[Fri Oct 30 16:46:56.076712 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     result = self.subparse(end_tokens)
[Fri Oct 30 16:46:56.076815 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 879, insubparse
[Fri Oct 30 16:46:56.076871 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     rv = self.parse_statement()
[Fri Oct 30 16:46:56.076981 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 121, inparse_statement
[Fri Oct 30 16:46:56.077073 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     return getattr(self, 'parse_' + self.stream.current.value)()
[Fri Oct 30 16:46:56.077189 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 175, inparse_set
[Fri Oct 30 16:46:56.077237 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     drop_needle=True)
[Fri Oct 30 16:46:56.077347 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/parser.py", line 155, inparse_statements
[Fri Oct 30 16:46:56.077408 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     self.stream.expect('block_end')
[Fri Oct 30 16:46:56.077504 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:   File "/usr/lib/python3.6/site-packages/jinja2/lexer.py", line 374, in expect
[Fri Oct 30 16:46:56.077559 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215:     self.name, self.filename)
[Fri Oct 30 16:46:56.077669 2020] [cgi:error] [pid 16415] [client 10.122.107.250:56745] AH01215: jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got '.'

**Comment by Aidaho12** [comment]
are your installation was without errors? I mean pip3 install and create_db.py

**Comment by sivanXu001** [comment]
As expected, it is the problem of installation package. Thank you very much for your support. This is absolutely a perfect project. I like it.

**Comment by Aidaho12** [comment]
Thank you :)
