### ISSUE TITLE
Metrics doesn't work

### ISSUE THREAD

**Issue by ascige** [Aidaho12/haproxy-wi#253]
Hi Aidaho12!
Thanks for you job! I've installed HaProxy-wi 4.5.2 on my CentOS 8. Every is working but when I try to show metrics of my servers, I don't see anything. I see that in "HAProxy Overview, I see my server but I don't understand what is the way to configure alarms, metrics and auto-start. I read that I must modify the configuration of every single HaProxy with the instruction on the site and install also socat. I made every operation but I don't why these check (alerts, metrics, ecc) are disabled.
Can you have any suggest? If you need some configuration filem please, ask me!
Regards
Antonio

**Comment by Aidaho12** [comment]
Hi,
Thank you ☺️
Have you installed metrics and all another services?  суббота, 14 ноября 2020г., 22:02 +06:00 от ascige  notifications@github.com :

**Comment by ascige** [comment]
Yes! I have installed all services with rpm packet
haproxy-wi-metrics.noarch                                                                                                               1-0.0                                                                                                                                    @HAProxy-WI

This is the result of : yum list installed

![Services on HaProxy-wi](https://user-images.githubusercontent.com/31512087/99151942-00cca800-269f-11eb-85c5-882e55aea77f.PNG)

This is an image of installed services
Thanks for your quickly answer

**Comment by Aidaho12** [comment]
Configuring should be easy... you should enable it on the Haproxy Overview page for certain servers

If it enabled, check the logs

**Comment by ascige** [comment]
I think so, but I don't understand. If I check, for example, "metrics" on HAProxy-->Overview this function should remain checked or not? What log I must see? I'am seeing haproxy.log on my server or I am wrong? I attach you a screenshot of my log.
Thanks for your patience

![HAProxy-log](https://user-images.githubusercontent.com/31512087/99152291-35416380-26a1-11eb-81bd-9361931fc469.PNG)

**Comment by Aidaho12** [comment]
It should be checked.

There is internal logs page in admin area

What shows the "Metrics" page?

**Comment by ascige** [comment]
The internal logs page ,as you now, can show some logs. If I try to show "Metrics.log" it says "Metrics master started". If I try to see, for example, "haproxy...log" I see the same logs of attached image. I don't know if for you is a goo information, but on general overview page, I see the "MAster metrics" ON and "Metrics workers" OFF. Maybe this the reason?
I attach you the "metrics " page.

![Metrics Page](https://user-images.githubusercontent.com/31512087/99152611-1fcd3900-26a3-11eb-88e0-6d3cb61b3866.PNG)

**Comment by Aidaho12** [comment]
If "Metrics workers" OFF it means that you haven't enabled it on the haproxy overview page. Can you show it?

Also on the internal logs should be the metrics-error.log

**Comment by ascige** [comment]
I find the problem! I don't know as I do this change, but on the right near "Logout" button I switch off "refresh interval".
Sorry, but maybe I made it without a sense! Thanks a lot for your support and have a nice evening

**Comment by Aidaho12** [comment]
Strange it does not influence on the metrics... but I glad that it works )
