### ISSUE TITLE
Accessing HAProxy-WI within Docker container

### ISSUE THREAD

**Issue by theaddies** [Aidaho12/haproxy-wi#255]
Sorry for the simple questions.  I am trying to configure haproxy-wi on an ubuntu linode machine per instructions from Wendel @ Level1.  I have haproxy-wi installed in a container and things appear to be working fine.  How do I access the configuration page for haproxy-wi.  When I type the local ip address of the container I get an apache splash page.  What file do I need to change or address do I need to type to be able to get to the configuration page for haproxy-wi?

**Comment by Aidaho12** [comment]
Can you open any HAProxy-WI page?

There are 2 configurations place: config file and configuration via web. Which one do you mean?

**Comment by theaddies** [comment]
I noticed that in the container the document folder for the apache server is /etc/httpd.  I changed that to /var/www/haproxy-wi in the httpd.conf file.  When I type the ip address of the container in a browser window it seems to work until it gets to the line /app/overview.py.  It then simply outputs the contents of that file in the browser window.  In trying to run overview.py from the command line I receive an error that says print(line.split(‘ ‘)[1], end=”<br>”).  This line is located in the file funct.py.

 

Does this shed any light on what I have going on?

**Comment by Aidaho12** [comment]
You have wrong httpd config. Httpd must run py files as fastcgi

**Comment by theaddies** [comment]
I’m sorry but I don’t know what fastcgi means or how to do things differently.

**Comment by Aidaho12** [comment]
Look at haproxy-wi.conf in repo or use https://haproxy-wi.org/docker.py вторник, 01 декабря 2020г., 14:58 +06:00 от theaddies  notifications@github.com :

**Comment by theaddies** [comment]
I did this.  I configured the docker container per the instructions provided.  The problem was that when going to the local ip address of the container it took me to an apache landing page and not the page for haproxy-wi.  That is why I went into the httpd config file and changed the document location to /var/www/haproxy-wi.  I forced it to point to the haproxy-wi index.html file.  It actually works and for about .5 seconds I see the haproxy-wi logo and then it disappears and the .py file appears.

**Comment by Aidaho12** [comment]
Do you mean that you see plain text again?

**Comment by theaddies** [comment]
This is the link I see in my browser.

 

172.18.0.3/app/overview.py

 

The file overview.py is in the browser in plain text.

**Comment by Aidaho12** [comment]
You should configure apache fir using fastcgi среда, 02 декабря 2020г., 00:02 +06:00 от theaddies  notifications@github.com :

**Comment by theaddies** [comment]
Yes.  I briefly see the logo for haproxy-wi and then it is replaced with the python code in plain text.

**Comment by Aidaho12** [comment]
When you configure apache properly, you will show web panel среда, 02 декабря 2020г., 00:11 +06:00 от theaddies  notifications@github.com :

**Comment by theaddies** [comment]
In the haproxy-wi.config you use the term my_domain.local:80.  What is my_domain.local?  Is it my domain name or the ip address of the container, which in my case is 172.17.0.2?

**Comment by Aidaho12** [comment]
Please, read about configuring Apache virtual host
