### ISSUE TITLE
Where to establish server

### ISSUE THREAD

**Issue by theaddies** [Aidaho12/haproxy-wi#256]
I am still working to get my system configured.  I have studied nginx, haproxy, and apache.  I am running ubuntu on a linode.  I have haproxy and nginx installed on the linode server.  I have haproxy-wi running in a docker container.  I can access the haproxy-wi configuration file.  I am now trying to connect a server.  I am confused as to where to do the setup.  The information in this link, https://haproxy-wi.org/description.py?description=setup, says to setup the server in the "admin area".  I did that and I get a verified connection.  However, when I go to overview it says that I do not have a server configured.  I then go to the "Servers" tab and I seemingly need to all the same things again in as was done in the "Admin area".  However, I am not allowed to duplicate the ip address for what haproxy-wi thinks is another server.  I deleted the server created in the "Admin area" and created that server in "Servers".  That server then appears both in "Servers" and "Admin area".  Where am I supposed to create the server?
![image](https://user-images.githubusercontent.com/3101960/102154294-0a386400-3e47-11eb-8cd4-05d8980ce8f8.png)
Now, even though I seem to be connected my overview page looks like this.
![image](https://user-images.githubusercontent.com/3101960/102154418-5b485800-3e47-11eb-88b5-22b35e5f5f6b.png)
When I click on either Haproxy or Nginx overview pages it says "Cannot get information about HAProxy.

**Comment by Aidaho12** [comment]
When you cannot see serer the overview page it seems that you and server have a different groups, or you have chosen virt checkbox.
Check logs, there is error, why HAProxy-WI cannot get information about haproxy вторник, 15 декабря 2020г., 07:08 +06:00 от theaddies  notifications@github.com :
