### ISSUE TITLE
NameError: name 'host' is not defined

### ISSUE THREAD

**Issue by scenigmatic** [Aidaho12/haproxy-wi#257]
Hi,
 
I have just done a fresh install of haproxy-wi on Ubuntu 18.04 and I get the following in the apache2 log:
 
_Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/overview.py", line 133, in 
    host=host,
NameError: name 'host' is not defined_
 
I’ve done a lot of searching but cannot find why this is happening. It occurs after I put in the username and password – it just goes back to the login screen.
 
I had a previous version installed and running OK (but old hence doing a fresh install while we are still testing).
 
Any idea what may be going on?
 
Thanks

**Comment by Aidaho12** [comment]
this error is ok

Try to clear you cache and cookies and login again

**Comment by scenigmatic** [comment]
Thanks - yes, cookie cleardown sorted this. Other similar errors have also come up after login - clicking on Haproxy or Admin Area leaves the following lines in the log and a white screen:

Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/users.py", line 80, in <module>
    openvpn=openvpn,
NameError: name 'openvpn' is not defined
Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/hapservers.py", line 57, in <module>
    services.append([s, service_ver[0]])
IndexError: list index out of range

**Comment by Aidaho12** [comment]
Edit please /var/www/haproxy-wi/app/hapservers.py on line 57:

```
try:
        services.append([s, service_ver[0]])
except Exception:
        services.append([s, ''])
```
instead of services.append([s, service_ver[0]])

users.py add the
```
openvpn_configs = ''
openvpn_sess = ''
openvpn = ''
```
after
```
funct.check_login()
funct.page_for_admin()
```
in the beginning of file

**Comment by scenigmatic** [comment]
Thanks - Yes, these fixes worked. I'm finding another:

_Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/hapservers.py", line 57, in <module>
    services.append([s, service_ver[0]])
IndexError: list index out of range_

when clicking on HAProxy -> Overview (and a couple of other links).

**Comment by Aidaho12** [comment]
Look at my prev post at the beginning, there is solution

**Comment by scenigmatic** [comment]
Sorry, yes, I had done it but quit with saving!

**Comment by Aidaho12** [comment]
does it works now?

**Comment by scenigmatic** [comment]
Sorry, another one when clicking on Add Proxy:

Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/add.py", line 35, in <module>
    os.makedirs(dir)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/var/www/haproxy-wi/lists'

Permissions look ok and there is only a folder called '1' in there

**Comment by Aidaho12** [comment]
edit it to:
```
os.makedirs(white_dir)
```

**Comment by scenigmatic** [comment]
Yep, that fixed that one ... another when clicking on Metrics:

Traceback (most recent call last):
  File "/var/www/haproxy-wi/app/metrics.py", line 30, in <module>
    services=service_ver[0],
IndexError: list index out of range

**Comment by Aidaho12** [comment]
No, you can't. You have to have access to rpm repository for it, and of course El distributive

**Comment by Aidaho12** [comment]
I've fixed bug with metrics, please, update
