### ISSUE TITLE
RPM installation does not work in amazon linux 2, documentation needs to be updated

### ISSUE THREAD

**Issue by epoplive** [Aidaho12/haproxy-wi#261]
I paid for a business license for the product, absolutely struggling to get this installed and web interface running on anything other than RHEL x64.  On AmazonLinux2 there seems to be issues related to the version of python installed by default, with the httpd logs complaining about missing the ginga2 package.  I tried installing python 3.7 and reinstalling requrements using pip3 requirements.txt, but continued to run into problems.

Unfortunately the documentation for the install seems to also not mention that it is only compatible with x86, I wasted a bunch of time before I realized this.  Is the RPM version of this project effectively only workable with RHEL x86?  If so is it possible to request a refund for my purchase?

**Comment by Aidaho12** [comment]
Hi, what error do you have?

Yes, it's possible. You may ask refund on patreon

**Comment by epoplive** [comment]
It gives an error about ginga2 not being installed.  From reading other tickets related to the non-rpm install, it looks like it's because amazon linux 2 is using python 2.7.  If you install python3 and set it as the primary via alternates (which breaks yum), and then install the dependancies via pip3 in /var/www/haproxy-wi/, it then leads to errors about I believe missing python modules.  I don't have the server up anymore to give you the errors, and had intentionally paid for the product RPM's to avoid going down this kind of rabbithole, and this gives me low expectations for some of the other feature sets working as well.

I also was unable to get this working in RHEL8 using arm instances in AWS.  It looks like the installer scripts are looking for x86/64 packages rather than for the appropriate platform.

My frustration here is that it seems like the documentation is either out of date regarding supported operating systems (and cpu platforms) or the instructions and/or packaging is out of date.  As far as I can tell, there is no way to trial the RPM version which purports to offer extra features, and there's no way for me to make an educated decision prior to purchase.

Please let me know what your intentions are regarding platform updates/support so I can decide wether or not to request a refund.  Thanks.

**Comment by Aidaho12** [comment]
I'm sorry that you have such a bad experience

I will investigate these problems and solve them

**Comment by Aidaho12** [comment]
I've found out where problem is.

It was because amazon linux has old pip3. Pip3 tries build cryptography module and fails. I've added this exception to RPM installation it works now.

There is a new package. Please, try it

**Comment by Aidaho12** [comment]
For ARM it cannot be used, because cryptography module is only for x86

**Comment by epoplive** [comment]
I've tried x86 amazon linux again, and while HAProxy-WI installs, there seems to still be issues on the platform.  On both RHEL8 and Amazon Linux 2 (x86) the UI itself seems to be having issues with the url hashes.  I'm having to manually put the urls in the address bar half of the time to get them to work.

On Amazon Linux2, it took multiple attempts to get HAProxy to install via the UI.  Nginx will not install, there doesn't seem to be any error though.  It creates an /etc/nginx/conf.d folder with nothing in it, and no nginx service installed.

What is the suggested platform for this product to actually run on?  Do I need to be using an older version of RHEL for this to function properly?

**Comment by Aidaho12** [comment]
`I'm having to manually put the urls in the address bar half of the time to get them to work.`
What do you mean? when you click on the left menu it doesn't work?

`What is the suggested platform for this product to actually run on? Do I need to be using an older version of RHEL for this to function properly?`
Better use Centos 7
