### ISSUE TITLE
Repo with username and password not working

### ISSUE THREAD

**Issue by yashar6909** [Aidaho12/haproxy-wi#262]
Format from your install guide. 

baseurl = http://login:password@repo.haproxy-wi.org/$ostype$releasever/

I am getting a 404 error

baseurl = http://awersomeusername:supersafepassword@repo.haproxy-wi.org/$ostype$releasever/ (I have modified user and password for this of course)

**Comment by Aidaho12** [comment]
What error do you get?

**Comment by Aidaho12** [comment]
The 404 error means that some file isn't found, if you had a problem with your login you would have 401 error

On what OS do you try to install?

**Comment by yashar6909** [comment]
on oracle linux 9

**Comment by Aidaho12** [comment]
there isn't package excactly for Oracle Linux, but you may try to edit bareurl like:

```
baseurl = http://login:password@repo.haproxy-wi.org/el8/
```

HAProxy-WI should work on Oracle

There is the list which OS HAProxy-WI supports https://haproxy-wi.org/installation.py#os
