### ISSUE TITLE
Haproxy show Map not working

### ISSUE THREAD

**Issue by ThibautBascoulergue** [Aidaho12/haproxy-wi#263]
Hello,

I have Haproxy-wi latest version : 5.0.1.0 and I can't display the haproxy map. The page is blank and in the logs i have this 👍 

[Mon Mar 15 12:22:38.216173 2021] [cgi:error] [pid 16569:tid 16569] [client 10.160.1.142:50432] AH01215: Traceback (most recent call last):: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/config.py?serv=10.1.2.24&showMap
[Mon Mar 15 12:22:38.216214 2021] [cgi:error] [pid 16569:tid 16569] [client 10.160.1.142:50432] AH01215:   File "/var/www/haproxy-wi/app/options.py", line 795, in <module>: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/config.py?serv=10.1.2.24&showMap
[Mon Mar 15 12:22:38.216230 2021] [cgi:error] [pid 16569:tid 16569] [client 10.160.1.142:50432] AH01215:     line_new2[1] = line_new2[1].strip(' \\t\\n\\r'): /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/config.py?serv=10.1.2.24&showMap
[Mon Mar 15 12:22:38.216242 2021] [cgi:error] [pid 16569:tid 16569] [client 10.160.1.142:50432] AH01215: IndexError: list index out of range: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/config.py?serv=10.1.2.24&showMap

thank's for you help.

**Comment by Aidaho12** [comment]
Hello,

Could you show your haproxy config file?

**Comment by ThibautBascoulergue** [comment]
`global
  ssl-default-bind-options ssl-min-ver TLSv1.0 no-tls-tickets # WARNING: tlsv1.3 disabled to avoid forced cipher issue
  #ssl-default-server-options ssl-min-ver TLSv1.0 no-tls-tickets
  tune.bufsize 128000
  tune.http.maxhdr  32767
  h1-case-adjust cache-control Cache-Control
  h1-case-adjust content-type Content-Type
  h1-case-adjust date Date 
  h1-case-adjust persistent-auth Persistent-Auth
  h1-case-adjust server Server
  h1-case-adjust set-cookie Set-Cookie
  h1-case-adjust transfer-encoding Transfer-Encoding
  h1-case-adjust www-authenticate WWW-Authenticate
  h1-case-adjust x-aspnet-version X-AspNet-Version
  h1-case-adjust x-clientinfo X-ClientInfo
  h1-case-adjust x-expirationinfo X-ExpirationInfo
  h1-case-adjust x-pendingperiod X-PendingPeriod
  h1-case-adjust x-powered-by X-Powered-By
  h1-case-adjust x-requestid X-RequestId
  h1-case-adjust x-requesttype X-RequestType
  h1-case-adjust x-responsecode X-ResponseCode
  h1-case-adjust x-serverapplication X-ServerApplication
  h1-case-adjust x-forwarded-for X-Forwarded-For

    log         127.0.0.1 local2
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     15000
    user        haproxy
    group       haproxy
    daemon
    stats socket /var/lib/haproxy/stats
    stats socket *:1999 level admin
    stats socket /var/run/haproxy.sock mode 600 level admin
    server-state-file /etc/haproxy/haproxy.state
    #ssl-server-verify none

peers EX2016-XX
 peer SRVEX2016CCV-HA 10.1.2.23:1023
 peer SRVEX2016JG-HA 10.1.2.24:1023

defaults
    mode                            tcp
    log                             global
    option                          tcplog
    option                          logasap
#   option                          dontlognull         # Do not log connections with no requests
    option                          redispatch          # Try another server in case of connection failure
    option                          contstats           # Enable continuous traffic statistics updates
    option                          allbackups          # allow using all backup servers in a farm
    option                          forwardfor          except 127.0.0.1/32
    backlog                         10000               # Size of SYN backlog queue
#
    option                          tcpka               # frontend + backend
#
    balance                         leastconn
    default-server                  inter 5s  rise 2  fall 3  weight 10
    maxconn                         15000
    retries                         3
#
    timeout                         connect          5s #  5 seconds max for the TCP connect
    timeout                         server           1h # 60 minutes max inactivity
    timeout                         client           1h # 60 minutes max inactivity
    timeout                         http-request     1m
    timeout                         queue           30s # 30 seconds max for a request to stay in a queue

#peers mypeers
#    bind *:1022
#    server 127.0.0.1



listen stats 
    bind *:8085
    mode http
    stats enable
    stats uri /stats
    stats realm HAProxy-04\ Statistics
    stats auth admin:password
    stats admin if TRUE

frontend http-https-frontend
        bind                    *:443 name *:443 ssl crt /etc/haproxy/chu-poitiers-Wildcard.pem
        #bind                    *:443 name *:443
        bind                    *:80 name *:80
        mode                    http
        log                     global
        option                  h1-case-adjust-bogus-client
        option                  socket-stats
        option                  log-separate-errors
        option                  httplog
        option                  http-keep-alive
        option                  forwardfor
        option                  accept-invalid-http-request
        acl https ssl_fc
        http-request set-header         X-Forwarded-Proto http if !https
        http-request set-header         X-Forwarded-Proto https if https
        http-request set-header Host webmail.chu-poitiers.fr if { hdr(host) -i webmail }
        http-request set-header Host webmail.chu-poitiers.fr if { hdr(host) -i webmail.chu-poitiers.local }
        maxconn                 15000
        timeout client          30000
        capture request header Host len 32
        capture request header User-Agent len 64
        capture response header Content-Length len 10
        #option httplog
        log-format %ci:%cp\ [%t]\ %ft\ %b/%s\ %Tq/%Tw/%Tc/%Tr/%Tt\ %ST\ %B\ %CC\ %CS\ %tsc\ %ac/%fc/%bc/%sc/%rc\ %sq/%bq\ %hr\ %hs\ {%sslv/%sslc/%[ssl_fc_sni]/%[ssl_fc_session_id]}\ "%[capture.req.method]\ %[capture.req.hdr(0)]%[capture.req.uri]\ HTTP/1.1"
        option  contstats               # Enable continuous traffic statistics updates
        timeout http-keep-alive 30s     # 15 second max for the client to post next request
        timeout http-request 30s        # 15 seconds max for the client to send a request
        acl                     not_https       ssl_fc,not
        acl                     is_portal       var(txn.txnhost) -m str -i webmail.chu-poitiers.fr
        acl                     is_healthcheck  var(txn.txnpath) -m reg -i healthcheck.htm$
        acl                     is_autodiscover var(txn.txnhost) -m str -i autodiscover.chu-poitiers.fr
        acl                     is_ecp  var(txn.txnpath) -m sub -i /ecp/
        acl                     is_rpc  var(txn.txnpath) -m sub -i /rpc/
        acl                     is_owa  var(txn.txnpath) -m sub -i /OWA/
        acl                     is_ews  var(txn.txnpath) -m sub -i /EWS/
        acl                     is_oab  var(txn.txnpath) -m sub -i /OAB/
        acl                     is_eas  var(txn.txnpath) -m sub -i /EAS/
        acl                     is_mapi var(txn.txnpath) -m sub -i /mapi/
        http-request set-var(txn.txnpath) path
        http-request set-var(txn.txnhost) hdr(host)
        #http-response deny  if  is_ecp
        http-response deny  if  is_healthcheck
        http-request redirect scheme https code 301  if  not_https
        use_backend portal-backend_ipvANY  if  is_portal
        use_backend ex-Autodiscover-backend_ipvANY  if  is_autodiscover
        use_backend ex-RPC-backend_ipvANY  if  is_rpc
        use_backend ex-OWA-backend_ipvANY  if  is_owa
        use_backend ex-EWS-backend_ipvANY  if  is_ews
        use_backend ex-OAB-backend_ipvANY  if  is_oab
        use_backend ex-EAS-backend_ipvANY  if  is_eas
        use_backend ex-MAPI-backend_ipvANY  if  is_mapi
        use_backend ex-ECP-backend_ipvANY  if  is_ecp
        default_backend ex-OWA-backend_ipvANY


frontend smtp-frontend
        bind                    *:25 name *:25
        mode                    tcp
        log                     global
        option                  socket-stats
        option                  dontlognull
        option                  dontlog-normal
        maxconn                 15000
        timeout client          300000
        option tcplog
        option contstats
        default_backend ex-smtp-backend_ipvANY

frontend smtptls-frontend
        bind                    *:587 name *:587
        mode                    tcp
        log                     global
        option                  dontlognull
        option                  dontlog-normal
        maxconn                 15000
        timeout client          300000
        option tcplog
        option contstats
        default_backend ex-smtptls-backend_ipvANY

frontend smtpssl-frontend
        bind                    *:465 name *:465
        mode                    tcp
        log                     global
        option                  dontlognull
        option                  dontlog-normal
        maxconn                 15000
        timeout client          300000
        option tcplog
        option contstats
        default_backend ex-smtpssl-backend_ipvANY

frontend imap-frontend
        bind                    *:143 name *:143
        mode                    tcp
        log                     global
        option                  dontlognull
        option                  dontlog-normal
        maxconn                 15000
        timeout client          300000
        option tcplog
        option contstats
        default_backend ex-imap-backend_ipvANY

frontend imaps-frontend
        bind                    *:993 name *:993
        mode                    tcp
        log                     global
        option                  dontlognull
        option                  dontlog-normal
        timeout client          300000
        option contstats
        default_backend ex-imaps-backend_ipvANY

frontend pop-frontend
        bind                    *:110 name *:110
        mode                    tcp
        log                     global
        option                  dontlognull
        option                  dontlog-normal
        maxconn                 15000
        timeout client          300000
        option tcplog
        option contstats
        default_backend ex-pop-backend_ipvANY

frontend pops-frontend
        bind                    *:995 name *:995
        mode                    tcp
        log                     global
        option                  dontlognull
        option                  dontlog-normal
        maxconn                 15000
        timeout client          300000
        option tcplog
        option contstats
        default_backend ex-pops-backend_ipvANY

backend portal-backend_ipvANY
        mode                    http
        id                      103
        log                     global
        #option                  h1-case-adjust-bogus-server
        stats                   enable
        stats                   uri /haproxy?stats
        stats                   realm .
        balance                 leastconn
        timeout connect         30000
        timeout server          30000
        retries                 3
        server                  SRVEX2016CCV1 10.1.2.130:443 id 101 ssl check inter 3000  verify none
        server                  SRVEX2016JG1 10.1.2.131:443 id 102 ssl check inter 3000  verify none
        server                  SRVEX2016CCV2 10.1.2.132:443 id 103 ssl check inter 3000  verify none
        server                  SRVEX2016JG2 10.1.2.133:443 id 104 ssl check inter 3000  verify none

backend ex-ECP-backend_ipvANY
        mode                    http
        id                      120
        log                     global
        stats                   enable
        stats                   uri /haproxy?stats
        stats                   realm .
        timeout connect         30000
        timeout server          30000
        retries                 3
        server                  SRVEX2016CCV1 10.1.2.130:443 id 101 ssl check inter 3000  verify none
        server                  SRVEX2016JG1 10.1.2.131:443 id 102 ssl check inter 3000  verify none
        server                  SRVEX2016CCV2 10.1.2.132:443 id 103 ssl check inter 3000  verify none
        server                  SRVEX2016JG2 10.1.2.133:443 id 104 ssl check inter 3000  verify none

backend ex-Autodiscover-backend_ipvANY
        mode                    http
        id                      105
        log                     global
        stats                   enable
        stats                   uri /haproxy?stats
        stats                   realm .
        balance                 leastconn
        balance                 leastconn
        timeout connect         30000
        timeout server          30000
        retries                 3
        option                  httpchk GET /autodiscover/healthcheck.htm
        http-check expect status 200
        option  redispatch              # Try another server in case of connection failure
        server                  SRVEX2016CCV1 10.1.2.130:443 id 101 ssl check inter 3000  verify none
        server                  SRVEX2016JG1 10.1.2.131:443 id 102 ssl check inter 3000  verify none
        server                  SRVEX2016CCV2 10.1.2.132:443 id 103 ssl check inter 3000  verify none
        server                  SRVEX2016JG2 10.1.2.133:443 id 104 ssl check inter 3000  verify none


backend ex-RPC-backend_ipvANY
        mode                    http
        id                      106
        log                     global
        stats                   enable
        stats                   uri /haproxy?stats
        stats                   realm .
        balance                 leastconn
        timeout connect         30000
        timeout server          30000
        retries                 3
        option                  httpchk GET /RPC/HealthCheck.htm
        http-check expect status 200
        cookie SERVERID insert nocache
        option  redispatch              # Try another server in case of connection failure
        #timeout queue 30s               # 30 seconds max queued on load balancer
        server                  SRVEX2016CCV1 10.1.2.130:443 id 101 ssl check inter 1000 verify none cookie uni1
        server                  SRVEX2016JG1 10.1.2.131:443 id 102 ssl check inter 1000 verify none cookie unit2
        server                  SRVEX2016CCV2 10.1.2.132:443 id 103 ssl check inter 1000 verify none cookie unit3
        server                  SRVEX2016JG2 10.1.2.133:443 id 104 ssl check inter 1000 verify none cookie unit4

backend ex-OWA-backend_ipvANY
        mode                    http
        id                      100
        log                     global
        stats                   enable
        stats                   uri /haproxy?stats
        stats                   realm .
        balance                 leastconn
        timeout connect         30000
        timeout server          30000
        retries                 3
        option                  httpchk GET /OWA/HealthCheck.htm
        http-check expect status 200
        option  redispatch              # Try another server in case of connection failure
        server                  SRVEX2016CCV1 10.1.2.130:443 id 101 ssl check inter 1000  verify none
        server                  SRVEX2016JG1 10.1.2.131:443 id 102 ssl check inter 1000  verify none
        server                  SRVEX2016CCV2 10.1.2.132:443 id 103 ssl check inter 1000  verify none
        server                  SRVEX2016JG2 10.1.2.133:443 id 104 ssl check inter 1000  verify none

backend ex-EWS-backend_ipvANY
        mode                    http
        id                      107
        log                     global
        stats                   enable
        stats                   uri /haproxy?stats
        stats                   realm .
        balance                 leastconn
        timeout connect         30000
        timeout server          30000
        retries                 3
        option                  httpchk GET /EWS/HealthCheck.htm
        http-check expect status 200
        option  redispatch              # Try another server in case of connection failure
        #timeout queue 30s               # 30 seconds max queued on load balancer
        server                  SRVEX2016CCV1 10.1.2.130:443 id 101 ssl check inter 1000  verify none
        server                  SRVEX2016JG1 10.1.2.131:443 id 102 ssl check inter 1000  verify none
        server                  SRVEX2016CCV2 10.1.2.132:443 id 103 ssl check inter 1000  verify none
        server                  SRVEX2016JG2 10.1.2.133:443 id 104 ssl check inter 1000  verify none

backend ex-OAB-backend_ipvANY
        mode                    http
        id                      108
        log                     global
        stats                   enable
        stats                   uri /haproxy?stats
        stats                   realm .
        balance                 leastconn
        timeout connect         30000
        timeout server          30000
        retries                 3
        option                  httpchk GET /OAB/HealthCheck.htm
        http-check expect status 200
        option  redispatch              # Try another server in case of connection failure
        #timeout queue 30s               # 30 seconds max queued on load balancer
        server                  SRVEX2016CCV1 10.1.2.130:443 id 101 ssl check inter 1000  verify none
        server                  SRVEX2016JG1 10.1.2.131:443 id 102 ssl check inter 1000  verify none
        server                  SRVEX2016CCV2 10.1.2.132:443 id 103 ssl check inter 1000  verify none
        server                  SRVEX2016JG2 10.1.2.133:443 id 104 ssl check inter 1000  verify none

backend ex-EAS-backend_ipvANY
        mode                    http
        id                      109
        log                     global
        stats                   enable
        stats                   uri /haproxy?stats
        stats                   realm .
        balance                 leastconn
        timeout connect         30000
        timeout server          30000
        retries                 3
        option                  httpchk GET /Microsoft-Server-ActiveSync/HealthCheck.htm
        http-check expect status 200
        option  redispatch              # Try another server in case of connection failure
        #timeout queue 30s               # 30 seconds max queued on load balancer
        server                  SRVEX2016CCV1 10.1.2.130:443 id 101 ssl check inter 1000  verify none
        server                  SRVEX2016JG1 10.1.2.131:443 id 102 ssl check inter 1000  verify none
        server                  SRVEX2016CCV2 10.1.2.132:443 id 103 ssl check inter 1000  verify none
        server                  SRVEX2016JG2 10.1.2.133:443 id 104 ssl check inter 1000  verify none

backend ex-MAPI-backend_ipvANY
        mode                    http
        id                      116
        log                     global
        #option                  h1-case-adjust-bogus-server
        stats                   enable
        stats                   uri /haproxy?stats
        stats                   realm .
        balance                 leastconn
        timeout connect         30000
        timeout server          30000
        retries                 3
        option                  httpchk GET /mapi/HealthCheck.htm
        http-check expect status 200
        option  redispatch              # Try another server in case of connection failure
        #timeout queue 30s               # 30 seconds max queued on load balancer
        server                  SRVEX2016CCV1 10.1.2.130:443 id 101 ssl check inter 1000  verify none
        server                  SRVEX2016JG1 10.1.2.131:443 id 102 ssl check inter 1000  verify none
        server                  SRVEX2016CCV2 10.1.2.132:443 id 103 ssl check inter 1000  verify none
        server                  SRVEX2016JG2 10.1.2.133:443 id 104 ssl check inter 1000  verify none

backend ex-smtp-backend_ipvANY
        mode                    tcp
        id                      110
        log                     global
        balance                 leastconn
        timeout connect         5000
        timeout server          30000
        retries                 3
        option redispatch
        option tcp-check
        tcp-check expect string 220
        default-server rise 2 fall 3
        server                  SRVEX2016CCV1 10.1.2.130:25 id 111 check inter 3000
        server                  SRVEX2016JG1 10.1.2.131:25 id 112 check inter 3000
        server                  SRVEX2016CCV2 10.1.2.132:25 id 113 check inter 3000
        server                  SRVEX2016JG2 10.1.2.133:25 id 114 check inter 3000


backend ex-smtptls-backend_ipvANY
        mode                    tcp
        id                      115
        log                     global
        balance                 leastconn
        timeout connect         5000
        timeout server          30000
        retries                 3
        default-server rise 2 fall 3
        option redispatch
        option tcp-check
        tcp-check expect string 220
        server                  SRVEX2016CCV1 10.1.2.130:587 id 111 check inter 3000
        server                  SRVEX2016JG1 10.1.2.131:587 id 112 check inter 3000
        server                  SRVEX2016CCV2 10.1.2.132:587 id 113 check inter 3000
        server                  SRVEX2016JG2 10.1.2.133:587 id 114 check inter 3000

backend ex-smtpssl-backend_ipvANY
        mode                    tcp
        id                      121
        log                     global
        balance                 leastconn
        timeout connect         5000
        timeout server          30000
        retries                 3
        option redispatch
        option tcp-check
        #tcp-check connect port 465 ssl
        tcp-check connect
        tcp-check expect string 220
        default-server rise 2 fall 3
        server                  SRVEX2016CCV1 10.1.2.130:465 id 111 check inter 3000 verify none
        server                  SRVEX2016JG1 10.1.2.131:465 id 112 check inter 3000 verify none
        server                  SRVEX2016CCV2 10.1.2.132:465 id 113 check inter 3000 verify none
        server                  SRVEX2016JG2 10.1.2.133:465 id 114 check inter 3000 verify none

backend ex-imap-backend_ipvANY
        mode                    tcp
        id                      114
        log                     global
        option                  log-health-checks
        balance                 leastconn
        timeout connect         30000
        timeout server          30000
        retries                 3
        option tcp-check
        tcp-check connect
        tcp-check expect string *\ OK
        tcp-check expect string 220
        server                  SRVEX2016CCV1 10.1.2.130:143 id 111 check inter 1000
        server                  SRVEX2016JG1 10.1.2.131:143 id 112 check inter 1000
        server                  SRVEX2016CCV2 10.1.2.132:143 id 113 check inter 1000
        server                  SRVEX2016JG2 10.1.2.133:143 id 114 check inter 1000

backend ex-imaps-backend_ipvANY
        mode                    tcp
        id                      117
        log                     global
        balance                 leastconn
        timeout connect         5000
        timeout server          30000
        retries                 3
        option redispatch
        option tcp-check
        tcp-check connect port 993 ssl
        tcp-check expect string *\ OK
        server                  SRVEX2016CCV1 10.1.2.130:993 id 111 check inter 3000 verify none
        server                  SRVEX2016JG1 10.1.2.131:993 id 112 check inter 3000 verify none
        server                  SRVEX2016CCV2 10.1.2.132:993 id 113 check inter 3000 verify none
        server                  SRVEX2016JG2 10.1.2.133:993 id 114 check inter 3000 verify none

backend ex-pop-backend_ipvANY
        mode                    tcp
        id                      132
        log                     global
        #option                  log-health-checks
        balance                 leastconn
        timeout connect         5000
        timeout server          30000
        retries                 3
        option redispatch
        option tcp-check
        tcp-check connect port 110
        tcp-check expect string +OK
        #default-server rise 2 fall 3
        server                  SRVEX2016CCV1 10.1.2.130:110 id 111 check inter 5000
        server                  SRVEX2016JG1 10.1.2.131:110 id 112 check inter 5000
	server                  SRVEX2016CCV2 10.1.2.132:110 id 113 check inter 5000
        server                  SRVEX2016JG2 10.1.2.133:110 id 114 check inter 5000

backend ex-pops-backend_ipvANY
        mode                    tcp
        id                      131
        log                     global
        #option                  log-health-checks
        balance                 leastconn
        timeout connect         5000
        timeout server          30000
        retries                 3
        option redispatch
        option tcp-check
        tcp-check connect port 995 ssl
        tcp-check expect string +OK
        #default-server rise 2 fall 3
        server                  SRVEX2016CCV1 10.1.2.130:995 id 111 check inter 5000 verify none
        server                  SRVEX2016JG1 10.1.2.131:995 id 112 check inter 5000 verify none
        server                  SRVEX2016CCV2 10.1.2.132:995 id 113 check inter 5000 verify none
        server                  SRVEX2016JG2 10.1.2.133:995 id 114 check inter 5000 verify none
`

**Comment by Aidaho12** [comment]
I suppose that error causes this:
```
bind *:80 name *:80
```

**Comment by ThibautBascoulergue** [comment]
Hi, same error after rename the bind. I can't show map.

82 bind *:443 name WITHSSL ssl crt /etc/haproxy/chu-poitiers-Wildcard.pem
83 bind *:80 name NOSSL

**Comment by Aidaho12** [comment]
I've found it. replace 795 line in options.py to:

```
                try:
                    line_new2[1] = line_new2[1].strip(' \t\n\r')
                except Exception as e:
                    line_new2 = ['','']
```

**Comment by ThibautBascoulergue** [comment]
Hello,

The modification does not work and it crashes the main page where we see the status of haproxy.
![2021-03-19 11_01_51-Window](https://user-images.githubusercontent.com/42678960/111763699-b81e3900-88a2-11eb-89e1-17f528fda08b.png)

**Comment by Aidaho12** [comment]
it doesn't influence on another pages

How did you past it?

**Comment by ThibautBascoulergue** [comment]
I edited the file with vim directly and commented out line 795 and added the other three below.

**Comment by Aidaho12** [comment]
I think, you've made mistake somewhere

**Comment by ThibautBascoulergue** [comment]
I used the autopep8 -i  /var/www/haproxy-wi/app/options.py
command

to correct the tabs file. And I always have the same mistakes

[Mon Mar 22 09:51:30.290259 2021] [cgi:error] [pid 53612:tid 53612] [client 10.160.1.142:51081] AH01215:   File "/var/www/haproxy-wi/app/options.py", line 842: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/overview.py
[Mon Mar 22 09:51:30.290329 2021] [cgi:error] [pid 53612:tid 53612] [client 10.160.1.142:51081] AH01215:     except Exception as e:: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/overview.py
[Mon Mar 22 09:51:30.290336 2021] [cgi:error] [pid 53612:tid 53612] [client 10.160.1.142:51081] AH01215:          ^: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/overview.py
[Mon Mar 22 09:51:30.290346 2021] [cgi:error] [pid 53612:tid 53612] [client 10.160.1.142:51081] AH01215: SyntaxError: invalid syntax: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/overview.py
[Mon Mar 22 09:51:30.292581 2021] [cgi:error] [pid 53612:tid 53612] [client 10.160.1.142:51081] End of script output before headers: options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/overview.py

**Comment by Aidaho12** [comment]
then download this file https://github.com/Aidaho12/haproxy-wi/blob/master/app/options.py

**Comment by ThibautBascoulergue** [comment]
it works, thank you ;)
