### ISSUE TITLE
show log in stdout mod UnicodeDecodeError

### ISSUE THREAD

**Issue by ThibautBascoulergue** [Aidaho12/haproxy-wi#264]
Hello,

I configured my haproxy to log requests from a specific frontend. When I want to display them, I think there are some characters that it can't decode, therefore, it doesn't display anything

[Tue Mar 30 15:34:56.647971 2021] [cgi:error] [pid 92781:tid 92781] [client 10.160.1.142:59018] AH01215: Traceback (most recent call last):: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/logs.py?service=haproxy&serv=10.1.2.24&rows=500&exgrep=&grep=&hour=01&minut=45&hour1=17&minut1=15&waf=0
[Tue Mar 30 15:34:56.648045 2021] [cgi:error] [pid 92781:tid 92781] [client 10.160.1.142:59018] AH01215:   File "/var/www/haproxy-wi/app/options.py", line 700, in <module>: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/logs.py?service=haproxy&serv=10.1.2.24&rows=500&exgrep=&grep=&hour=01&minut=45&hour1=17&minut1=15&waf=0
[Tue Mar 30 15:34:56.648075 2021] [cgi:error] [pid 92781:tid 92781] [client 10.160.1.142:59018] AH01215:     minut1=minut1, service=service): /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/logs.py?service=haproxy&serv=10.1.2.24&rows=500&exgrep=&grep=&hour=01&minut=45&hour1=17&minut1=15&waf=0
[Tue Mar 30 15:34:56.648115 2021] [cgi:error] [pid 92781:tid 92781] [client 10.160.1.142:59018] AH01215:   File "/var/www/haproxy-wi/app/funct.py", line 888, in show_haproxy_log: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/logs.py?service=haproxy&serv=10.1.2.24&rows=500&exgrep=&grep=&hour=01&minut=45&hour1=17&minut1=15&waf=0
[Tue Mar 30 15:34:56.648147 2021] [cgi:error] [pid 92781:tid 92781] [client 10.160.1.142:59018] AH01215:     return ssh_command(syslog_server, commands, show_log='1', grep=grep): /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/logs.py?service=haproxy&serv=10.1.2.24&rows=500&exgrep=&grep=&hour=01&minut=45&hour1=17&minut1=15&waf=0
[Tue Mar 30 15:34:56.648176 2021] [cgi:error] [pid 92781:tid 92781] [client 10.160.1.142:59018] AH01215:   File "/var/www/haproxy-wi/app/funct.py", line 987, in ssh_command: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/logs.py?service=haproxy&serv=10.1.2.24&rows=500&exgrep=&grep=&hour=01&minut=45&hour1=17&minut1=15&waf=0
[Tue Mar 30 15:34:56.648200 2021] [cgi:error] [pid 92781:tid 92781] [client 10.160.1.142:59018] AH01215:     return show_log(stdout, grep=kwargs.get("grep")): /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/logs.py?service=haproxy&serv=10.1.2.24&rows=500&exgrep=&grep=&hour=01&minut=45&hour1=17&minut1=15&waf=0
[Tue Mar 30 15:34:56.648235 2021] [cgi:error] [pid 92781:tid 92781] [client 10.160.1.142:59018] AH01215:   File "/var/www/haproxy-wi/app/funct.py", line 837, in show_log: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/logs.py?service=haproxy&serv=10.1.2.24&rows=500&exgrep=&grep=&hour=01&minut=45&hour1=17&minut1=15&waf=0
[Tue Mar 30 15:34:56.648249 2021] [cgi:error] [pid 92781:tid 92781] [client 10.160.1.142:59018] AH01215:     for line in stdout:\t\t: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/logs.py?service=haproxy&serv=10.1.2.24&rows=500&exgrep=&grep=&hour=01&minut=45&hour1=17&minut1=15&waf=0
[Tue Mar 30 15:34:56.648287 2021] [cgi:error] [pid 92781:tid 92781] [client 10.160.1.142:59018] AH01215:   File "/usr/local/lib/python3.6/site-packages/paramiko/file.py", line 122, in __next__: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/logs.py?service=haproxy&serv=10.1.2.24&rows=500&exgrep=&grep=&hour=01&minut=45&hour1=17&minut1=15&waf=0
[Tue Mar 30 15:34:56.648319 2021] [cgi:error] [pid 92781:tid 92781] [client 10.160.1.142:59018] AH01215:     line = self.readline(): /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/logs.py?service=haproxy&serv=10.1.2.24&rows=500&exgrep=&grep=&hour=01&minut=45&hour1=17&minut1=15&waf=0
[Tue Mar 30 15:34:56.648358 2021] [cgi:error] [pid 92781:tid 92781] [client 10.160.1.142:59018] AH01215:   File "/usr/local/lib/python3.6/site-packages/paramiko/file.py", line 338, in readline: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/logs.py?service=haproxy&serv=10.1.2.24&rows=500&exgrep=&grep=&hour=01&minut=45&hour1=17&minut1=15&waf=0
[Tue Mar 30 15:34:56.648392 2021] [cgi:error] [pid 92781:tid 92781] [client 10.160.1.142:59018] AH01215:     return line if self._flags & self.FLAG_BINARY else u(line): /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/logs.py?service=haproxy&serv=10.1.2.24&rows=500&exgrep=&grep=&hour=01&minut=45&hour1=17&minut1=15&waf=0
[Tue Mar 30 15:34:56.648436 2021] [cgi:error] [pid 92781:tid 92781] [client 10.160.1.142:59018] AH01215:   File "/usr/local/lib/python3.6/site-packages/paramiko/py3compat.py", line 102, in u: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/logs.py?service=haproxy&serv=10.1.2.24&rows=500&exgrep=&grep=&hour=01&minut=45&hour1=17&minut1=15&waf=0
[Tue Mar 30 15:34:56.648458 2021] [cgi:error] [pid 92781:tid 92781] [client 10.160.1.142:59018] AH01215:     return s.decode('utf-8'): /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/logs.py?service=haproxy&serv=10.1.2.24&rows=500&exgrep=&grep=&hour=01&minut=45&hour1=17&minut1=15&waf=0
[Tue Mar 30 15:34:56.648506 2021] [cgi:error] [pid 92781:tid 92781] [client 10.160.1.142:59018] AH01215: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 384: invalid start byte: /var/www/haproxy-wi/app/options.py, referer: https://srvhaproxy-wi.chu-poitiers.local/app/logs.py?service=haproxy&serv=10.1.2.24&rows=500&exgrep=&grep=&hour=01&minut=45&hour1=17&minut1=15&waf=0

**Comment by Aidaho12** [comment]
Hello,

yes, there are not utf-8 characters
