### ISSUE TITLE
error while generating map

### ISSUE THREAD

**Issue by bes1967** [Aidaho12/haproxy-wi#267]
Hi, I just started using HAProxy-WI. It's quite interesting, thank you for this kind of software.

Since I am new to this program, I am interested in trying different operations. And when creating a map for my HAProxy instance, I got this error:

haproxy-wi draw_networkx_edge_labels() got an unexpected keyword argument 'labels' mv: cannot stat ‘map.png’: No such file or directory

Seems to be the problem with this line of code (in options.py):
nx.draw_networkx_edge_labels(G, pos, label_pos=0.5, font_color="blue", labels=edge_labels, font_size=8)

I'm not a big expert in python, but according to the documentation (https://networkx.org/documentation/stable/reference/generated/networkx.drawing.nx_pylab.draw_networkx_edge_labels.html), the name of the parameter is 'edge_labels', not 'labels'. I've edited my file like this:
nx.draw_networkx_edge_labels(G, pos, label_pos=0.5, font_color="blue", edge_labels=edge_labels, font_size=8)

and everything started working like a charm.

Maybe this will be helpful

**Comment by Aidaho12** [comment]
Hi!

Thank you! I will add it
