### ISSUE TITLE
Ansible Playbook issue 

### ISSUE THREAD

**Issue by hamzajaved12** [Aidaho12/haproxy-wi#272]
Please guide in steps how we can run this repo for ansible playbook for remote host ?

**Comment by hamzajaved12** [comment]
TASK [haproxy : Install HAProxy] **********************************************************************************************************************************************
fatal: [web2]: FAILED! => {"msg": "The field 'environment' has an invalid value, which includes an undefined variable. The error was: 'PROXY' is undefined\n\nThe error appears to be in '/etc/ansible/roles/haproxy/tasks/main.yml': line 79, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install HAProxy\n  ^ here\n"}

this is what I get when I run the haproxy roles in playbook 

- hosts: all
  name: "Install haproxy-wi using Ansible  on Linux"
  roles:
   - haproxy

**Comment by Aidaho12** [comment]
If you use the "All" group then "Admin area" -> Settings, if other then "Servers" -> "Settings"

**Comment by hamzajaved12** [comment]
Frankly speaking, did not get you

**Comment by Aidaho12** [comment]
I written where are proxy settings, what exactly didn't you understand?

**Comment by hamzajaved12** [comment]
see, I have a ubuntu VM and I want to install haproxy-wi on that VM using an ansible role. And I am doing that using your  Ansible role in my playbook simple.

**Comment by Aidaho12** [comment]
Play book works fine, I've just checked it on Ubuntu.

So, check you proxy settings again, and check with what parameters play book runs

**Comment by hamzajaved12** [comment]
I have not used any proxy setting. Can you show me your directory structure for ubuntu playbook ?. I just want to check where I am going wrong

**Comment by Aidaho12** [comment]
it's here https://github.com/Aidaho12/haproxy-wi/blob/master/app/scripts/ansible/roles/haproxy/tasks/main.yml
