### ISSUE TITLE
Unable to add SSH-Credentials

### ISSUE THREAD

**Issue by mithileshjain** [Aidaho12/haproxy-wi#273]
When trying to add SSH Credentials, I get an error in the browser saying "Something wrong, check and try again". They log on the host gives the following error each time I try uploading a SSH private key

AH01215: AttributeError: module 'paramiko.pkey' has no attribute 'load_private_key'

I tried searching around but had no luck so far. Can you please help figure out this issue?

Thanks in Advance

**Comment by Aidaho12** [comment]
It looks like you have paramiko instead of paramiko-ng

**Comment by mithileshjain** [comment]
I checked the installed python packages on the host and I seem to have both installed,

# pip3 list | grep paramiko
paramiko               2.7.2
paramiko-ng            2.8.4

So, just a background on this (may help in better understanding), I installed HAProxy-wi and did not make any changes to any py scripts. The UI loads fine but gives me this error when trying to add SSH credentials. Also, I checked the options,py script it is complaining about and it has the following line

import paramiko

and the full error is as follows,

AH01215: Traceback (most recent call last):, referer: https://***/app/users.py
AH01215:   File "/var/www/haproxy-wi/app/options.py", line 1792, in <module>, referer: https://***/app/users.py
AH01215:     key = paramiko.pkey.load_private_key(form.getvalue('ssh_cert')), referer: https://***/app/users.py
AH01215: AttributeError: module 'paramiko.pkey' has no attribute 'load_private_key', referer: https://***/app/users.py

Should both packages not be installed? or did I get the old version installed which has an old options.py?

**Comment by Aidaho12** [comment]
You should delete paramiko
