### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by hobojoe720** [Aidaho12/haproxy-wi#28]
Having followed the install instructions, (they should state that Python3 is required, or install it).

At the end of the installation the following error is received:

```
Traceback (most recent call last):
  File "./update_db.py", line 3, in <module>
    import create_db
  File "/var/www/haproxy-wi/app/create_db.py", line 6, in <module>
    import funct
  File "/var/www/haproxy-wi/app/funct.py", line 4, in <module>
    import paramiko
  File "/var/www/haproxy-wi/app/paramiko/__init__.py", line 22, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/var/www/haproxy-wi/app/paramiko/transport.py", line 57, in <module>
    from paramiko.ed25519key import Ed25519Key
  File "/var/www/haproxy-wi/app/paramiko/ed25519key.py", line 17, in <module>
    import bcrypt
  File "/var/www/haproxy-wi/app/bcrypt/__init__.py", line 25, in <module>
    from bcrypt import _bcrypt
ImportError: /var/www/haproxy-wi/app/bcrypt/_bcrypt.so: undefined symbol: PyInt_FromLong
```

OS: Ubuntu 16.04
Python Version: Python 3.5.2
Web Server: Apache2
Database selected: SQLite or MySQL

**Comment by Aidaho12** [comment]
Install script tries install python34

Sometimes it happens that the python does not see modules... I do not know why this happens... Try use clean Linux install

**Comment by hobojoe720** [comment]
Its one of the modules installed as part of the install script. I updated pip3, and reinstalled it and its gone past that and gives a similar issue with "cffi" now

**Comment by Aidaho12** [comment]
Show please all log
--
Отправлено из Mail.Ru для Android четверг, 09 августа 2018г., 17:46 +06:00 от hobojoe720  notifications@github.com :

**Comment by hobojoe720** [comment]
Found the cause. And its just an update to the install instructions:
```
$ sudo apt-get install -y python3 python3-dev
$ sudo apt-get install -y python3-pip
$ sudo apt-get install -y libssl-dev libffi-dev
$ sudo -H pip3 install --upgrade pip
```
Then you can carry on with the instructions as you have them. The important bits were to meet the requirements for bcrypt, cffi and cryptography. As well as have pip3 at the latest version before installing.

**Comment by Aidaho12** [comment]
Ok. thank you.
 I will edit install script
