### ISSUE TITLE
Unable to login - Internal Server Error

### ISSUE THREAD

**Issue by hobojoe720** [Aidaho12/haproxy-wi#29]
OS: Ubuntu 16.04
Python: 3.5.2
Webserver: Apache2

```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
```

I have been hunting to find where the issue lay, authentication is working (it is very insecure). However once logged in I get Internal Server error when going to the redirected url: "/login.py?login=admin&pass=admin"
Apache2 logs have no records for this at all.

If I run this from python and set the username and password in the code, I get the following:
```
/var/www/haproxy-wi/app$ python3 login.py
Set-Cookie: uuid=e3d0c66c-2571-479f-aaf4-64e1b850f097; expires=Tue, 14 Aug 2018 14:05:34 GMT; Path=/app/
Content-type: text/html

ok
```

Bit stumped as to where to go next

**Comment by Aidaho12** [comment]
Yes, it's insecure, but apache dont wont work with post method, couse ajax form used.
Login page dont redirect you with login and pass uri, its ajax method. At your browser javascript enabled?
--
Отправлено из Mail.Ru для Android четверг, 09 августа 2018г., 20:06 +06:00 от hobojoe720  notifications@github.com :

**Comment by hobojoe720** [comment]
I have tried Chrome, Firefox and Internet Explorer.
I have checked within Chrome and JavaScript is enabled.

**Comment by Aidaho12** [comment]
I just made a fresh install, it works. Check to see if you do not block downloading the jqury from their site and try running the web inspector and see if there are any errors js

**Comment by hobojoe720** [comment]
This is a fresh server, new install of Ubuntu 16.0.4, install Apache2, install Python3, download and install the app. 

Will check to see if there are any errors in the browser

**Comment by Aidaho12** [comment]
Keep me informed :)

**Comment by hobojoe720** [comment]
Ok, there is a permission somewhere thats the issue. I got annoyed and set the whole directory to 777 and it works.

**Comment by Aidaho12** [comment]
How everything just turned out :) But apache must log this error...

How to use, please leave your comments, what you liked / did not like and generally

**Comment by Aidaho12** [comment]
And added sudo for chmod special for Ubuntu )
