### ISSUE TITLE
How can I use this project?

### ISSUE THREAD

**Issue by Sad-polar-bear** [Aidaho12/haproxy-wi#3]
Hi,
    I am Chinese user. I am a pythoner and I searching for haproxy web manager platform.I already download your project.But,how can I start the project?Other question,I run the command "python create_db.py" return is 
"DB already exists, try update
An error occurred: no such table: servers
An error occurred: no such table: servers".How can I do for this?
                                                                                                                                               Thanks for you.

**Comment by Aidaho12** [comment]
Hi

In the previous version, there was an error while creating the database. Download today's update, where the database is created automatically the first time you log in.

**Comment by Sad-polar-bear** [comment]
Hi,
    I already downloaded the latest code. I always use python by django or tornado as web frame.I don't know how to running your project.Can you tell me which script startup program should I run？
                                                                                                                                                                                                                                                                         Thank You

**Comment by Aidaho12** [comment]
You have configured a virtual host with fastCGI support? like this:

# cat /etc/httpd/conf.d/haproxy-wi.conf 
<VirtualHost *:8000>
        ServerName haproxy-wi
        ErrorLog /var/log/httpd/haproxy-wi.error.log
        CustomLog /var/log/httpd/haproxy-wi.access.log combined

        DocumentRoot /var/www/haproxy-wi
        ScriptAlias /cgi-bin/ "/var/www/haproxy-wi/cgi-bin/"

        <Directory /var/www/haproxy-wi>
                Options +ExecCGI
                AddHandler cgi-script .py
                Order deny,allow
                Allow from all
        </Directory>
</VirtualHost>

**Comment by Sad-polar-bear** [comment]
I am sorry to that my english is poor,but I like python.So, I will learning for each other who's python is well.Thanks for you replay me, thank you very much!

**Comment by Aidaho12** [comment]
You are welcome. Did you manage to run?

**Comment by Sad-polar-bear** [comment]
I know what you have described.I haven't studied fastcgi yet,but I know the CGI principle.If I have any If I have anything else, I'll ask you again.Do you have weChat?

**Comment by Aidaho12** [comment]
Unfortunately no. There are: fb, whatsapp, telegram, skype.

Try run this in folder /var/www/haproxy-wi:
```
#!/usr/bin/env python3
import os, sys 
from configparser import ConfigParser, ExtendedInterpolation

path_config = "/var/www/haproxy-wi/cgi-bin/haproxy-webintarface.config"
config = ConfigParser(interpolation=ExtendedInterpolation())
config.read(path_config)
log_path = config.get('main', 'log_path')
fullpath = config.get('main', 'fullpath')

from http.server import HTTPServer, CGIHTTPRequestHandler

webdir = fullpath
os.chdir(webdir)
server_address = (0.0.0.0, 8000)
httpd = HTTPServer(server_address, CGIHTTPRequestHandler)
httpd.serve_forever()

```

**Comment by Sad-polar-bear** [comment]
I did it in your way.But there are some mistakes：
[root@localhost haproxy-wi]# cat run.py 
#!/usr/bin/env python3
import os, sys 
from configparser import ConfigParser, ExtendedInterpolation

path_config = "/var/www/haproxy-wi/cgi-bin/haproxy-webintarface.config"
config = ConfigParser(interpolation=ExtendedInterpolation())
config.read(path_config)
log_path = config.get('main', 'log_path')
fullpath = config.get('main', 'fullpath')

from http.server import HTTPServer, CGIHTTPRequestHandler

webdir = fullpath
os.chdir(webdir)
server_address = ('0.0.0.0', 8000)
httpd = HTTPServer(server_address, CGIHTTPRequestHandler)
httpd.serve_forever()
[root@localhost haproxy-wi]# python3.5 run.py 
192.168.3.2 - - [23/Apr/2018 22:52:32] "GET /cgi-bin/overview.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/configparser.py", line 1135, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/haproxy-wi/cgi-bin/overview.py", line 4, in <module>
    import funct
  File "/var/www/haproxy-wi/cgi-bin/funct.py", line 17, in <module>
    fullpath = config.get('main', 'fullpath')
  File "/usr/local/lib/python3.5/configparser.py", line 778, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.5/configparser.py", line 1138, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'main'
192.168.3.2 - - [23/Apr/2018 22:52:33] CGI script exit status 0x100

**Comment by Aidaho12** [comment]
you unzipped all the files to the folder "/var/www/haproxy-wi"?

Please show "tree /var/www/haproxy-wi/"

And edit in start script this string:
server_address = ('0.0.0.0', 8001)

**Comment by Sad-polar-bear** [comment]
yes,I unzip all the files to the folder "/var/www/haproxy-wi"

this is my command return:
[root@localhost www]# tree /var/www/haproxy-wi/
/var/www/haproxy-wi/
├── cgi-bin
│   ├── add.py
│   ├── config.py
│   ├── configshow.py
│   ├── configver.py
│   ├── create_db.py
│   ├── delver.py
│   ├── diff.py
│   ├── edit.py
│   ├── funct.py
│   ├── hap_config
│   │   └── 172.28.5.5.cfg
│   ├── haproxy-webintarface.config
│   ├── login.py
│   ├── logs.py
│   ├── map.py
│   ├── options.py
│   ├── overview.py
│   ├── ovw.py
│   ├── __pycache__
│   │   └── sql.cpython-35.pyc
│   ├── settings.py
│   ├── sql.py
│   ├── users.py
│   ├── viewlogs.py
│   └── viewsttats.py
├── CONTRIBUTING.md
├── image
│   ├── haproxy-wi-add-listen.jpeg
│   ├── haproxy-wi-admin-area.jpeg
│   ├── haproxy-wi-compare.jpeg
│   ├── haproxy-wi-config-edit.jpeg
│   ├── haproxy-wi-config-show.jpeg
│   ├── haproxy-wi-logs.jpeg
│   ├── haproxy-wi-map.jpeg
│   ├── haproxy-wi-overview.jpeg
│   ├── haproxy-wi-runtime.jpeg
│   ├── haproxy-wi-statistics.jpeg
│   └── pic
│       ├── compare.png
│       ├── edit.png
│       ├── favicon.ico
│       ├── map.png
│       ├── show.png
│       ├── start.png
│       ├── stop.png
│       └── update.png
├── inc
│   ├── awesome.css
│   ├── configshow.js
│   ├── fa-solid.min.js
│   ├── fontawesome.min.js
│   ├── js-cookie.js
│   ├── nprogress.css
│   ├── nprogress.js
│   ├── script.js
│   ├── style.css
│   ├── usersdop.js
│   ├── users.js
│   └── vertical_scrol
│       ├── custom_scrollbar.css
│       └── custom_scrollbar.min.js
├── index.html
├── LICENSE
├── log
│   └── config_edit.log
├── README.md
├── requirements.txt
└── run.py

8 directories, 61 files
[root@localhost www]# 


[root@localhost haproxy-wi]# cat run.py 
#!/usr/bin/env python3
import os, sys 
from configparser import ConfigParser, ExtendedInterpolation

path_config = "/var/www/haproxy-wi/cgi-bin/haproxy-webintarface.config"
config = ConfigParser(interpolation=ExtendedInterpolation())
config.read(path_config)
log_path = config.get('main', 'log_path')
fullpath = config.get('main', 'fullpath')

from http.server import HTTPServer, CGIHTTPRequestHandler

webdir = fullpath
os.chdir(webdir)
#server_address = ('0.0.0.0', 8000)
server_address = ('0.0.0.0', 8001)
httpd = HTTPServer(server_address, CGIHTTPRequestHandler)
httpd.serve_forever()
[root@localhost haproxy-wi]#

**Comment by Sad-polar-bear** [comment]
Now,Still make a mistake：
[root@localhost haproxy-wi]# python3.5 run.py 
192.168.3.2 - - [23/Apr/2018 23:12:01] "GET / HTTP/1.1" 200 -
192.168.3.2 - - [23/Apr/2018 23:12:01] "GET /inc/style.css HTTP/1.1" 200 -
192.168.3.2 - - [23/Apr/2018 23:12:01] "GET /cgi-bin/overview.py HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/configparser.py", line 1135, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/haproxy-wi/cgi-bin/overview.py", line 4, in <module>
    import funct
  File "/var/www/haproxy-wi/cgi-bin/funct.py", line 17, in <module>
    fullpath = config.get('main', 'fullpath')
  File "/usr/local/lib/python3.5/configparser.py", line 778, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.5/configparser.py", line 1138, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'main'
192.168.3.2 - - [23/Apr/2018 23:12:01] CGI script exit status 0x100
192.168.3.2 - - [23/Apr/2018 23:12:01] code 404, message File not found
192.168.3.2 - - [23/Apr/2018 23:12:01] "GET /favicon.ico HTTP/1.1" 404 -
192.168.3.2 - - [23/Apr/2018 23:12:01] code 404, message File not found
192.168.3.2 - - [23/Apr/2018 23:12:01] "GET /favicon.ico HTTP/1.1" 404 -
192.168.3.2 - - [23/Apr/2018 23:12:01] code 404, message File not found
192.168.3.2 - - [23/Apr/2018 23:12:01] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by Aidaho12** [comment]
Hm.... strange, everything is in place, but for some reason the config does not see it. Okay, then we'll remove it from the startup script, it's there, in principle, not particularly needed. Do this:
```
#!/usr/bin/env python3
import os, sys 
from http.server import HTTPServer, CGIHTTPRequestHandler

webdir = /var/www/haproxy-wi/cgi-bin
os.chdir(webdir)
server_address = ('0.0.0.0', 8001)
httpd = HTTPServer(server_address, CGIHTTPRequestHandler)
httpd.serve_forever()
```

But best way use Apache, this script only fow test, because he work slowly :(

**Comment by Sad-polar-bear** [comment]
There are some new mistakes.Browser show that:Error response
Error code: 404

Message: No such CGI script ('/cgi-bin/overview.py').

Error code explanation: HTTPStatus.NOT_FOUND - Nothing matches the given URI.


And linux host show:
[root@localhost haproxy-wi]# python3.5 run.py 
192.168.3.2 - - [23/Apr/2018 23:25:33] code 404, message No such CGI script ('/cgi-bin/overview.py')
192.168.3.2 - - [23/Apr/2018 23:25:33] "GET /cgi-bin/overview.py HTTP/1.1" 404 -

**Comment by Sad-polar-bear** [comment]
[root@localhost www]# grep -rn "/cgi-bin/overview.py" .
匹配到二进制文件 ./haproxy-wi-master.zip
./haproxy-wi/cgi-bin/funct.py:163:						'<li><a href=/cgi-bin/overview.py title="Server and service status" class="overview-link head-submenu">Overview</a> </li>'
./haproxy-wi/index.html:9:<meta http-equiv="refresh" content="0; url=/cgi-bin/overview.py">
[root@localhost www]# 

Do I need to modify the parameters here？

**Comment by Aidaho12** [comment]
Work for me now:
```
cd /var/www/haproxy-wi/
cp cgi-bin/haproxy-webintarface.config .
cp cgi-bin/haproxy-wi.db .
```
And in run script edit webdir:
```
webdir = '/var/www/haproxy-wi/'
```

**Comment by Sad-polar-bear** [comment]
It worked！Why not separate the front and back ends for your project?
thank you very much indeed

**Comment by Aidaho12** [comment]
I'm glad that you started! Write please after the tests, as you. What was pleasant, that is not present. Need to collect feedback)

About separation:
I tried, but after a day of studying the Flask, I realized that it was too difficult for me. Maybe later, so long as it works.

**Comment by Sad-polar-bear** [comment]
It's my pleasure.I already give you a star.My moto is: everything is possible.I maybe write a new code in django or tornado.

**Comment by Aidaho12** [comment]
Thank you )
