### ISSUE TITLE
Login Details

### ISSUE THREAD

**Issue by afaqbabar** [Aidaho12/haproxy-wi#32]
Hello, I want to to ask if you can provide us with login details. After running install.sh, i select SQLite option, but after then, I cannot login using 'admin' username and 'admin' password.
Thanks

**Comment by Aidaho12** [comment]
Hi, show me apache error log

**Comment by afaqbabar** [comment]
![bildschirmfoto vom 2018-08-14 17-30-36](https://user-images.githubusercontent.com/14087105/44101744-68661400-9fe8-11e8-9c7f-9957eb44b003.png)
when I login, I do not see any error message as seen in the attached picture. all of the .py files have + bit set as seen below:
`root@ubuntu-test-server-a:/var/www/haproxy-wi/app# ls -la
insgesamt 268
drwxr-xr-x 7 apache apache  4096 Aug 14 16:25 .
drwxr-xr-x 9 apache apache  4096 Aug 14 16:14 ..
-rwxr-xr-x 1 apache apache  5991 Aug 14 16:08 add.py
-rwxr-xr-x 1 apache apache  1682 Aug 14 16:08 blacklist.py
drwxr-xr-x 2 apache apache  4096 Aug 14 16:14 certs
-rwxr-xr-x 1 apache apache  2524 Aug 14 16:08 config.py
-rwxr-xr-x 1 apache apache   969 Aug 14 16:08 configshow.py
-rwxr-xr-x 1 apache apache  2069 Aug 14 16:08 configver.py
-rwxr-xr-x 1 apache apache 19570 Aug 14 16:08 create_db.py
-rwxr-xr-x 1 apache apache  1984 Aug 14 16:08 delver.py
-rwxr-xr-x 1 apache apache   870 Aug 14 16:08 diff.py
-rwxr-xr-x 1 apache apache  1070 Aug 14 16:08 edit.py
-rwxr-xr-x 1 apache apache 13770 Aug 14 16:08 funct.py
-rw-r--r-- 1 apache apache   504 Aug 14 16:14 haproxy-webintarface.config
-rw-r--r-- 1 apache apache 27648 Aug 14 16:14 haproxy-wi.db
-rw-r--r-- 1 apache apache  2054 Aug 14 16:08 haproxy-wi.db.sql
-rwxr-xr-x 1 apache apache   901 Aug 14 16:08 ha.py
-rwxr-xr-x 1 apache apache   874 Aug 14 16:08 ihap.py
-rwxr-xr-x 1 apache apache  2500 Aug 14 16:08 keepalivedconfig.py
-rwxr-xr-x 1 apache apache  1682 Aug 14 16:08 lists.py
-rwxr-xr-x 1 apache apache  2930 Aug 14 16:08 login.py
-rwxr-xr-x 1 apache apache  1187 Aug 14 16:08 logs.py
-rwxr-xr-x 1 apache apache   853 Aug 14 16:08 map.py
-rwxr-xr-x 1 apache apache   875 Aug 14 16:08 metrics.py
-rwxr-xr-x 1 apache apache 18505 Aug 14 16:08 options.py
-rwxr-xr-x 1 apache apache  1583 Aug 14 16:08 overview.py
-rwxr-xr-x 1 apache apache  5454 Aug 14 16:08 ovw.py
drwxr-xr-x 2 apache apache  4096 Aug 14 16:18 __pycache__
drwxr-xr-x 2 apache apache  4096 Aug 14 16:08 scripts
-rwxr-xr-x 1 apache apache  1284 Aug 14 16:08 servers.py
-rwxr-xr-x 1 apache apache   798 Aug 14 16:08 settings.py
-rwxr-xr-x 1 apache apache 38658 Aug 14 16:08 sql.py
drwxr-xr-x 3 apache apache  4096 Aug 14 16:08 templates
drwxr-xr-x 2 apache apache  4096 Aug 14 16:08 tools
-rwxr-xr-x 1 apache apache   337 Aug 14 16:08 update_db.py
-rwxr-xr-x 1 apache apache  1138 Aug 14 16:08 users.py
-rwxr-xr-x 1 apache apache  2322 Aug 14 16:08 viewlogs.py
-rwxr-xr-x 1 apache apache  1126 Aug 14 16:08 viewsttats.py`

**Comment by Aidaho12** [comment]
Javascript enabled? Jquery src loaded?

**Comment by afaqbabar** [comment]
Yes, java script is enabled ion Firefox. 
Can you login to my test machine using team viewer? If yes, I can send you access details through email.
Thanks

**Comment by Aidaho12** [comment]
Yes, let's help, but it would be great if you supported the project on the patron, at will

mail buffoon2001@mail.ru

**Comment by louisyssel** [comment]
I have a similar problem, however, I use external MySQL database. Everything works fine during installation. When I try initial login, I get an error: Can not find "session_ttl" parametr. Check into settings, "main" section.

There is no such parameter in haproxy-webintarface.config. Or should it be somewhere else.

The web page displays, and I am able to try the login, and I try admin/admin, but the login page justs loads again.

**Comment by Aidaho12** [comment]
Try run update_db.py

**Comment by louisyssel** [comment]
This is the ourput when I run update_db.py

<div class="alert alert-danger">
An error occurred: 1062 (23000): Duplicate entry 'admin' for key 'username'
</div>
An error occurred: 1060 (42S21): Duplicate column name 'type_ip'
An error occurred: 1060 (42S21): Duplicate column name 'enable'
An error occurred: 1060 (42S21): Duplicate column name 'master'
DB was update to 2.4 <br />
An error occurred: 1060 (42S21): Duplicate column name 'exp'
An error occurred: 1060 (42S21): Duplicate column name 'cred'
An error occurred: 1060 (42S21): Duplicate column name 'groups'
An error occurred: 1060 (42S21): Duplicate column name 'alert'
An error occurred: 1060 (42S21): Duplicate column name 'metrics'
An error occurred: 1062 (23000): Duplicate entry 'lists_path' for key 'param'
An error occurred: 1060 (42S21): Duplicate column name 'section'

**Comment by Aidaho12** [comment]
Yes, it,s ok)
--
Отправлено из Mail.Ru для Android среда, 15 августа 2018г., 20:58 +06:00 от Louis Yssel  notifications@github.com :

**Comment by louisyssel** [comment]
Nothing changed, still getting the same problem

**Comment by Aidaho12** [comment]
What version haproxy-wi?

**Comment by louisyssel** [comment]
The latest one from today, branch Master

**Comment by Aidaho12** [comment]
Ok, it's bug with mysql update table, now try fix

**Comment by Aidaho12** [comment]
Ok, done. Update haproxy-wi, after update db, and try again

**Comment by Aidaho12** [comment]
Now work?

**Comment by louisyssel** [comment]
OK, seems to be working now, thanks a lot, I will contact you again if I have any problems.

Regards,

**Comment by Aidaho12** [comment]
Hello, how did it come about?


>Вторник, 14 августа 2018, 21:46 +06:00 от afaqbabar <notifications@github.com>:
>
>Yes, java script is enabled ion Firefox.
>Can you login to my test machine using team viewer? If yes, I can send you access details through email.
>Thanks
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Павел.
