### ISSUE TITLE
Type Error 

### ISSUE THREAD

**Issue by atriumcarceri** [Aidaho12/haproxy-wi#37]
Hallo!
Just Installed and get type error

`[cgi:error] [pid 14009:tid 140102521034496] [client 10.10.10.10:60684] AH01215: Traceback (most recent call last):: /var/www/haproxy-wi/app/login.py, referer: http://haproxyserver:8080/app/login.py?ref=/app/overview.py`
`[cgi:error] [pid 14009:tid 140102521034496] [client 10.10.10.10:60684] AH01215:   File "/var/www/haproxy-wi/app/login.py", line 68, in <module>: /var/www/haproxy-wi/app/login.py, referer: http://haproxyserver:8080/app/login.py?ref=/app/overview.py`
`[cgi:error] [pid 14009:tid 140102521034496] [client 10.10.10.10:60684] AH01215:     if login in users[1] and password == users[3]:: /var/www/haproxy-wi/app/login.py, referer: http://haproxyserver:8080/app/login.py?ref=/app/overview.py`
`[Fri Aug 31 17:03:02.544562 2018] [cgi:error] [pid 14009:tid 140102521034496] [client 10.10.10.10:60684] AH01215: TypeError: a bytes-like object is required, not 'str': /var/www/haproxy-wi/app/login.py, referer: http://haproxyserver:8080/app/login.py?ref=/app/overview.py`
`[cgi:error] [pid 14009:tid 140102521034496] [client 10.10.10.10:60684] End of script output before headers: login.py, referer: http://haproxyserver:8080/app/login.py?ref=/app/overview.py`

**Comment by Aidaho12** [comment]
Hi,

check whether the database was created properly and the table users is have defaults logins

**Comment by atriumcarceri** [comment]
i had only error when install.sh, near
`insert into cred('enable','username','password') values ('1', 'root','password');`
in haproxy-wi.db.sql file, so i just create it manually, changed it to 
`insert into cred(enable,username,password) values ('1', 'root','password');`
and error gone

**Comment by Aidaho12** [comment]
ou ) I'm forgot update that file ) thank you

Share your impressions after using

**Comment by atriumcarceri** [comment]
same error, 500 http://server:8080/app/login.py?login=admin&pass=admin
and in error log

```
[Mon Sep 03 15:43:48.789879 2018] [cgi:error] [pid 17038:tid 140568533346048] [client 10.10.10.10:54826] AH01215: Traceback (most recent call last):: /var/www/haproxy-wi/app/login.py, referer: http://server:8080/app/login.py?ref=/app/overview.py

[Mon Sep 03 15:43:48.789974 2018] [cgi:error] [pid 17038:tid 140568533346048] [client 10.10.10.10:54826] AH01215:   File "/var/www/haproxy-wi/app/login.py", line 68, in <module>: /var/www/haproxy-wi/app/login.py, referer: http://server:8080/app/login.py?ref=/app/overview.py

[Mon Sep 03 15:43:48.789997 2018] [cgi:error] [pid 17038:tid 140568533346048] [client 10.10.10.10:54826] AH01215:     if login in users[1] and password == users[3]:: /var/www/haproxy-wi/app/login.py, referer: http://server:8080/app/login.py?ref=/app/overview.py

[Mon Sep 03 15:43:48.790024 2018] [cgi:error] [pid 17038:tid 140568533346048] [client 10.10.10.10:54826] AH01215: TypeError: a bytes-like object is required, not 'str': /var/www/haproxy-wi/app/login.py, referer: http://server:8080/app/login.py?ref=/app/overview.py
[Mon Sep 03 15:43:48.821473 2018] [cgi:error] [pid 17038:tid 140568533346048] [client 10.10.10.10:54826] End of script output before headers: login.py, referer: http://server:8080/app/login.py?ref=/app/overview.py
```

**Comment by Aidaho12** [comment]
you solved this problem and again?

**Comment by atriumcarceri** [comment]
Nope, i did not. I mean, that error on installing gone, but 500 still. so i just did clean install.sh, you have errors in create_db.py

```
<div class="alert alert-danger">
An error occurred: 1062 (23000): Duplicate entry 'admin' for key 'username'
</div>
An error occurred: 1062 (23000): Duplicate entry 'time_zone' for key 'param'
An error occurred: 1060 (42S21): Duplicate column name 'port'
```
but w\e, i executed haproxy-wi.db.sql (haproxy-wi.db.sql:5 you forgot a comma), its done successful, but 
 when i tryin to login i still get 500 error.

**Comment by atriumcarceri** [comment]
![screenshot_1](https://user-images.githubusercontent.com/11857996/44989701-596c6a80-af97-11e8-989b-cfcd1abecf04.png)

**Comment by Aidaho12** [comment]
I'm updated repo, try update and recreate DB

**Comment by atriumcarceri** [comment]
Same. Maybe its problem in version python? I have
(Python 2.7.13 (default, Nov 24 2017, 17:33:09))

https://ru.stackoverflow.com/questions/466658/Ошибка-при-подключении-сокета-к-серверу-a-bytes-like-object-is-required-not-s

**Comment by Aidaho12** [comment]
Да, в этом проблема, нужен питон от 3.4 )

Но установочный скрипт должен поставить все... попробуй набрать python3

>Понедельник,  3 сентября 2018, 20:28 +06:00 от Roman Havrilyuk <notifications@github.com>:
>
>Same. Maybe its problem in version python? I have
>(Python 2.7.13 (default, Nov 24 2017, 17:33:09))
>https://ru.stackoverflow.com/questions/466658/Ошибка-при-подключении-сокета-к-серверу-a-bytes-like-object-is-required-not-s
>—
>You are receiving this because you modified the open/close state.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Павел.

**Comment by atriumcarceri** [comment]
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
На самой базе селекты выполняются нормально, мне кажется проблема не в бд

**Comment by Aidaho12** [comment]
Кажется нашел в чем причина, посмотри сколько полей в таблице uuid? Если два то сделай
```
ALTER TABLE `uuid` ADD COLUMN `exp` DATETIME default '0000-00-00 00:00:00';
```

**Comment by Aidaho12** [comment]
ну как, помогло?

**Comment by Aidaho12** [comment]
A js включаен, jqury нормально подгружается?

**Comment by atriumcarceri** [comment]
в итоге поставил скуль и приложение на одном сервере, полет нормальный.

**Comment by Aidaho12** [comment]
Забавно....
Как потестируете, напишите свои ощущения, что понравилось, что нет?
--
Отправлено из Mail.Ru для Android среда, 05 сентября 2018г., 17:07 +06:00 от Roman Havrilyuk  notifications@github.com :
