### ISSUE TITLE
error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips error

### ISSUE THREAD

**Issue by cankaya07** [Aidaho12/haproxy-wi#41]
i am getting an error while application trying to connect server or localhost via ssh 

error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips

here is the output of paramiko. Probably caused of the cryptolibs. how can i verify it ?

>>> import paramiko
>>> print paramiko.__version__
2.4.2
>>>

**Comment by Aidaho12** [comment]
Check enabled FIPS:
```
sysctl crypto.fips_enabled
```
If yes, you must disabled it

**Comment by Aidaho12** [comment]
I do not know the solution, if you find it, let me know

**Comment by Aidaho12** [comment]
By the way: try use password not ssh keys

**Comment by monder1385** [comment]
Tried password but still the same error.
(error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips)

**Comment by Aidaho12** [comment]
Try update paramiko:
```
pip3 install -e git+https://github.com/ioparaskev/paramiko#egg=paramiko
```

**Comment by monder1385** [comment]
Yes, this worked! thanks

**Comment by cankaya07** [comment]
brilliant solution. It worked me too. Thank you.
