### ISSUE TITLE
why am i getting these errors ?

### ISSUE THREAD

**Issue by cankaya07** [Aidaho12/haproxy-wi#43]
[Wed Sep 26 14:34:48.017386 2018] [cgi:error] [pid 20289] [client 10.0.100.100:50479] AH01215: Traceback (most recent call last):, referer: http://10.0.20.200:8080/app/configshow.py
[Wed Sep 26 14:34:48.017607 2018] [cgi:error] [pid 20289] [client 10.0.100.100:50479] AH01215:   File "/var/www/haproxy-wi/app/options.py", line 335, in <module>, referer: http://10.0.20.200:8080/app/configshow.py
[Wed Sep 26 14:34:48.017942 2018] [cgi:error] [pid 20289] [client 10.0.100.100:50479] AH01215:     template = template.render(conf=conf, view=form.getvalue('view'), serv=serv, configver=form.getvalue('configver'))\t\t\t\t\t\t\t\t\t\t\t, referer: http://10.0.20.200:8080/app/configshow.py
[Wed Sep 26 14:34:48.018047 2018] [cgi:error] [pid 20289] [client 10.0.100.100:50479] AH01215: NameError: name 'conf' is not defined, referer: http://10.0.20.200:8080/app/configshow.py

**Comment by Aidaho12** [comment]
This error because you can't connect via SSH, and get haproxy config
