### ISSUE TITLE
Error on adding new ssh server

### ISSUE THREAD

**Issue by hackathorr** [Aidaho12/haproxy-wi#46]
Getting the error, when trying to add a new ssh server with ssh credential: 
**All fields must be completed**

<img width="1232" alt="add-server" src="https://user-images.githubusercontent.com/43058952/46201562-1e5d1d00-c332-11e8-879f-c44339353020.png">

Please suggest some solution.

**Comment by Aidaho12** [comment]
Show me what you send to the servers? I meen use something like firebug

**Comment by monder1385** [comment]
you should add servers from Admin Area,  you can try it.

**Comment by hackathorr** [comment]
I tried that. In admin area I'm not even able to click the submit button.

**Comment by Aidaho12** [comment]
Yes, if your user is't have any group, add servers must be from admin area, there should be notice on the page about this

**Comment by Aidaho12** [comment]
>I tried that. In admin area I'm not even able to click the submit button.
Printscreen please

**Comment by hackathorr** [comment]
[https://www.dropbox.com/s/wjkbnuqz0d3ty4i/video-haproxy-wi.mp4?dl=0](Watch this clip)

**Comment by Aidaho12** [comment]
Ou, your screen to small, funny bug ) 

Ok, try set for your user group, and try add from "Servers" section, Soon I update repo, and will fix this bug

**Comment by Aidaho12** [comment]
Fixed, update and try

**Comment by abhishekranjanyml** [comment]
I am able to add a server but am not able to see it , when i go to installations tab i don't see it. I have created a new group and also tried with ALL as groups.
<img width="1428" alt="haproxy-wi 2" src="https://user-images.githubusercontent.com/43058934/46262755-4e1f4700-c523-11e8-9862-ccda15a9669d.png">
<img width="1392" alt="haproxy-wi-1" src="https://user-images.githubusercontent.com/43058934/46262756-4e1f4700-c523-11e8-9a3f-c134bbfc157e.png">

**Comment by Aidaho12** [comment]
At another pages it have? And show me apache error log
--
Отправлено из Mail.Ru для Android понедельник, 01 октября 2018г., 03:10 +06:00 от abhishekranjanyml  notifications@github.com :
