### ISSUE TITLE
Left navigation not working on tabbed pages

### ISSUE THREAD

**Issue by Khartir** [Aidaho12/haproxy-wi#47]
The second level of the left navigation isn't working on tabbed pages, like "Admin Area" or "Servers".
It works the first time, to switch to that page and the correct tab, but if you try to change the tab while staying on the same page nothing happens.

**Comment by Aidaho12** [comment]
For me work fine. You can navigate into the tabs use arrow button: left, right

**Comment by Khartir** [comment]
Just to clarify what I mean: I cannot change from Admin area/Users to Admin Area/Groups using the left navigation.
I can switch using the tabs or the arrow buttons.
I can also switch to Servers/Servers and if I then switch to Admin Area/Groups the correct tab is opened.

**Comment by Aidaho12** [comment]
Aaa... I understand you, but this is a feature of the work JQuery, MB I can do somethings

**Comment by Aidaho12** [comment]
Fixed, update and try
