### ISSUE TITLE
Request: Display error message if SSH-connection to server is not possible

### ISSUE THREAD

**Issue by Khartir** [Aidaho12/haproxy-wi#48]
Currently there is no way to debug if the connection to a server doesn't work. I'm currently testing this with an haproxy server running in a docker container and I think the problem is that haproxy-wi can't connect to the server for some reason. But I'm not sure and there is no way to check.
The only error message I get is when trying to edit the config for the server, then I get the message "'str' object has no attribute 'open_sftp' Can't read import config file". 
It would be nice if there was a "test connection" button or something that shows error messages if the connection to the server doesn't work.

**Comment by Aidaho12** [comment]
At "Overview" page isn't have error when ssh can't connect?

And this function was, when you add server, but I removed it)

**Comment by Khartir** [comment]
I just realized that I get a lot of errors in the current docker container because it is missing python3.5. Maybe that's the problem. I'll check again, when the new container is out.

**Comment by Aidaho12** [comment]
May be, now i build new image with python3.5, try it. Soon will be update
--
Отправлено из Mail.Ru для Android пятница, 28 сентября 2018г., 19:28 +06:00 от Khartir  notifications@github.com :

**Comment by Aidaho12** [comment]
Hi! I was added check SSH connect, updated :)
