### ISSUE TITLE
Site Not Displaying properley when installed on Centos 7 using Auto Installer

### ISSUE THREAD

**Issue by jtoland** [Aidaho12/haproxy-wi#5]
Hello,

When i install your script using the autoinstall method i get the following when visiting the site

#!/usr/bin/env python3
import html
import cgi
import funct
import ovw

funct.head("Overview")
funct.check_config()
funct.check_login()
funct.get_auto_refresh("Overview")	
print("<script>if (cur_url[0] == 'overview.py') { $('#secIntervals').css('display', 'none');}</script>")
print('<script> window.onload = showOverview()</script><div id="ajax"></div>')

funct.footer()

You can see by going to the following link http://92.63.142.243:8080/app/overview.py

This was a fresh install of Centos 7.

**Comment by Aidaho12** [comment]
Can you show me your apahce config? haproxy-wi.conf

**Comment by jtoland** [comment]
Hi here is the conf

<prox-wi.nshub.co.ukVirtualHost *:8080>
        ServerName haprox-wi.nshub.co.uk
        ErrorLog /var/log/httpd/haproxy-wi.error.log
        CustomLog /var/log/httpd/haproxy-wi.access.log combined

        DocumentRoot /var/www/haproxy-wi
        ScriptAlias "/cgi-bin/ "/var/www/haproxy-wi/app/"


        <Directory haproxy-wi>
                Options +ExecCGI
                AddHandler cgi-script .py
                Order deny,allow
                Allow from all
        </Directory>
</VirtualHost>

**Comment by Aidaho12** [comment]
Edit from 
ScriptAlias "/cgi-bin/ 
To 
ScriptAlias /cgi-bin/ 
Resrart apache and try again
Отправлено из Mail.Ru для Android

**Comment by jtoland** [comment]
Hello,

I have changed the config to 

<VirtualHost *:8080>
        ServerName haprox-wi.example.com
        ErrorLog /var/log/httpd/haproxy-wi.error.log
        CustomLog /var/log/httpd/haproxy-wi.access.log combined

        DocumentRoot /var/www/haproxy-wi
        ScriptAlias /cgi-bin/ "/var/www/haproxy-wi/app/"


        <Directory haproxy-wi>
                Options +ExecCGI
                AddHandler cgi-script .py
                Order deny,allow
                Allow from all
        </Directory>
</VirtualHost>


this still does not work

**Comment by Aidaho12** [comment]
Problem was here:
   <Directory haproxy-wi>

Need:
   <Directory /var/www/haproxy-wi/app>

**Comment by jtoland** [comment]
Hello

Thank you for confirming.
