### ISSUE TITLE
package of waf feature

### ISSUE THREAD

**Issue by cankaya07** [Aidaho12/haproxy-wi#52]
Which package are you using for waf features ?

**Comment by Aidaho12** [comment]
Mod security
--
Отправлено из Mail.Ru для Android понедельник, 01 октября 2018г., 12:45 +06:00 от Can KAYA  notifications@github.com :

**Comment by cankaya07** [comment]
thanks

**Comment by cankaya07** [comment]
is there any documentation to follow up related with this waf feature. I installed mod_security package and linked the config file. is there any instruction to do this, I will appreciate it.

**Comment by Aidaho12** [comment]
What for u did that? Waf installer configured all self
About docs: google, i,m do not write any docs
--
Отправлено из Mail.Ru для Android понедельник, 01 октября 2018г., 19:42 +06:00 от Can KAYA  notifications@github.com :

**Comment by cankaya07** [comment]
did you convert as a service waf module under the apache service. I installed ModSecurity it looks working like a submodule under the apache service. i am not able to restart waf service via ssh systemctl ... commands. Thank you for your help and rapid answer 👍
