### ISSUE TITLE
Cannot add server

### ISSUE THREAD

**Issue by tar-xzvff** [Aidaho12/haproxy-wi#53]
I attempted to add a server, but I could not add it due to an error.

I tried to add "All fields must be completed" and it was displayed.

version: v3.2.11
![2018-10-03 17 56 50](https://user-images.githubusercontent.com/18513971/46400657-f7d62200-c735-11e8-80f9-e6171b7da3e7.png)

An error was output even if you input All fields.

**Comment by Aidaho12** [comment]
Your user have group?

**Comment by tar-xzvff** [comment]
Yes, the logged-in user has a group.

**Comment by tar-xzvff** [comment]
It seems that you do not POST the value "newservergroup" from the browser.

![2018-10-03 18 39 42](https://user-images.githubusercontent.com/18513971/46402861-e132c980-c73b-11e8-8fde-85caaf2934da.png)

https://github.com/Aidaho12/haproxy-wi/blob/429e306ce0eed08ea2ed9bb953ffe12d19dab2a7/app/sql.py#L1079

**Comment by Aidaho12** [comment]
I think I understand what the problem is, I will soon correct

**Comment by tar-xzvff** [comment]
Thank you.

When I turned the browser to chrome, "Group" was displayed.
It is not displayed when browser is Safari.

![2018-10-03 19 04 35](https://user-images.githubusercontent.com/18513971/46404265-9ca92d00-c73f-11e8-9f1b-230524a7e372.png)

**Comment by Aidaho12** [comment]
Fixed, update and try

About safari, MB, I didn't check it at safari

**Comment by tar-xzvff** [comment]
I understand.
I confirmed that v3.2.12 works normally.

**Comment by Aidaho12** [comment]
I am pleased to )

**Comment by Aidaho12** [comment]
By the way... new form for add servers is more convenient?

**Comment by tar-xzvff** [comment]
The new form is very nice as the UI is easy to understand and easy to use!

**Comment by Aidaho12** [comment]
It good)
