### ISSUE TITLE
Config file name is misspelled

### ISSUE THREAD

**Issue by beruic** [Aidaho12/haproxy-wi#54]
The config file `haproxy-webintarface.config` should be renamed `haproxy-webinterface.config`.

**Comment by Aidaho12** [comment]
Oh ) Thank you, I will fix it soon

**Comment by Aidaho12** [comment]
Now it called haproxy-wi.cfg

**Comment by beruic** [comment]
I tip my hat to you sir, for choosing a short, yet concise (given the context) name.
