### ISSUE TITLE
Keepalived->Edit Config doesn't show my server

### ISSUE THREAD

**Issue by monder1385** [Aidaho12/haproxy-wi#57]
Hello,
keepalivedconfig.py page doesn't show my server on "choose server" combo. I installed the keepalived and is running on server. No logs on error file.
Any idea?

**Comment by Aidaho12** [comment]
If you didn't set  master-slave you willnt see it
--
Отправлено из Mail.Ru для Android среда, 10 октября 2018г., 19:15 +06:00 от monder1385  notifications@github.com :

**Comment by monder1385** [comment]
thanks for the info...

**Comment by Aidaho12** [comment]
or not convenient?
