### ISSUE TITLE
Installer.sh doesnt work for Ubuntu

### ISSUE THREAD

**Issue by mhammady** [Aidaho12/haproxy-wi#6]
Hello,

I gave this nice GUI a try, but I couldn't run it on Ubuntu server 16.x. The directories are different, and I had to install and use yum tools instead of apt-get.

As a suggestion; can you please create an installer for Ubuntu server?

Thanks
Mohamed

**Comment by Aidaho12** [comment]
Yes, it true, I'm don't use Ubuntu, and don't know this systems.... You can install manual, in readme have man

**Comment by mhammady** [comment]
Thank you for your reply. So what do you use? i can install it on a separate box just for the GUI

**Comment by Aidaho12** [comment]
Centos 7, or Redhat 7

**Comment by mhammady** [comment]
Thank you. I'm not a Linux savvy, so I will try to install it on Centos7 and connect to other HAProxies

**Comment by Aidaho12** [comment]
U will win! )
