### ISSUE TITLE
Some templates are missing

### ISSUE THREAD

**Issue by perdonjp** [Aidaho12/haproxy-wi#63]
The templates metric_out.html is missing and metric_waf.html is also missing. Used the script "install.sh" for this.

**Comment by Aidaho12** [comment]
They are not missing, they are will create, when you enable metrics


>Понедельник, 22 октября 2018, 16:33 +06:00 от JP Perdon <notifications@github.com>:
>
>The templates metric_out.html is missing and metric_waf.html is also missing. Used the script "install.sh" for this.
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Павел.
