### ISSUE TITLE
Feature: Nginx config for haproxy-wi

### ISSUE THREAD

**Issue by mrhackcz** [Aidaho12/haproxy-wi#67]
Hi Aidaho12 !
Can you please add configuration for run haproxy-wi on nginx? :+1:  :)
Thank you

**Comment by Aidaho12** [comment]
Hi! I do not use Nginx, so I can not promise that I will figure it out soon. But I'll try

**Comment by SysadminEU1** [comment]
Nginx is a competitor to Haproxy, I think the author should stay focused on Haproxy.

**Comment by fsuste** [comment]
@SysadminEU1 well, yes and no. This isn't a battle between a better load balancer, but just a need/request for a different web server. I would also like to see this feature since it's my preferred web server of choice.

**Comment by Aidaho12** [comment]
Unfortunately nginx can't fastcgi, only wsgi, therefore maybe it will happened when I will rewrite for wsgi
