### ISSUE TITLE
Request-URI Too Long

### ISSUE THREAD

**Issue by Clero92** [Aidaho12/haproxy-wi#68]
Hello,
when I update the haproxy cfg I get following error:

Request-URI Too Long
The requested URL's length exceeds the capacity limit for this server.
Apache/2.4.25 (Debian) Server at haproxy-wi Port 443

Google said, that the process must be changed to POST from GET. Can you check this out please :) ?

**Comment by mrhackcz** [comment]
Try to increase LimitRequestLine and LimitRequestFieldSize http://httpd.apache.org/docs/2.2/mod/core.html#limitrequestline

**Comment by Aidaho12** [comment]
Yes, POST will be very good, but apache dosn't work with CGI and POST. I don't know why (

**Comment by Clero92** [comment]
Hello,
can you please provide an example?
I have edited /etc/apache2/apache2.conf with

LimitRequestFieldSize 16380
LimitRequestLine 16380
LimitRequestFields 16380

+ restart, but nothing changed.

**Comment by Clero92** [comment]
Ok, fixed it with editing the virtual-host config:

/etc/apache2/sites-available/000-default.conf

<VirtualHost *:443>
[...]
LimitRequestLine 16380
[...]
</VirtualHost>

**Comment by Aidaho12** [comment]
Cool! Thank you

**Comment by Aidaho12** [comment]
And it every times?

**Comment by Clero92** [comment]
Yes, every time I update the haproxy config (with apache config "LimitRequestLine 16380").

**Comment by Aidaho12** [comment]
in error log something have?

I can't reproduce it

**Comment by Clero92** [comment]
[Fri Nov 02 13:56:37.760064 2018] [cgi:error] [pid 26635:tid 140415927326464] [client 10.188.188.150:10886] AH01215: dos2unix: : /var/www/haproxy-wi/app/config.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/config.py?serv=10.188.251.101&open=open
[Fri Nov 02 13:56:37.760212 2018] [cgi:error] [pid 26635:tid 140415927326464] [client 10.188.188.150:10886] AH01215: converting file /var/www/haproxy-wi/configs/hap_config/10.188.251.101-2018-11-02.12:56:37.cfg to Unix format...: /var/www/haproxy-wi/app/config.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/config.py?serv=10.188.251.101&open=open
[Fri Nov 02 13:56:38.468681 2018] [cgi:error] [pid 26635:tid 140415927326464] [client 10.188.188.150:10886] AH01215: dos2unix: : /var/www/haproxy-wi/app/config.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/config.py?serv=10.188.251.101&open=open
[Fri Nov 02 13:56:38.468880 2018] [cgi:error] [pid 26635:tid 140415927326464] [client 10.188.188.150:10886] AH01215: converting file /var/www/haproxy-wi/configs/hap_config/10.188.251.101-2018-11-02.12:56:37.cfg to Unix format...: /var/www/haproxy-wi/app/config.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/config.py?serv=10.188.251.101&open=open

My config has a lenght of 6530 chars, have you tried it with a large config file?

**Comment by Aidaho12** [comment]
Yes, and more:

:!wc -m /etc/haproxy/haproxy.cfg
6542 /etc/haproxy/haproxy.cfg

**Comment by Clero92** [comment]
Maybe server reboot or cookie?
Don't know why, but now it's working perfectly :)
