### ISSUE TITLE
HAProxy CFG disappear if error in CFG

### ISSUE THREAD

**Issue by Clero92** [Aidaho12/haproxy-wi#69]
Hello,
when I change the HAProxy CFG and wrote a wrong syntax, the website said "ok" (green popup), but the CFG is not updated and my changes are gone.

Can you please save the changes before "saving" and check if the CFG is ok? Maybe red window, CFG error, please check CFG.

Thank you :)

**Comment by Aidaho12** [comment]
Check your changes at "Upload" section. And check of a config happens on the server where you change cfg. Couse why HAProxy-WI accept your wrong config you must check at the HAProxy server

**Comment by Clero92** [comment]
1.) edit config with HAPWI - with wrong syntax
2.) save and restart -> "Config ok" popup in green
3.) HAProxy config did not change at HAProxy node
4.) "wrong" config is available in HAPWI @ Versions->Upload but not in HAProxy -> Configs

Ok, now I can edit the wrong config in Upload, thanks :). But can you please add e.g. a red popup with "wrong settings"?

**Comment by Clero92** [comment]
Output is ok:
[ALERT] 305/092720 (29016) : parsing [2018-11-02.07:00:35.cfg:23] : unknown keyword 'd' in 'global' section
[ALERT] 305/092720 (29016) : Error(s) found in configuration file : 2018-11-02.07:00:35.cfg
[ALERT] 305/092720 (29016) : Fatal errors found in configuration.

HAPWI should not activate wrong configs, like now :). I only thought a infobox with "wrong settings" or the error output from this command would be nice.

**Comment by Aidaho12** [comment]
Fixed, update and try

**Comment by Clero92** [comment]
now it works like a charm :) thanks.
