### ISSUE TITLE
Feature: LDAP login?

### ISSUE THREAD

**Issue by Clero92** [Aidaho12/haproxy-wi#70]
Hello,
it would be nice if you can implement an LDAP Login :) (e.g. for Microsoft AD).

Kind regards, Clero

**Comment by Aidaho12** [comment]
Yes, I thinked about it too)

**Comment by Aidaho12** [comment]
Hi! Now have ldap support

**Comment by Clero92** [comment]
Hello, you're working quick :) !

But, it's not working yet in our enviroment :( .

[Thu Nov 08 16:42:01.898581 2018] [cgi:error] [pid 17010:tid 140415726462720] [client 10.188.188.150:22902] AH01215: Traceback (most recent call last):: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:42:01.898686 2018] [cgi:error] [pid 17010:tid 140415726462720] [client 10.188.188.150:22902] AH01215: File "/var/www/haproxy-wi/app/options.py", line 621, in <module>: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:42:01.898701 2018] [cgi:error] [pid 17010:tid 140415726462720] [client 10.188.188.150:22902] AH01215: import ldap: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:42:01.898721 2018] [cgi:error] [pid 17010:tid 140415726462720] [client 10.188.188.150:22902] AH01215: ImportError: No module named 'ldap': /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py

Any ideas?

**Comment by Aidaho12** [comment]
Try: pip3 install python-ldap 
--
Отправлено из Mail.Ru для Android четверг, 08 ноября 2018г., 21:45 +06:00 от Clero92  notifications@github.com :

**Comment by Clero92** [comment]
Yes, got an error.

I had to do:
sudo apt-get install libpq-dev python-dev libxml2-dev libxslt1-dev libldap2-dev libsasl2-dev libffi-dev python3-dev

pip3 install --trusted-host pypi.org --trusted-host files.pythonhosted.org -r /var/www/haproxy-wi/requirements.txt

Now I'm getting this error:
[Thu Nov 08 16:56:17.251531 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: Traceback (most recent call last):: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.251624 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/var/www/haproxy-wi/app/options.py", line 638, in <module>: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.251675 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: result = l.search_s(base, ldap.SCOPE_SUBTREE, criteria, attributes): /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.251733 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 852, in search_s: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.251798 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout): /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.251859 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 846, in search_ext_s: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.251923 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: return self.result(msgid,all=1,timeout=timeout)[1]: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.251984 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 738, in result: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252032 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: resp_type, resp_data, resp_msgid = self.result2(msgid,all,timeout): /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252091 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 742, in result2: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252160 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all,timeout): /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252218 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 749, in result3: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252247 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: resp_ctrl_classes=resp_ctrl_classes: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252305 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 756, in result4: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252374 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop): /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252434 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 329, in _ldap_call: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252467 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: reraise(exc_type, exc_value, exc_traceback): /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252523 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/compat.py", line 44, in reraise: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252539 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: raise exc_value: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252599 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 313, in _ldap_call: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252623 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: result = func(*args,**kwargs): /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252690 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: ldap.REFERRAL: {'info': 'Referral:\\nldap://kar-tel.local/dc=kar-tel,%20dc=local', 'desc': 'Referral'}: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py

**Comment by Aidaho12** [comment]
You are configures ldap connection?
--
Отправлено из Mail.Ru для Android четверг, 08 ноября 2018г., 21:58 +06:00 от Clero92  notifications@github.com :

**Comment by Aidaho12** [comment]
Found some bugs, update and try

**Comment by Clero92** [comment]
Yes.

ldap_enable = 1
ldap_server = [MyLDAPServer_IP]
ldap_port = 389
ldap_user = myLDAPuser@subdomain.domain.de
ldap_password = [PW]
ldap_base = DC=subdomain,DC=domain,DC=de

**Comment by Clero92** [comment]
Now I'm getting "error, user not found".

[Thu Nov 08 16:56:17.251531 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: Traceback (most recent call last):: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.251624 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/var/www/haproxy-wi/app/options.py", line 638, in <module>: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.251675 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: result = l.search_s(base, ldap.SCOPE_SUBTREE, criteria, attributes): /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.251733 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 852, in search_s: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.251798 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: return self.search_ext_s(base,scope,filterstr,attrlist,attrsonly,None,None,timeout=self.timeout): /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.251859 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 846, in search_ext_s: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.251923 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: return self.result(msgid,all=1,timeout=timeout)[1]: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.251984 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 738, in result: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252032 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: resp_type, resp_data, resp_msgid = self.result2(msgid,all,timeout): /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252091 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 742, in result2: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252160 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all,timeout): /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252218 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 749, in result3: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252247 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: resp_ctrl_classes=resp_ctrl_classes: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252305 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 756, in result4: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252374 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop): /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252434 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 329, in _ldap_call: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252467 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: reraise(exc_type, exc_value, exc_traceback): /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252523 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/compat.py", line 44, in reraise: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252539 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: raise exc_value: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252599 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: File "/usr/local/lib/python3.5/dist-packages/ldap/ldapobject.py", line 313, in _ldap_call: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252623 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: result = func(*args,**kwargs): /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py
[Thu Nov 08 16:56:17.252690 2018] [cgi:error] [pid 17010:tid 140415768426240] [client 10.188.188.150:23467] AH01215: ldap.REFERRAL: {'info': 'Referral:\\nldap://kar-tel.local/dc=kar-tel,%20dc=local', 'desc': 'Referral'}: /var/www/haproxy-wi/app/options.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/users.py

**Comment by Aidaho12** [comment]
You updated?
--
Отправлено из Mail.Ru для Android четверг, 08 ноября 2018г., 22:11 +06:00 от Clero92  notifications@github.com :

**Comment by Clero92** [comment]
yes

**Comment by Aidaho12** [comment]
Show me
```
try:
		l.protocol_version = ldap.VERSION3
		l.set_option(ldap.OPT_REFERRALS, 0)

		bind = l.simple_bind_s(user, password)

		criteria = "(&(objectClass=user)(sAMAccountName="+username+"))"
		attributes = ['mail']
		result = l.search_s(ldap_base, ldap.SCOPE_SUBTREE, criteria, attributes)

		results = [entry for dn, entry in result if isinstance(entry, dict)]
		try:
			print('["'+results[0]['mail'][0].decode("utf-8")+'","'+user.split('@')[1]+'"]')
		except:
			print('error: user not found')
	finally:
l.unbind()
```
in options.py, it at end file

**Comment by Clero92** [comment]
Ok, test finished. I had to change some values:

My useraccount doesn't have a mail-value: so changed "mail" to "userPrincipalName"

Then I got an error with Array and changed from 1 to 0 in try section (user.split('@')[0]).

attributes = ['userPrincipalName']
print('["'+results[0]['userPrincipalName'][0].decode("utf-8")+'","'+user.split('@')[0]+'"]')

Now I can search accounts in HAPWI. Can you confirm?

**Comment by Aidaho12** [comment]
Cool, I will add exception

**Comment by Clero92** [comment]
Found new one:

The Login name in "Admin area" is listed wrong: "myADAccount@ldap_user_in_config"
This should be "myADAccount@mydomain" (userPrincipalName).

The Login with "myADAccount@ldap_user_in_config" does not work. No new logs :( .

**Comment by Aidaho12** [comment]
yes, that's why there is a split by "@", you must found field where have something like mail, to parse domain

**Comment by Aidaho12** [comment]
change from user.split('@')[0] to user.split('@')[1]

But why you got array error if you set ldapuser@domin.de ?

**Comment by Clero92** [comment]
Login doesnt work with ldapuser@domin.de and the system added the account with "myADAccount@ldap_user_in_config".

Can you add selection field for domain in login page? Or login with subdomain\ldapaccount?

**Comment by Aidaho12** [comment]
Ok... update and do this in DB:
```
"INSERT INTO settings (param, value, section, `desc`) values('ldap_domain', '', 'ldap', 'Domain for login, that after @, like user@domain.com, without user@');",
"INSERT INTO settings (param, value, section, `desc`) values('ldap_search_field', 'mail', 'ldap', 'Field where user e-mail saved');
```

**Comment by Clero92** [comment]
1.)
Ok, after git update and db update + ldap_domain + ldap_search_field in Settings, I can login with ldapuser@subdomain.domain.tld :)

But I can't login with subdomain\ldapuser . 
Can you add one field to login with the subdomain (local login or subdomain and which subdomain in AD Forest). Mabye [local\local_user] [subdomain1\ldapuser] [subdomain2\ldapuser]

2.)
AD Forest search did not work. I changed ldap_base to forest root and the system did not find the user in subdomain1 or subdomain2. If I changed ldap_base back to subdomain1 then subdomain1 ldapaccounts will be found, but not subdomain2.

3.)
Maybe change  (&(objectClass=user)(sAMAccountName="+username+")) to (&(objectClass=user)(userPrincipalName="+username+")) for big environment (quicker ldap search)?

4.)
Can I add an ldap group?

5.) 
sorry to bother you with ldap :(

**Comment by Aidaho12** [comment]
1,2) If forest search will work i think what login with subdomain, subdomain2 etc will work too.... But I can't check this, becouse in my AD only 1 domain... and I don't know AD :(

3) Maybe, Try it, and after say me please your experiance ))

4) Do not quite understand

**Comment by Clero92** [comment]
1.)
Ok, to perform search against whole forest (root, sub1, sub2 etc.) you must query the global catalog. In my case the global catalog service was running on the same ldap server I configuered in settings but changed the port to 3268 (ldap://global_catalog_ip:3268). 

Good, now you can search with "(&(objectClass=user)(samACCountName=MyLDAPUser))" in every site :) .

2.)
Now, I dont like to write MyLDAPUser@sub1.domain.tld in login page. Instead sub1\MyLDAPUser would be pretty :) .

Can you update the login page to use the domain "sub1" before "\MyLDAPUser" then search the root domain with rootDSE, add the root domain to sub1 and then you will have the userprincipalname (MyLDAPUser@sub1.domain.tld).

res = l.search_s("", ldap.SCOPE_BASE, '(objectClass=*)')
rootDSE = res[0][1]
print(rootDSE['rootDomainNamingContext'][0])

3.) if sub1\MyLDAPUser login is working, can you set a list of logindomains as selectbox in login page?

4.) LDAP-Groups
I want to add a ldap group instead of an ldapuser. 
ldapuser-login -> ldapuser in ldapgroup -> access in hapwi

**Comment by Aidaho12** [comment]
1) Fine

2,3,4) May be latter...
