### ISSUE TITLE
HAProxy Map function in HAPWI - output window too small 

### ISSUE THREAD

**Issue by Clero92** [Aidaho12/haproxy-wi#71]
Hello,
how can I change the size of the output window from the Map function (HAPWI -> HAProxy->Configs->Map)?

We have long frontend and backend names and these were cut in the window.

BTW: great feature! :). Hope you can fix this.

**Comment by Aidaho12** [comment]
I changed map size, update and try

And will be good if you show me map pic

**Comment by Aidaho12** [comment]
It after update?  It seems everything fits

>Maybe custom config with scrollbars possible?
No, size fixed in program :(


>Пятница,  2 ноября 2018, 14:25 +06:00 от Clero92 <notifications@github.com>:
>
>https://picload.org/view/dcogowgw/hapwi_issue_71_2.png.html
>https://picload.org/view/dcogowrg/hapwi_issue_71_1.png.html
>Maybe custom config with scrollbars possible?
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Павел.

**Comment by Clero92** [comment]
Yes, pics are after update. Better then before :) 

Some overlaping now and the backend names are cut (use backend ... [...] ).

**Comment by Aidaho12** [comment]
You can change it manual in ovw.py, line 182:
```
plt.figure(10,figsize=(15,20))
```
Last 2 params 15, 20

**Comment by Clero92** [comment]
Ok, thanks. I will take a look.
