### ISSUE TITLE
'ascii' codec can't encode character

### ISSUE THREAD

**Issue by Clero92** [Aidaho12/haproxy-wi#72]
Hello,
I have found a bug. If I enter utf-8 chars in password for user I cant access "Admin area->Servers" (site is blank).

I then changed my password in db back to "admin" and everything is ok (btw: please implement password-hash :) ).

Error:
: 'ascii' codec can't encode character '\\xa7' in position 7514: ordinal not in range(128): /var/www/haproxy-wi/app/servers.py, r

Password: vg§RWd>GS%G>Axn1uMRI

**Comment by Aidaho12** [comment]
Try decode admin page to utf-8

>please implement password-hash
I have been going for a long time, but my hands do not reach

>Пятница,  2 ноября 2018, 14:06 +06:00 от Clero92 <notifications@github.com>:
>
>Hello,
>I have found a bug. If I enter utf-8 chars in password for user I cant access "Admin area->Servers" (site is blank).
>I then changed my password in db back to "admin" and everything is ok (btw: please implement password-hash :) ).
>Error:
>: 'ascii' codec can't encode character '\xa7' in position 7514: ordinal not in range(128): /var/www/haproxy-wi/app/servers.py, r
>Password: vg§RWd>GS%G>Axn1uMRI
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Павел.

**Comment by Aidaho12** [comment]
I think I fixed it, update and try

**Comment by Clero92** [comment]
no sry, changed Password to "ü" - same error

[Fri Nov 02 10:20:05.911625 2018] [cgi:error] [pid 23601:tid 140589219628800] [client 10.188.188.150:6230] AH01215: Traceback (most recent call last):: /var/www/haproxy-wi/app/users.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/overview.py
[Fri Nov 02 10:20:05.911707 2018] [cgi:error] [pid 23601:tid 140589219628800] [client 10.188.188.150:6230] AH01215: File "/var/www/haproxy-wi/app/users.py", line 39, in <module>: /var/www/haproxy-wi/app/users.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/overview.py
[Fri Nov 02 10:20:05.911731 2018] [cgi:error] [pid 23601:tid 140589219628800] [client 10.188.188.150:6230] AH01215: print(output_from_parsed_template): /var/www/haproxy-wi/app/users.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/overview.py
[Fri Nov 02 10:20:05.911782 2018] [cgi:error] [pid 23601:tid 140589219628800] [client 10.188.188.150:6230] AH01215: UnicodeEncodeError: 'ascii' codec can't encode character '\\xfc' in position 7343: ordinal not in range(128): /var/www/haproxy-wi/app/users.py, referer: https://snsrvhapwi1t.helios-dom.helios-kliniken.de/app/overview.py

**Comment by Aidaho12** [comment]
strange behavior if i do:
```
output_from_parsed_template = template.render(title = "Admin area: users manage",
												role = sql.get_user_role_by_uuid(user_id.value),
												user = user,
												users = users,
												groups = sql.select_groups(),
												servers = sql.select_servers(full=1),
												roles = sql.select_roles(),
												masters = sql.select_servers(get_master_servers=1),
												sshs = sql.select_ssh(),
												telegrams = sql.select_telegram(),
												token = token).encode('utf-8')
```
many characters appear like: '\t\t\n\n\n\n\n'

**Comment by Aidaho12** [comment]
Hi! I have fixed the bug, you can check ))))
