### ISSUE TITLE
Invalid "docker run" command

### ISSUE THREAD

**Issue by shchedrin** [Aidaho12/haproxy-wi#73]
Hello!
I found a problem in command `docker run -d --name haproxy-wi -v haproxy-wi:/var/www/haproxy-wi/app aidaho/haproxy-wi`
You need to expose 80 port:
`docker run -d --name haproxy-wi -v haproxy-wi:/var/www/haproxy-wi/app -p 8080:80 aidaho/haproxy-wi`

**Comment by Aidaho12** [comment]
Oh ) Thank you )
