### ISSUE TITLE
Can't save config

### ISSUE THREAD

**Issue by mattmac1** [Aidaho12/haproxy-wi#78]
When trying to save a new config haproxy-wi hangs.

I can see the following error in the logs:

[Fri Nov 09 08:22:26.982140 2018] [cgi:error] [pid 24575] [client 10.0.66.203:39932] AH01215: dos2unix: converting file /var/www/haproxy-wi/configs/hap_config/192.168.168.50-2018-11-09.07:22:26.cfg to Unix format ..., referer: http://192.168.168.50:8080/app/config.py?serv=192.168.168.50&open=open

**Comment by Aidaho12** [comment]
What you meen "hangs"? 

If you see message:
```
[Fri Nov 09 08:22:26.982140 2018] [cgi:error] [pid 24575] [client 10.0.66.203:39932] AH01215: dos2unix: converting file /var/www/haproxy-wi/configs/hap_config/192.168.168.50-2018-11-09.07:22:26.cfg to Unix format ..., referer: http://192.168.168.50:8080/app/config.py?serv=192.168.168.50&open=open
```
It's meen config is saved at HAProxy-WI

**Comment by mattmac1** [comment]
The new config isn't applied to /etc/haproxy/haproxy.cfg if I manually edit it and click save and restart.
Also when adding a listener the screen gets grayed out and stay like that... attached screenshot
![image](https://user-images.githubusercontent.com/6524325/48251705-e6ea9180-e402-11e8-967e-2f74a3d2ff5b.png)

**Comment by Aidaho12** [comment]
Hm....

Check all folders where save configs. Need to understand at what stage it disappears. Also run javascript debug and watch what happen when you will save config
