### ISSUE TITLE
waf does not install 

### ISSUE THREAD

**Issue by dizi11** [Aidaho12/haproxy-wi#79]
Hi
I want to install a waf on a (CentOS Linux release 7.5.1804) but it does not work.
I realized that in my case we do not have pcre-devel installed.
I have installed and now it works:
sudo yum install pcre-devel -y

But I can not tick Metrics. I tick it but it does not check.

And i have this error in page:

Not Found

The requested URL /app/templates/metrics_waf_out.html was not found on this server.

**Comment by Aidaho12** [comment]
Hi
Chekc apache error log
And "not found" error its ok
--
Отправлено из Mail.Ru для Android понедельник, 12 ноября 2018г., 18:10 +06:00 от dizi11  notifications@github.com :

**Comment by dizi11** [comment]
[Mon Nov 12 14:24:26.792597 2018] [cgi:error] [pid 6995] [client 1.1.1.1:57382] AH01215: WARNING:bokeh.core.validation.check:W-1002 (EMPTY_LAYOUT): Layout has no children: Column(id='b9cb0dda-be8f-4736-a66d-c27113dbfe72', ...), referer: http://1.1.1.2:8080/app/waf.py

**Comment by Aidaho12** [comment]
Check 1999 port on both servers
--
Отправлено из Mail.Ru для Android понедельник, 12 ноября 2018г., 20:29 +06:00 от dizi11  notifications@github.com :

**Comment by dizi11** [comment]
they are open

**Comment by jokothinker** [comment]
sorry my mistake. as mentioned by dizi11, pcre-devel is needed on proxy node. thanks

**Comment by ping999ms** [comment]
![234](https://github.com/roxy-wi/roxy-wi/assets/93276453/9ef95bb7-3108-40a9-8a8a-22a665d1e9cd)
Has anyone ever encountered an issue installing a firewall for NGINX like I have? Please, I need assistance
