### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by vrelk** [Aidaho12/haproxy-wi#8]
On a fresh install of CentOS 7 and the auto install of HAWI, I am getting the following error when trying to create a server. I did check the html, and that is the entire error, so unfortunately it doesn't mention what is missing.

`(2, 'No such file or directory')`

Second, please convert the login from get to post, HUGE security issue right there.

**Comment by Aidaho12** [comment]
You trying create server in admin area? 

And can you show apache logs? /var/log/httpd/haproxy-wi.error.log

**Comment by Aidaho12** [comment]
And you upload ssh key, or set root password in config file?

**Comment by vrelk** [comment]
Err, whoops. Didn't even think about the ssh key since it was a local install.

**Comment by Aidaho12** [comment]
>Second, please convert the login from get to post, HUGE security issue right there.

Yes, i know, but post for some resons didn't work (
