### ISSUE TITLE
WAF Setting

### ISSUE THREAD

**Issue by Ahmedsbelghith** [Aidaho12/haproxy-wi#81]
Hello 
first of all thank you for your great work
i've a question about the waf setting, after the installation of waf on the server, how we can manage it via web interface?
and does the waf uses only apache module security and what about evasive module ?

thanks

Regard 
Ahmed

**Comment by Aidaho12** [comment]
Hi!
Thank you )

You can edit WAF settings in rules files and cfg file mod_sec

haproxy dosn't support the evasive module

**Comment by ahmedbelghith** [comment]
Dear @Aidaho12 
I 'am working with  modSec from Haproxy (installed from your script) 
 I've a couple of issues that I'll describe just below : 
my Server acts as Haproxy/LB who distrute the requests to webserver(node1).
I just want the WAF block  requests based on Cross-Site Scripting (XSS ) but it seems that crs rule(/etc/haproxy//waf/rules/modsecurity_crs_41_xss_attacks.conf) doesn't work, by injecting some  malicious code into mywebserver

below my config
`global
    log         127.0.0.1 local2
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon
    stats socket /var/lib/haproxy/stats
    stats socket *:1999 level admin
    stats socket /var/run/haproxy.sock mode 600 level admin
    server-state-file /etc/haproxy/haproxy.state

defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

listen stats
    bind *:8085
    stats enable
    stats uri /stats
    stats realm HAProxy-04\ Statistics
    stats auth admin:password
    stats admin if TRUE
 

backend test_back
    mode http
    balance roundrobin
    server 192.168.52.154 192.168.52.154:80 check
    #server 192.168.52.157 192.168.52.157:80 check
frontend test_front
    bind *:80
    mode http
    maxconn 2000
    default_backend test_back
backend waf
    mode tcp
    timeout connect 5s
    timeout server  3m
    server waf 127.0.0.1:12345 check

`
is it an issue with SPOE ?

thanks

**Comment by Aidaho12** [comment]
everything looks good, check waf servis is started

**Comment by ahmedbelghith** [comment]
hello thanks for your reply
Waf service works , but i cannot access to the page i got 403 forbidden.
 
`

 global
    log         127.0.0.1 local2
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon
    stats socket /var/lib/haproxy/stats
    stats socket *:1999 level admin
    stats socket /var/run/haproxy.sock mode 600 level admin
    server-state-file /etc/haproxy/haproxy.state

defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 3000

listen stats
    bind *:8085
    stats enable
    stats uri /stats
    stats realm HAProxy-04\ Statistics
    stats auth admin:password
    stats admin if TRUE
 

backend test_back
    mode http
    balance roundrobin
     
    server 192.168.52.154 192.168.52.154:80 check
    #server 192.168.52.157 192.168.52.157:80 check


frontend test_front
    bind *:80
    mode http
    maxconn 2000
    #filter trace
    #http-response set-header X-ModSecStatus "%[var(txn.modsec.err)]"
    #http-response set-header X-ModSec "%[var(txn.modsec.code)]"
    default_backend test_back
    
 
backend waf
    mode tcp
    timeout connect 5s
    timeout server  3m
    server waf 127.0.0.1:12345 check


 
`

**Comment by Aidaho12** [comment]
403 error meens waf work :)

**Comment by ahmedbelghith** [comment]
yes i know 403 means waf work, but my backend server became unreachable after this config.
in principle, the page requested should appears, then i can inject xss and check if  the waf detect the malicious code or not .

**Comment by Aidaho12** [comment]
read about mod_sec configuring

**Comment by ahmedbelghith** [comment]
as far i know, Haproxy uses thirdparty daemon 'SPOE', who gives request send by haproxy to modsecurity and return the verdict.
i've tested modsec module with apache, and it works fine, but with Haproxy/modsec is bit complicated.
with haproxy: modsec works as standalone.
so i asked if had make error on my haproxy config 

thanks!!
