### ISSUE TITLE
Tools are DOWN, haproxy server connection is ok.

### ISSUE THREAD

**Issue by maxpavlov** [Aidaho12/haproxy-wi#83]
Hello.

I've installed haproxy-wi via Docker. I've connected it to my haproxy server with haproxy 1.8.8 and Ubuntu 18.04. I used password credentials, not a key, in SSH Credentials.

Here is what I see in my overview screen:
![overview](https://user-images.githubusercontent.com/669701/49443695-bf0a0600-f7d5-11e8-894b-25c968e0261c.jpg)

The problems are:
All Tools are DOWN.

When I go to Haproxy -> Configs and Select my server and click "Show" I get "Can't read import config file" error.

How can I fix the Config display error?

**Comment by Aidaho12** [comment]
Hi, 
Ssh chech is ok? And show me apache error log
--
Отправлено из Mail.Ru для Android вторник, 04 декабря 2018г., 19:05 +06:00 от Max Pavlov  notifications@github.com :

**Comment by maxpavlov** [comment]
@Aidaho12 when I go to Admin area -> Servers and click "Check" button, I get "Connect accept" in the green background. Is this the "SSH Check" you were reffering to?

Also, where do I see an apache error log given that I have a docker container image hosted haproxy-wi. If you are talking about: Admin area -> Internal logs -> error.log, the only meaningful one is:

> [Tue Dec 04 13:04:14.469671 2018] [cgi:error] [pid 8] [client 10.240.255.107:58846] AH01215: NameError: name 'conf' is not defined, referer: http://haproxy.westeurope.azurecontainer.io/app/config.py

**Comment by Aidaho12** [comment]
On the haproxy server config file is /etc/haproxy/haproxy.cfg?
--
Отправлено из Mail.Ru для Android вторник, 04 декабря 2018г., 19:20 +06:00 от Max Pavlov  notifications@github.com :

**Comment by maxpavlov** [comment]
Yes, exactly there, by default since the beginning.

**Comment by maxpavlov** [comment]
Let's not close this one in a meantime, maybe someone will have a similar problem. I suspect not many docker deployments are out there just yet.

**Comment by maxpavlov** [comment]
I also get this when I try to go to WAF:

![image](https://user-images.githubusercontent.com/669701/49452622-35b0fe80-f7ea-11e8-9c9b-f966807d3f06.png)

Maybe docker image is missing some template files in its installation?

**Comment by Aidaho12** [comment]
It's ok, at Docker image services like metric, alert and keep_alived not work, you may try start them manual

**Comment by maxpavlov** [comment]
Thanks. Also, my SSH port is not 22. Does your code take into account the PORT setting from SSH Credentials everywhere so that it tries to retrieve the config file via the correct port?

**Comment by Aidaho12** [comment]
There should be a port that is specified in the settings, but it is better to check which port it is connected to on the docker

**Comment by SysadminEU1** [comment]
I have also tried Ubuntu 16.04 and did not find any other solution than reinstall using Centos 7 with yum update.

Now I can install haproxy-wi from the clone command given in the install feature.
I got other issues now, I will open another forum post for this.

**Comment by Symbianx** [comment]
I can't access my configuration, when I called show i get the error:

```
[Fri Feb 22 15:08:04.779421 2019] [cgi:error] [pid 58] [client 10.42.17.4:34148] AH01215: NameError: name 'conf' is not defined, referer: https://haproxy.qc.nos.pt/app/config.py
[Fri Feb 22 15:08:13.403960 2019] [cgi:error] [pid 9] [client 10.42.17.4:34186] AH01215: /usr/lib/python3.5/site-packages/paramiko/kex_ecdh_nist.py:39: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding., referer: https://haproxy.qc.nos.pt/app/config.py
[Fri Feb 22 15:08:13.404059 2019] [cgi:error] [pid 9] [client 10.42.17.4:34186] AH01215:   m.add_string(self.Q_C.public_numbers().encode_point()), referer: https://haproxy.qc.nos.pt/app/config.py
[Fri Feb 22 15:08:13.404345 2019] [cgi:error] [pid 9] [client 10.42.17.4:34186] AH01215: /usr/lib/python3.5/site-packages/paramiko/kex_ecdh_nist.py:96: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point, referer: https://haproxy.qc.nos.pt/app/config.py
[Fri Feb 22 15:08:13.404393 2019] [cgi:error] [pid 9] [client 10.42.17.4:34186] AH01215:   self.curve, Q_S_bytes, referer: https://haproxy.qc.nos.pt/app/config.py
[Fri Feb 22 15:08:13.404725 2019] [cgi:error] [pid 9] [client 10.42.17.4:34186] AH01215: /usr/lib/python3.5/site-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding., referer: https://haproxy.qc.nos.pt/app/config.py
[Fri Feb 22 15:08:13.404805 2019] [cgi:error] [pid 9] [client 10.42.17.4:34186] AH01215:   hm.add_string(self.Q_C.public_numbers().encode_point()), referer: https://haproxy.qc.nos.pt/app/config.py
[Fri Feb 22 15:08:13.404865 2019] [cgi:error] [pid 9] [client 10.42.17.4:34186] AH01215: Traceback (most recent call last):, referer: https://haproxy.qc.nos.pt/app/config.py
[Fri Feb 22 15:08:13.404941 2019] [cgi:error] [pid 9] [client 10.42.17.4:34186] AH01215:   File "/var/www/haproxy-wi/app/options.py", line 340, in <module>, referer: https://haproxy.qc.nos.pt/app/config.py
[Fri Feb 22 15:08:13.405084 2019] [cgi:error] [pid 9] [client 10.42.17.4:34186] AH01215:     template = template.render(conf=conf, view=form.getvalue('view'), serv=serv, configver=form.getvalue('configver'))\t\t\t\t\t\t\t\t\t\t\t, referer: https://haproxy.qc.nos.pt/app/config.py
[Fri Feb 22 15:08:13.405137 2019] [cgi:error] [pid 9] [client 10.42.17.4:34186] AH01215: NameError: name 'conf' is not defined, referer: https://haproxy.qc.nos.pt/app/config.py
```

I deployed haproxy-wi in docker and let it install haproxy on the machine.

**Comment by Symbianx** [comment]
Ok, I found my problem, the container was in kubernetes and the configs folder was mounted inside a volume, that folder did not give enough permissions to the apache user to make changes.

**Comment by sheng5521627** [comment]
Can't connect to HAproxy who can I do
