### ISSUE TITLE
Centos 7.5 High cpu and unable to install HAproxy 1.18.x

### ISSUE THREAD

**Issue by SysadminEU1** [Aidaho12/haproxy-wi#84]
Hey

First and foremost thanks for this project, it will be successfull.

My setup is very simple, one subnet with one Haproxy-wi(sqlite) and two frontend with Haproxy and (VRRP).
System is Centos 7 on the latest version.

1. High CPU - 99% CPU on "python3 /var/www/haproxy-wi/app/tools/keep_alive.py"
2. I only want to use HAProxy 1.18.x and not 1.15 (My problem is that I cannot uninstall haproxy with the command "yum remove haproxy" - yum does not figure out how it is compilled/installed, it says 
No Match for argument: haproxy
No Packages marked for removal.
2.1 How do I uninstall haproxy on the two frontends - without reinstalling Centos 7 from scratch?
2.2 I tried to fix the 1.15 problem by using this guide https://pario.no/2018/07/17/install-haproxy-1-8-on-centos-7/ it failed utterly.
2.3 How does haproxy-wi actually install 1.18.5 succesfully, what needs to be installed? with yum install?

Many thanks for the project
Suggestion for improvement - when haproxy-wi connects to the target system where haproxy is going to be installed - it should ask for what system it is and apply the apprioate commands or tell that the system is not supported by haproxy-wi.

**Comment by SysadminEU1** [comment]
1. I cloned it yesterday from Github - I dont think I can disable the service as I plan to use it for a HA.
2. I installed haproxy from the web interface /app/ha.py - I set a master and a slave, VRRP ip, I did not install it from other sources.
2.3 So are you saying that I could a fresh Centos 7 install, compile a new haproxy 1.18.14 and haproxy-wi would pickup the configuration and do its magic from that point on?

**Comment by Aidaho12** [comment]
2,3 Yes you can, or you can install new haproxy on current system

If you will choose clear system, you will need to do some config settings in haproxy

**Comment by SysadminEU1** [comment]
2.3 What commands will you suggest I do to get 1.18.5 to function?

**Comment by Aidaho12** [comment]
Google ^_^

**Comment by SysadminEU1** [comment]
:-)

**Comment by SysadminEU1** [comment]
Please do not comment, I will use this post to write what I did.

As I am back to sqaure one, I deleted the two exsisting servers and reinstalled Centos 7.5 again.

I did a full reinstall, by deleting the harddrive partions and installed centos 7.5 again and ran the command yum update, as well as yum install git wget ntsysv

From HA-Proxy i did a diffrent apporach - I installed HAProxy from the /app/ihap.py (I did not and on the two frontends I got 

[root@localhost ~]# haproxy -v
HA-Proxy version 1.8.1 2017/12/03
Copyright 2000-2017 Willy Tarreau <willy@haproxy.org>

So I am on 1.8.1 (Not 1.8.5 as written in the URL)
Will try to move on with HA and the other log settings as well
A wish for future release, I allways want to be on the latest version :-)

**Comment by SysadminEU1** [comment]
Latest version of HAproxy, at the time of writing is 1.8.14

**Comment by SysadminEU1** [comment]
The first thing I wanted to try is HA
My two frontends, are called front1 and front2.

I navigated to the page "Configure HA"
I Choose front1 (10.0.0.33) as master and front2 (10.0.0.34) as slave.
VRRP interface = eth0
VRRP IP=10.0.0.35
Install HAProxy = unchecked
Sync flood protrect = checked (default)

After the animation is finish, the log box still reports 
"Please don't close and don't represh page. Wait until the work is completed. This may take some time"

No other prompts are generated and somehow stuck.

A wish for the future, any error - please post them here, or show actually console "action" for debugging purposes.

**Comment by SysadminEU1** [comment]
I am going to wait 30 min for the "Please don´t ......." and see if it disappers, I dont believe it will.

**Comment by SysadminEU1** [comment]
As expected - it did not complete.
After a F5 browser refresh it is clear that HA is not enabled as nothing in showing the "Or add VRRP to exist"

It failed without any hint on why.
A wish, somehow it should show the error on the page.

**Comment by Aidaho12** [comment]
>I am going to wait 30 min for the "Please don´t ......." and see if it disappers, I dont believe it will.

Some times it's happened ( you can check install, more often it's ok

**Comment by SysadminEU1** [comment]
Where would the correct logfile be located - for the HA configuration?

**Comment by Aidaho12** [comment]
they do not exist :(

**Comment by SysadminEU1** [comment]
A wish for the furture

Looking on official Centos 7 documentation to verify that my configuration whis, would actually work.

**Comment by SysadminEU1** [comment]
Still working on VRRP
Tried disable FW on all 3 servers, looked on Mac adresses and some other stuff, no luck so far.

**Comment by SysadminEU1** [comment]
I decided to run ./waf.sh and I got the following error

[root@localhost tmp]# ./waf.sh
error: Need HAProxy version 1.8 or later <a title="Close" id="errorMess"><b>X</b></a>
[root@localhost tmp]# haproxy -v
HA-Proxy version 1.8.1 2017/12/03
Copyright 2000-2017 Willy Tarreau <willy@haproxy.org>

**Comment by SysadminEU1** [comment]
`[root@localhost tmp]# ./waf.sh
error: Need HAProxy version 1.8 or later <a title="Close" id="errorMess"><b>X</b></a>
[root@localhost tmp]# haproxy -v
HA-Proxy version 1.8.1 2017/12/03
Copyright 2000-2017 Willy Tarreau <willy@haproxy.org>
`

**Comment by SysadminEU1** [comment]
I await a solution as I believe the issue is starting from ./waf.sh 

Moving on to add a backend server and creating a proxy setting without HA

**Comment by Aidaho12** [comment]
waf.sh it's script to creating waf service

if you need install keepalived, run install_keepalived.sh with params what script need. Check connect to internet, check your yum working or not...

I don't do support ... for free
