### ISSUE TITLE
Error saving new config

### ISSUE THREAD

**Issue by servere** [Aidaho12/haproxy-wi#85]
HAPROXY-WI v3.4 with HAPROXY 1.8.4

When saving a new config, I got the following error on the web page:
Some errors: sudo: haproxy: command not found

In the Apache error log:
[Mon Dec 10 10:43:52.676596 2018] [cgi:error] [pid 6116] [client xx.xx.xx.xx:30195] AH01215: dos2unix: converting file /var/www/haproxy-wi/configs/hap_config/10.63.65.50-2018-12-10.09:43:51.cfg to Unix format ..., referer: http://s-eacea-rh7-haproxywi:8080/app/config.py?serv=yy.yy.yy.yy&open=open

Can you please help?

**Comment by Aidaho12** [comment]
See https://github.com/Aidaho12/haproxy-wi/issues/80
