### ISSUE TITLE
Offline Use

### ISSUE THREAD

**Issue by tonycrotwell** [Aidaho12/haproxy-wi#86]
Hi. When trying to use this container in an offline setup (ie. docker save, docker load...) it seems to start but when I try to login, and looking at the dev tools with Firefox, I see it's trying to connect to an external URL jquery.code or whatever for some css config files. Is there a way to self contain this piece for use in an offline environment?  Thanks so much.

**Comment by Aidaho12** [comment]
Hi! Yes, you can. Just download all jquery files localy and re-create docker image with those files. And edit link in index.html and base.html with new local address

**Comment by tonycrotwell** [comment]
Thank you.  That is what I was planning but wanted to make sure you weren't
updating the official image yourself.

Appreciate the prompt response.

Tony

**Comment by ducttapecoder-vt** [comment]
Hello,
Can you update the docker image to include this natively or provide instructions on how to do this manually?

**Comment by Aidaho12** [comment]
Hello, docker image already includes all necessary files

**Comment by ducttapecoder-vt** [comment]
How do I make it work then? I'm seeing the same issue that @tonycrotwell originally mentioned. It's trying to make a call to code.jquery.com which obviously fails when offline. I put in username/password and it just drops back to the login screen with no message.

**Comment by ducttapecoder-vt** [comment]
Okay I tried to replace 
```
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
```
with 
```
<link rel="stylesheet" href="/inc/jquery-ui.css">
<script src="/inc/jquery-1.12.4.js"></script>
<script src="/inc/jquery-ui.js"></script>
```
https://github.com/ducttapecoder-vt/haproxy-wi/commit/266de0b45412939dd6a3f92b882e76b6fc56c094

and rebuilt the docker container pointing to my fork and now the container gives a "welcome to haproxy-wi" splash for a brief second then goes to

> Internal Server Error
> The server encountered an internal error or misconfiguration and was unable to complete your request.

Docker gave me a warning when building, not sure if related:

> SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

**Comment by Aidaho12** [comment]
I have updated docker image with offline usege. Try in 2 hours

**Comment by ducttapecoder-vt** [comment]
Success, I'm logged in! Now how the hell do I use this thing? Just kidding. ;)
