### ISSUE TITLE
Let's Encrypt

### ISSUE THREAD

**Issue by SeyedGH** [Aidaho12/haproxy-wi#89]
Hi is there any way there is implementation possible for automated certificate request and renews?

**Comment by Aidaho12** [comment]
Yes, there is a possibility, maybe someday I will do it

**Comment by BloodyIron** [comment]
You might be able to meet your need by adapting the apache config to work with Let's Encrypt. Have you looked into that?

**Comment by Aidaho12** [comment]
Few days ago were update, he included for https config. Just change paths to your certs
