### ISSUE TITLE
Upload config not working

### ISSUE THREAD

**Issue by Luxiter** [Aidaho12/haproxy-wi#9]
We try to use thi interface and the upload config seems to not working correctly

**Comment by Aidaho12** [comment]
Show me apache error logs, please

**Comment by Luxiter** [comment]
[Tue May 08 10:42:36.161348 2018] [cgi:error] [pid 1479] [client 192.168.122.1:33212] AH01215: dos2unix: converting file /var/www/haproxy-wi/configs/hap_config/192.168.122.177-2018-05-08.08:42:36.cfg to Unix format ..., referer: http://haprox-wi.example.com:8080/app/config.py?serv=192.168.122.177&open=open
[Tue May 08 10:46:10.895952 2018] [cgi:error] [pid 14632] [client 192.168.122.1:33382] AH01215: dos2unix: converting file /var/www/haproxy-wi/configs/hap_config/192.168.122.177-2018-05-08.08:17:42.cfg to Unix format ..., referer: http://haprox-wi.example.com:8080/app/configver.py?serv=192.168.122.177&open=open&configver=192.168.122.177-2018-05-08.08:17:42.cfg
[Tue May 08 10:46:11.904054 2018] [cgi:error] [pid 14632] [client 192.168.122.1:33382] AH01215: Traceback (most recent call last):, referer: http://haprox-wi.example.com:8080/app/configver.py?serv=192.168.122.177&open=open&configver=192.168.122.177-2018-05-08.08:17:42.cfg
[Tue May 08 10:46:11.904133 2018] [cgi:error] [pid 14632] [client 192.168.122.1:33382] AH01215:   File "/var/www/haproxy-wi/app/configver.py", line 65, in <module>, referer: http://haprox-wi.example.com:8080/app/configver.py?serv=192.168.122.177&open=open&configver=192.168.122.177-2018-05-08.08:17:42.cfg
[Tue May 08 10:46:11.904198 2018] [cgi:error] [pid 14632] [client 192.168.122.1:33382] AH01215:     stderr, error = funct.upload_and_restart(serv, configver, just_save=save), referer: http://haprox-wi.example.com:8080/app/configver.py?serv=192.168.122.177&open=open&configver=192.168.122.177-2018-05-08.08:17:42.cfg
[Tue May 08 10:46:11.904240 2018] [cgi:error] [pid 14632] [client 192.168.122.1:33382] AH01215: ValueError: too many values to unpack (expected 2), referer: http://haprox-wi.example.com:8080/app/configver.py?serv=192.168.122.177&open=open&configver=192.168.122.177-2018-05-08.08:17:42.cfg
[Tue May 08 10:48:19.598643 2018] [cgi:error] [pid 1154] [client 192.168.122.1:33436] AH01215: dos2unix: converting file /var/www/haproxy-wi/configs/hap_config/192.168.122.177-2018-05-08.08:17:42.cfg to Unix format ..., referer: http://haprox-wi.example.com:8080/app/configver.py?serv=192.168.122.177&open=open&configver=192.168.122.177-2018-05-08.08:17:42.cfg
[Tue May 08 10:48:20.294090 2018] [cgi:error] [pid 1154] [client 192.168.122.1:33436] AH01215: Traceback (most recent call last):, referer: http://haprox-wi.example.com:8080/app/configver.py?serv=192.168.122.177&open=open&configver=192.168.122.177-2018-05-08.08:17:42.cfg
[Tue May 08 10:48:20.294171 2018] [cgi:error] [pid 1154] [client 192.168.122.1:33436] AH01215:   File "/var/www/haproxy-wi/app/configver.py", line 65, in <module>, referer: http://haprox-wi.example.com:8080/app/configver.py?serv=192.168.122.177&open=open&configver=192.168.122.177-2018-05-08.08:17:42.cfg
[Tue May 08 10:48:20.294218 2018] [cgi:error] [pid 1154] [client 192.168.122.1:33436] AH01215:     stderr, error = funct.upload_and_restart(serv, configver, just_save=save), referer: http://haprox-wi.example.com:8080/app/configver.py?serv=192.168.122.177&open=open&configver=192.168.122.177-2018-05-08.08:17:42.cfg
[Tue May 08 10:48:20.294265 2018] [cgi:error] [pid 1154] [client 192.168.122.1:33436] AH01215: ValueError: too many values to unpack (expected 2), referer: http://haprox-wi.example.com:8080/app/configver.py?serv=192.168.122.177&open=open&configver=192.168.122.177-2018-05-08.08:17:42.cfg

**Comment by Aidaho12** [comment]
Overwrite this file with the original in the folder app/

[configver.zip](https://github.com/Aidaho12/haproxy-wi/files/1983109/configver.zip)

**Comment by Aidaho12** [comment]
Disable firewall configure in config file
--
Отправлено из Mail.Ru для Android вторник, 08 мая 2018г., 15:24 +06:00 от Luxiter  notifications@github.com :

**Comment by Luxiter** [comment]
Some errors:

b"[ALERT] 127/113247 (1793) : parsing [/tmp//2018-05-08.09:32:47.cfg:42] : 'server 192.168.122.177:80' : could not resolve address 'check'.\n[ALERT] 127/113247 (1793) : Failed to initialize server(s) addr.\n" 

but the port 80 is active 

tcp        0      0 0.0.0.0:8085            0.0.0.0:*               LISTEN      873/haproxy         
tcp6       0      0 :::80                   :::*                    LISTEN      1762/httpd          
tcp6       0      0 :::8080                 :::*                    LISTEN      1762/httpd          
tcp6       0      0 192.168.122.177:80      192.168.122.1:50036     TIME_WAIT   -                   
tcp6       0      0 192.168.122.177:80      192.168.122.1:50038     TIME_WAIT   -

**Comment by Aidaho12** [comment]
This error return haproxy, becouse in your config have error
--
Отправлено из Mail.Ru для Android вторник, 08 мая 2018г., 15:37 +06:00 от Luxiter  notifications@github.com :

**Comment by Luxiter** [comment]
ok now working fine
