### ISSUE TITLE
IRC channel for discussion/recommendations

### ISSUE THREAD

**Issue by linuxphone** [Aidaho12/haproxy-wi#90]
Aidaho12,
The project looks great!

Would it be possible to open a IRC channel for discussion/recommendations. Append the info to the main README of the repo for others to have visibility/join. Thank you.

**Comment by Aidaho12** [comment]
Thank you

Not enough twitter?

In principle, it is possible. You know free IRC channels? Or may be Telegram chat?

**Comment by linuxphone** [comment]
Aidaho12 ,
Let me register the channel and I will provide you all the details. Thats
how great communities get created using IRC, its free!

**Comment by Aidaho12** [comment]
ok, please register it
--
Отправлено из Mail.Ru для Android среда, 23 января 2019г., 19:40 +06:00 от linuxphone  notifications@github.com :

**Comment by linuxphone** [comment]
Aidaho12,

I have registered the channel under:

 

irc.freenode.net 

 

using the following channel name:

 

#haproxy-wi

**Comment by Aidaho12** [comment]
What clients are good for IRC now? or does this service have a web interface?

**Comment by linuxphone** [comment]
Aidaho12,

I normally used invision: http://xmog.capellan.us/Invision/Invision3.1.3.May10.Incl.mIRC635.exe

 

But there are tons of options in terms of clients. I prefer invision because beautiful interface and easy of use.

**Comment by Aidaho12** [comment]
Not found page (

Installed mIRC for the first time

I'll update the readme now

Thank you )

**Comment by linuxphone** [comment]
Awesome, I saw you in the channel. Now we can have real time discussions.
