### ISSUE TITLE
Updating support for 1.9.2

### ISSUE THREAD

**Issue by linuxphone** [Aidaho12/haproxy-wi#91]
Aidaho12,
Can you validate support for 1.9.2, See the following link for compile RPM. Once validated, please update upstream via merge. Thank you.

http://download.opensuse.org/repositories/home:/Miuku/openSUSE_Leap_42.3/x86_64/haproxy-1.9.2-1.1.x86_64.rpm

**Comment by Aidaho12** [comment]
Now I can't add haproxy 1.9.2 because to install it need new ssl lib, but the new one is not yet in the repositories

**Comment by linuxphone** [comment]
Which lib is missing?

**Comment by Aidaho12** [comment]
libssl and libcrypto

**Comment by linuxphone** [comment]
Is there a specific version we are looking for?

**Comment by Aidaho12** [comment]
this is not important, it is important that they are not in the standard repositories
