### ISSUE TITLE
Keepalived not restarting

### ISSUE THREAD

**Issue by pcatarino** [Aidaho12/haproxy-wi#96]
Hi Guys,

Saving Keepalived configuration works fine, but if you try to save and restart it doesn't restart the service. 
It looks like you have a bug in your funct.py file.  

Line 344 
commands = [ "sudo mv -f " + tmp_file + " /etc/keepalived/keepalived.conf", "sudo systemctl restart keepalived" ]

**should be**
commands = [ "sudo mv -f " + tmp_file + " /etc/keepalived/keepalived.conf && sudo systemctl restart keepalived" ]

Keep up with your amazing work.

**Comment by Aidaho12** [comment]
Hi

You changed it and now works fine?

**Comment by pcatarino** [comment]
Hi,

Yes, initially was just saving the conf file, but was not restarting.
with that change is saving and restarting the keepalived service.

**Comment by Aidaho12** [comment]
Ok, thank you
