### ISSUE TITLE
Upgrade from older version

### ISSUE THREAD

**Issue by razvanli** [Aidaho12/haproxy-wi#97]
I am using the older version v2.5.6.2 and I plan to upgrade it to the latest one. What is the recommendation to fresh install or upgrade?
Fresh install case - How can the data be exported and imported?
Upgrade - What are the recommended steps?

**Comment by Aidaho12** [comment]
Or even better reinstall

**Comment by razvanli** [comment]
Yes I know I am using a very old version...but I have so many LBs there :) it not easy to make a change.
I think reinstall is the best solution. Making a backup of haproxy-wi.db and haproxy-wi.cfg is enough in order to import them in the new version?

**Comment by Aidaho12** [comment]
I'm afraid that it won't start anyway, backups will be needed to see what settings you had
